const make=(id,title,chineseTitle,grade,topic,intro,parts,words,quote,quoteZh)=>({id,title,chineseTitle,grade,difficulty:grade==='七年级'?'基础':grade==='八年级'?'进阶':'挑战',topic,minutes:5,intro,paragraphs:parts.map(([en,zh])=>({en,zh})),words,quote,quoteZh,collection:'主题拓展'});
export const expandedArticles=[
make('paper-crane','The Paper Crane by the Window','窗边的纸鹤','七年级','校园故事','一份安静的鼓励也能陪人走过困难。',[['A paper crane appeared on Emma’s desk before an important test. On one wing, someone had written, “Take one question at a time.”','一次重要考试前，艾玛的桌上出现了一只纸鹤。它的一侧翅膀上写着：“一次只解决一道题。”'],['The message slowed her racing heart. After the test, she folded another crane for a worried classmate.','这句话让她慌乱的心慢了下来。考试后，她又为紧张的同学折了一只纸鹤。'],['Encouragement had traveled without needing a name.','鼓励不需要名字，也能继续传递。']],[['crane','纸鹤'],['racing','急速跳动的'],['encouragement','鼓励']],'Encouragement can travel without a name.','鼓励不需要名字，也能继续传递。'),
make('old-bridge','The Bridge That Remembered','记得往事的桥','八年级','历史文化','古老建筑连接今天与过去。',[['An old stone bridge had stood above the river for three hundred years.','一座古老的石桥已在河上矗立三百年。'],['A historian showed students marks left by floods, repairs, and generations of builders.','历史学家向学生指出洪水、修缮和几代工匠留下的痕迹。'],['The bridge became a record written in stone.','这座桥成为写在石头上的记录。']],[['historian','历史学家'],['repair','修缮'],['generation','一代人']],'Old places are memories we can walk through.','古老的地方是我们可以走过的记忆。'),
make('orchestra-chair','The Empty Chair in the Orchestra','乐团里的空椅子','八年级','音乐艺术','合作需要为别人的声音留出空间。',[['During rehearsal, every player wanted to be heard, and few were truly listening.','排练时，每位演奏者都想被听见，却很少有人真正倾听。'],['The conductor said, “Music also lives in the space we leave for others.”','指挥说：“音乐也存在于我们为别人留下的空间里。”'],['They played again, and many instruments finally became one piece of music.','他们再次演奏，众多乐器终于汇成了一首完整的音乐。']],[['orchestra','管弦乐团'],['rehearsal','排练'],['conductor','指挥']],'Harmony begins when we listen.','和谐始于倾听。'),
make('moon-garden','The Garden Under the Moon','月光下的花园','七年级','自然观察','白天结束后，另一个世界才刚醒来。',[['Nina thought the garden slept at night until her grandfather took her outside.','妮娜以为花园在夜里会沉睡，直到爷爷带她走到户外。'],['White flowers opened, a moth rested on a leaf, and a hedgehog moved beneath the bushes.','白花开放，飞蛾停在叶上，刺猬穿过灌木。'],['Darkness was a different stage where other lives performed.','黑暗是其他生命登场的另一座舞台。']],[['moth','飞蛾'],['hedgehog','刺猬'],['curtain','幕布']],'Night is alive in another way.','夜晚以另一种方式充满生命。'),
make('lost-recipe','Grandmother’s Missing Recipe','奶奶遗失的食谱','七年级','家庭文化','味道也藏在共同度过的时间里。',[['When the recipe book disappeared, Jun worried that his grandmother’s special soup was lost forever.','食谱本不见后，俊担心奶奶的拿手汤会永远失传。'],['She asked him to cook beside her and judged the heat by listening to the pot.','奶奶请他一起下厨，并听着锅里的声音判断火候。'],['Jun learned what no recipe could hold: patience, attention, and stories.','俊学到了食谱无法容纳的东西：耐心、专注和故事。']],[['recipe','食谱'],['judge','判断'],['patience','耐心']],'Tradition lives in what we practice together.','传统存在于共同实践之中。'),
make('robot-mistake','The Robot That Made a Mistake','犯错的机器人','八年级','科技伦理','智慧也包括发现知识的边界。',[['The school robot sorted recycling quickly, but placed every blue object in the paper bin.','学校机器人快速分类回收物，却把所有蓝色物品都放进纸类箱。'],['The programmers discovered that its training examples were too simple.','程序员发现它的训练例子过于简单。'],['They taught it to ask when uncertain. A useful system must know its limits.','他们教它在不确定时询问。有用的系统必须知道自身边界。']],[['sort','分类'],['uncertain','不确定的'],['limit','边界']],'Intelligence includes knowing when to ask.','智慧包括知道何时应该询问。'),
make('rain-roof','A Roof That Saves Rain','会收集雨水的屋顶','八年级','绿色校园','好的设计让资源重新进入循环。',[['Students noticed how much clean water the school garden needed.','学生们注意到校园花园需要大量清水。'],['They designed tanks and filters to collect rain from the roof.','他们设计储水箱和过滤装置来收集屋顶雨水。'],['The project helped the school notice a resource always falling from the sky.','这个项目帮助学校发现了一种一直从天空落下的资源。']],[['tank','储水箱'],['filter','过滤装置'],['resource','资源']],'Good design helps us notice what we waste.','好的设计帮助我们看见被浪费的资源。'),
make('last-runner','The Last Runner','最后一名跑者','七年级','体育精神','坚持完成自己的比赛也是胜利。',[['When the fastest runners finished, Ravi was still far behind.','最快的选手完赛时，拉维还远远落后。'],['A teammate returned to run beside him, and others clapped with his steps.','一名队友回到跑道陪跑，其他人也随着他的步伐鼓掌。'],['The result showed his place; his final steps showed his character.','成绩显示了名次，最后的脚步展现了品格。']],[['track','跑道'],['rhythm','节奏'],['character','品格']],'A finish can reveal courage.','完成比赛能够展现勇气。'),
make('painting-label','The Label Beside the Painting','画作旁的说明牌','九年级','艺术思考','艺术是创作者与观看者故事的相遇。',[['Sofia saw a painting of an empty room and felt lonely.','索菲娅看见空房间的画，感到孤独。'],['The label said the artist had painted a peaceful place after years of noise.','说明牌写道，艺术家在多年喧嚣后画下了宁静空间。'],['The same room carried two different stories.','同一个房间承载着两个不同的故事。']],[['label','说明牌'],['peaceful','宁静的'],['viewer','观看者']],'Art is where two stories meet.','艺术是两个故事相遇之处。'),
make('familiar-smell','The Science of a Familiar Smell','熟悉气味里的科学','九年级','脑科学','气味为什么能突然打开久远记忆？',[['The smell of oranges brought Lina back to her childhood kitchen.','橙子的气味把莉娜带回童年厨房。'],['Smell signals travel through brain areas connected with emotion and memory.','嗅觉信号会经过与情绪和记忆相连的大脑区域。'],['The same orange may open a different memory for every person.','同一个橙子可能为每个人打开不同的记忆。']],[['signal','信号'],['emotion','情绪'],['memory','记忆']],'A scent can be a key inside the mind.','气味可以成为打开内心的钥匙。'),
make('one-minute','One Minute Before Replying','回复前的一分钟','八年级','情绪管理','暂停让我们有机会选择回应。',[['An angry message appeared on Theo’s phone, and he wrote an even angrier reply.','西奥收到令人恼火的消息，写下了更加愤怒的回复。'],['He waited one minute. During that minute, his breathing slowed.','他等待了一分钟，呼吸慢了下来。'],['He deleted half the words and asked a question instead.','他删掉一半的话，改为提出问题。']],[['reply','回复'],['delete','删除'],['conversation','对话']],'A pause creates space between feeling and action.','暂停在感受与行动之间创造空间。'),
make('shared-bike','The Bicycle Everyone Shared','大家共用的自行车','七年级','社区生活','公共物品需要共同责任。',[['The neighborhood bought bicycles that anyone could borrow. Soon, one tire was flat.','社区购买了任何人都能借用的自行车。不久，一只轮胎没气了。'],['People complained, but no one believed repairs were their job.','人们抱怨，却没人认为维修是自己的责任。'],['Students created a repair morning. “Everyone’s” began to mean “ours.”','学生设立维修日。“大家的”开始意味着“我们的”。']],[['borrow','借用'],['repair','维修'],['responsibility','责任']],'Shared ownership needs shared care.','共同所有需要共同爱护。'),
make('coral-city','A City Built by Tiny Animals','微小动物建造的城市','七年级','海洋生命','珊瑚礁是微小生命长期合作的成果。',[['A coral reef looks like a colorful underwater city, yet its builders are tiny polyps.','珊瑚礁像多彩的海底城市，建造者却是微小的珊瑚虫。'],['Generation after generation, they build homes for many sea creatures.','一代又一代，它们为许多海洋生物建造家园。'],['Protecting reefs means protecting an entire community.','保护珊瑚礁就是保护整个生命群落。']],[['reef','珊瑚礁'],['polyp','珊瑚虫'],['community','群落']],'Great cities can begin with tiny builders.','伟大的生命之城可由微小建造者创造。'),
make('word-no-twin','The Word That Had No Twin','没有双胞胎的词','九年级','语言文化','翻译在不同文化之间搭桥。',[['Mei found a word in a poem with no exact twin in English.','梅发现诗中一个词在英语里没有完全对应的表达。'],['It was an invitation to explain a different way of seeing the world.','这是一个解释不同世界观的邀请。'],['Translation lets readers notice the beautiful distance between languages.','翻译让读者看见语言之间美丽的距离。']],[['translate','翻译'],['exact','完全准确的'],['distance','距离']],'Translation builds a bridge without removing the river.','翻译架起桥梁，却不抹去河流。'),
make('dark-sky','The Town That Turned Off Its Lights','关掉灯光的小镇','八年级','环境保护','减少光污染能让星空重新出现。',[['For one night, a town turned off unnecessary lights.','一个夜晚，小镇关闭了不必要的灯光。'],['The Milky Way appeared, and night animals benefited from natural darkness.','银河出现了，夜行动物也从自然黑暗中受益。'],['Pollution can be too much of something useful in the wrong place.','污染可能只是有用之物在错误地点出现得太多。']],[['unnecessary','不必要的'],['benefit','受益'],['pollution','污染']],'We need light, but we also need darkness.','我们需要光，也需要黑暗。'),
make('things-library','A Library Without Books','没有书的图书馆','八年级','创新生活','图书馆也可以共享工具。',[['People borrowed drills, sewing machines, tents, and cake pans from this unusual library.','人们从这家特别的图书馆借电钻、缝纫机、帐篷和蛋糕模具。'],['Sharing saved money, reduced waste, and helped neighbors learn skills.','共享节省金钱、减少浪费，也帮助邻居学习技能。'],['A community grows stronger when resources are open to many people.','当资源向更多人开放时，社区会变得更强大。']],[['drill','电钻'],['reduce','减少'],['resource','资源']],'Sharing turns objects into opportunities.','共享让物品变成机会。'),
make('question-tree','The Tree of Questions','问题之树','七年级','科学思维','一个好问题会长出更多问题。',[['The teacher drew a tree and wrote, “Why do leaves change color?” on its trunk.','老师画了一棵树，并在树干上写下：“树叶为什么会变色？”'],['Each answer produced new branches and new questions.','每个答案都长出新的枝条和问题。'],['The students discovered the shape of curiosity.','学生们发现了好奇心的形状。']],[['trunk','树干'],['branch','树枝'],['curiosity','好奇心']],'Every strong question grows new branches.','有力量的问题会长出新的枝条。'),
make('future-letter','A Letter to My Future Self','写给未来自己的信','九年级','自我成长','成长是在变化中重新认识自己。',[['At fifteen, Hana wrote a letter to the person she would be at twenty-five.','十五岁时，花奈给二十五岁的自己写了一封信。'],['Ten years later, her plans had changed, but she still wished to be useful, brave, and kind.','十年后，计划已改变，但她仍希望成为有用、勇敢而善良的人。'],['A direction can remain even when the road changes.','道路会改变，方向却可以保留。']],[['promise','承诺'],['recognize','认出'],['direction','方向']],'The road may change while the direction remains.','道路可以改变，方向仍可保留。')
];
