const article=(id,title,chineseTitle,grade,topic,intro,parts,words,quote,quoteZh)=>({id,title,chineseTitle,grade,difficulty:grade==='七年级'?'基础':grade==='八年级'?'进阶':'挑战',topic,minutes:4,intro,paragraphs:parts.map(([en,zh])=>({en,zh})),words,quote,quoteZh,collection:'热门话题原创'});
export const hotTopicArticles=[
article('ai-teacher','Can AI Be a Good Teacher?','人工智能能成为好老师吗？','八年级','人工智能','工具可以给出答案，教育则帮助我们学会思考。',[
['AI can explain a math problem in seconds and repeat the explanation without becoming impatient. For many students, that makes learning easier.','人工智能能在几秒内解释数学题，也能不厌其烦地重复讲解，这让许多学生学得更轻松。'],['Yet a good teacher does more than provide information. A teacher notices confusion, encourages courage, and understands different kinds of silence.','然而，好老师不只提供信息。老师会发现困惑、鼓励勇气，也能理解不同含义的沉默。'],['AI may be a powerful learning partner, but students still need human care and their own judgment. Technology should support thinking, not replace it.','人工智能可以成为强大的学习伙伴，但学生仍需要人的关怀和自己的判断。技术应支持思考，而非取代思考。']],
[['impatient','不耐烦的'],['confusion','困惑'],['judgment','判断力']], 'Technology should support thinking, not replace it.','技术应当支持思考，而不是取代思考。'),
article('quiet-hour','The Power of One Quiet Hour','安静一小时的力量','七年级','学习方法','专注不是天赋，而是一种可以练习的能力。',[
['Lily often studied with five browser tabs open and her phone beside her notebook. She worked for hours but remembered very little.','莉莉学习时常开着五个网页标签，手机也放在笔记本旁。她学了很久，却记不住多少。'],['She began putting her phone in another room and choosing one clear task for forty minutes. At first, the silence felt uncomfortable. Soon, it became peaceful.','她开始把手机放到另一个房间，并在四十分钟内只完成一项任务。起初她不习惯安静，很快却感到平和。'],['One focused hour can be worth more than an afternoon of divided attention. Concentration grows each time we protect it.','专注的一小时，可能比注意力分散的一下午更有价值。每当我们保护专注力时，它都会成长。']],
[['task','任务'],['focused','专注的'],['concentration','专注力']], 'Concentration grows each time we protect it.','每当我们保护专注力时，它都会成长。'),
article('failure-data','What Failure Can Teach Us','失败能教会我们什么','八年级','成长','错误不是终点，也可以是一份有价值的数据。',[
['After losing a race, Ben wanted to hide his result. His coach asked him to study it: Where did his speed fall? When did his breathing change?','比赛失利后，本想藏起成绩。教练却请他研究：速度在哪里下降？呼吸何时发生变化？'],['The result stopped being an insult and became information. Ben changed his training and measured progress over months, not days.','这个结果不再是打击，而变成了信息。本改变了训练方式，并以月而不是以天衡量进步。'],['Failure hurts when it closes a door. It helps when it shows us where the door is and what key we still need.','失败关上一扇门时会令人难过；但当它指出门在哪里、我们还需要怎样的钥匙时，也能带来帮助。']],
[['result','结果'],['measure','衡量'],['progress','进步']], 'Failure can become information.','失败可以变成有价值的信息。'),
article('phone-mirror','The Mirror in the Phone','手机里的镜子','九年级','网络生活','社交媒体展示的是生活片段，而不是生活全貌。',[
['Online, everyone seemed to be traveling, winning prizes, or laughing with friends. Looking at the pictures, Kai felt that his ordinary life was too small.','网络上，每个人似乎都在旅行、获奖或与朋友欢笑。看着那些照片，凯觉得自己的普通生活太不起眼。'],['Then he remembered that he also posted only his best moments. The screen was a wall covered with carefully chosen pictures, not a window into complete lives.','后来他想起，自己也只发布最好的时刻。屏幕是一面贴满精选照片的墙，而不是观察完整人生的窗。'],['Comparison is unfair when we compare our whole story with another person’s best page. A picture is a moment, not a whole life.','拿自己的完整故事与别人最精彩的一页相比并不公平。一张照片只是一个瞬间，而不是完整人生。']],
[['ordinary','普通的'],['complete','完整的'],['comparison','比较']], 'A picture is a moment, not a whole life.','一张照片只是一个瞬间，而不是完整的人生。'),
article('future-jobs','Jobs That Do Not Exist Yet','尚未出现的职业','九年级','未来职业','未来需要的不只是已有答案，更是学习新事物的能力。',[
['Some of tomorrow’s jobs have not been invented. Twenty years ago, few students planned to become app designers or drone engineers.','有些未来职业尚未出现。二十年前，很少有学生计划成为应用设计师或无人机工程师。'],['Good planning now means more than learning one tool. Curiosity, communication, and the ability to learn may last longer than any technology.','今天的良好规划不只是学会一种工具。好奇心、沟通力和学习能力可能比任何技术都更持久。'],['We cannot prepare for every job title. We can prepare to meet change with useful skills and an open mind.','我们无法为每一个职业名称做准备，却可以培养实用能力和开放心态，以迎接变化。']],
[['invent','发明'],['communication','沟通'],['prepare','准备']], 'Prepare for change, not only for a title.','要为变化做好准备，而不只是为一个职业名称。'),
article('small-habits','Why Small Habits Win','微习惯为什么有效','七年级','生活智慧','每天进步一点，比偶尔努力很多更可靠。',[
['Noah planned to finish a book every week. The exciting but heavy plan lasted only three days.','诺亚计划每周读完一本书。这个令人兴奋却过于沉重的计划只坚持了三天。'],['He started again with ten pages each night. It seemed almost too easy, which was exactly why he could continue on busy days.','他重新开始，每晚只读十页。它似乎简单得过头，却正因如此，他在忙碌的日子也能坚持。'],['A small habit is a vote for the person we want to become. One vote changes little, but hundreds create a clear result.','一个微小习惯，是为我们想成为的人投出的一票。一票改变不大，但数百票会产生清晰的结果。']],
[['habit','习惯'],['continue','继续'],['result','结果']], 'Make a habit small enough to repeat.','让习惯小到足以重复。'),
article('kind-disagreement','How to Disagree Kindly','如何友善地表达不同意见','八年级','沟通','不同意见不必变成彼此攻击。',[
['During a discussion, Maya heard an opinion she strongly disliked. Before replying, she asked, “What experience led you to that view?”','讨论中，玛雅听到了一个非常不赞同的观点。回应前，她问：“什么经历让你产生这个看法？”'],['The question did not make them agree. It made both students explain their reasons instead of questioning each other’s character.','这个问题没有让他们达成一致，却让双方解释理由，而不是质疑彼此的人品。'],['Respectful disagreement is not weakness. It protects truth and the relationship at the same time.','尊重地表达不同意见并非软弱。它能同时维护事实与关系。']],
[['opinion','观点'],['character','品格'],['respectful','尊重他人的']], 'Challenge the idea without attacking the person.','质疑观点，但不要攻击表达观点的人。'),
article('alone-crowd','Alone in a Crowd','人群中的孤独','九年级','心理成长','被许多人看见，不等于被真正理解。',[
['A person can receive a hundred messages and still feel lonely. Connection is not counted only by how many people know our name.','一个人可能收到上百条消息，却依然孤独。联系的深浅，不只取决于多少人知道我们的名字。'],['Real friendship needs attention, honesty, and time. These qualities are slower than clicking a like button, but they reach much deeper.','真正的友谊需要关注、坦诚和时间。这些品质比点赞慢得多，却能抵达更深的地方。'],['When loneliness appears, one honest conversation may help more than another hour of scrolling.','孤独出现时，一次真诚的交谈可能比再刷一小时屏幕更有帮助。']],
[['connection','联系'],['honesty','坦诚'],['scroll','滚动浏览']], 'To be noticed is not always to be known.','被人注意，并不总意味着被人理解。'),
article('plastic-journey','The Journey of a Plastic Bottle','塑料瓶的旅程','七年级','环保','我们扔掉的东西，并不会真正消失。',[
['A bottle beside a road may be carried by rain into a river and finally into the sea. Its short use can begin a journey lasting hundreds of years.','路边的塑料瓶可能被雨水带进河流，最后进入海洋。短暂的使用会开启一段持续数百年的旅程。'],['Sunlight breaks plastic into smaller pieces but does not make it disappear. Tiny pieces can enter the bodies of fish and birds.','阳光会把塑料分解成更小的碎片，却无法让它消失。微小碎片可能进入鱼类和鸟类的身体。'],['Using less, reusing, and recycling correctly can change where the bottle’s journey ends.','减少使用、重复利用并正确回收，能够改变塑料瓶旅程的终点。']],
[['lasting','持续的'],['tiny','微小的'],['recycle','回收']], 'There is no real “away” when we throw something away.','当我们扔掉东西时，并不存在真正的“消失”。'),
article('mars-home','Should Humans Live on Mars?','人类应该移居火星吗？','九年级','太空探索','探索新世界，也会让我们重新认识自己的家园。',[
['Mars attracts us because it is both near and mysterious. Living there could teach us about survival and the history of our solar system.','火星吸引我们，因为它相对接近又充满神秘。居住在那里能让我们学习生存和太阳系的历史。'],['But Mars has no air we can breathe and little protection from radiation. Every glass of water and breath would depend on technology.','但火星没有可供呼吸的空气，也几乎无法抵御辐射。每一杯水和每一次呼吸都将依赖技术。'],['Perhaps the greatest lesson of Mars is how rare Earth is. Exploring another planet should increase our care for this one.','也许火星最大的启示，是地球何其珍贵。探索另一颗星球，应让我们更珍惜这一颗。']],
[['mysterious','神秘的'],['survival','生存'],['radiation','辐射']], 'Looking outward can teach us to value home.','向外探索，能教会我们珍惜家园。'),
article('money-happiness','Can Money Buy Happiness?','金钱能买到幸福吗？','八年级','人生思考','金钱能解决许多问题，却不能回答所有问题。',[
['Money can buy food, medicine, safety, and time. When these needs are missing, enough money can greatly improve life.','金钱可以买到食物、药品、安全和时间。当这些需求缺失时，足够的金钱能极大改善生活。'],['Beyond basic comfort, more possessions do not always create deeper happiness. Trust, purpose, health, and belonging cannot simply be ordered.','在基本舒适之外，更多物品并不总能创造更深的幸福。信任、目标、健康和归属感无法直接订购。'],['Money is a useful tool, not a complete map of a good life. Wisdom is knowing what it can buy and what must be built differently.','金钱是有用的工具，却不是美好生活的完整地图。智慧在于明白什么能买到，什么必须以其他方式建立。']],
[['possession','所有物'],['purpose','目标感'],['wisdom','智慧']], 'Money is a tool, not the meaning of life.','金钱是工具，而不是生活的意义。'),
article('sleep-learn','Why Sleep Helps Us Learn','睡眠为什么帮助学习','七年级','健康','休息不是学习的敌人，而是学习过程的一部分。',[
['While we sleep, the brain sorts information, strengthens useful memories, and clears away some of the day’s mental noise.','睡眠时，大脑会整理信息、加强有用记忆，并清除白天的一部分思维杂音。'],['Studying very late may create more reading time, but a tired brain pays less attention and remembers less.','学习到很晚也许增加了阅读时间，但疲惫的大脑注意力更弱，记住的内容也更少。'],['Good learning needs effort and recovery. Closing a book at the right time can be the smartest study decision.','有效学习既需要努力，也需要恢复。在合适的时候合上书，有时正是最明智的决定。']],
[['strengthen','加强'],['mental','思维的'],['recovery','恢复']], 'Rest is part of learning.','休息是学习的一部分。'),
article('check-news','Before You Share','转发之前','九年级','媒介素养','在信息传播越来越快时，停下来核实是一种责任。',[
['A surprising headline can travel around a school in minutes. Strong emotion makes people share before asking whether the story is true.','一个惊人的标题能在几分钟内传遍校园。强烈情绪让人们在判断真假前就转发。'],['Careful readers look for the original source, date, evidence, and reports from other reliable places. They separate facts from opinions.','谨慎的读者会寻找原始来源、日期、证据和其他可靠报道，也会区分事实与观点。'],['Pausing may feel slow, but correcting false information later is much harder. In a fast network, thoughtful delay is useful.','停下来似乎很慢，但事后纠正虚假信息更困难。在高速网络中，审慎的延迟很有用。']],
[['headline','标题'],['evidence','证据'],['reliable','可靠的']], 'Check first; share second.','先核实，再转发。'),
article('own-success','Your Own Definition of Success','你自己的成功定义','九年级','人生思考','如果从不定义成功，我们就容易追逐别人的答案。',[
['Success is often shown as a high score, a famous school, or an impressive job. These achievements do not fit every person in the same way.','成功常被描述成高分、名校或令人羡慕的工作，但这些成就并不以同样方式适合每个人。'],['One person may value discovery, another service, creativity, family, or peace. A meaningful goal should reflect our values, not only win applause.','有人重视探索，有人重视服务、创造、家庭或平静。有意义的目标应反映价值观，而不只为赢得掌声。'],['We can learn from other people’s paths without borrowing their destination. Growing up includes deciding what a good life means to us.','我们可以借鉴别人的道路，却不必借用他们的终点。成长也包括决定美好生活对自己意味着什么。']],
[['achievement','成就'],['reflect','反映'],['applause','掌声']], 'Learn from another path; choose your own destination.','借鉴别人的道路，选择自己的终点。')
];
