package learning

import (
	"path/filepath"

	"github.com/kataras/iris/v12"
)

func RegisterRoutes(app *iris.Application, controller *Controller, root string) {
	api := app.Party("/api")
	api.Get("/health", controller.Health)
	api.Post("/auth/register", controller.Register)
	api.Post("/auth/login", controller.Login)
	api.Post("/auth/logout", controller.Logout)
	api.Get("/auth/me", controller.Me)
	api.Post("/auth/change-password", controller.ChangePassword)
	api.Use(requireAuth)
	admin := api.Party("/admin", requireAdmin)
	admin.Get("/users", controller.AdminUsers)
	admin.Get("/overview", controller.AdminOverview)
	admin.Put("/users/{id:string}", controller.AdminUpdateUser)
	admin.Post("/users/{id:string}/reset-password", controller.AdminResetPassword)
	admin.Post("/import/articles", controller.ImportArticles)
	admin.Post("/import/words", controller.ImportWords)
	admin.Get("/words", controller.AdminWords)
	admin.Post("/words", controller.AdminSaveWord)
	admin.Put("/words/{id:string}", controller.AdminSaveWord)
	admin.Delete("/words/{id:string}", controller.AdminDeleteWord)
	admin.Get("/articles", controller.AdminArticles)
	admin.Post("/articles", controller.AdminSaveArticle)
	admin.Put("/articles/{id:string}", controller.AdminSaveArticle)
	admin.Delete("/articles/{id:string}", controller.AdminDeleteArticle)
	admin.Get("/content/versions/{contentType:string}/{id:string}", controller.AdminContentVersions)
	admin.Post("/content/versions/{contentType:string}/{id:string}/{version:string}/restore", controller.AdminRestoreContentVersion)
	admin.Get("/exams", controller.AdminExams)
	admin.Post("/exams", controller.AdminSaveExam)
	admin.Put("/exams/{id:string}", controller.AdminSaveExam)
	admin.Delete("/exams/{id:string}", controller.AdminDeleteExam)
	admin.Post("/import/exams", controller.AdminImportExams)
	admin.Get("/agent/config", controller.AdminAgentConfig)
	admin.Put("/agent/config", controller.AdminSaveAgentConfig)
	admin.Post("/agent/test", controller.AdminTestAgent)
	admin.Get("/factory/tasks", controller.FactoryTasks)
	admin.Get("/factory/overview", controller.FactoryOverview)
	admin.Get("/factory/schedules", controller.FactorySchedules)
	admin.Post("/factory/schedules", controller.FactorySaveSchedule)
	admin.Post("/factory/tasks", controller.FactoryCreateTask)
	admin.Post("/factory/tasks/{id:string}/process", controller.FactoryProcessTask)
	admin.Post("/factory/tasks/{id:string}/retry", controller.FactoryRetryTask)
	admin.Get("/factory/tasks/{id:string}/events", controller.FactoryTaskEvents)
	admin.Get("/factory/drafts/{id:string}", controller.FactoryDraft)
	admin.Put("/factory/drafts/{id:string}", controller.FactorySaveDraft)
	admin.Post("/factory/drafts/{id:string}/publish", controller.FactoryPublishDraft)
	admin.Get("/factory/batches", controller.FactoryBatches)
	admin.Post("/factory/batches/{id:string}/rollback", controller.FactoryRollbackBatch)
	admin.Get("/homeworks", controller.AdminHomeworks)
	admin.Post("/homeworks", controller.AdminSaveHomework)
	admin.Get("/homeworks/{id:string}/submissions", controller.AdminHomeworkSubmissions)
	admin.Post("/homeworks/{id:string}/submissions/{userId:string}/ai-grade", controller.AdminAIGradeHomework)
	admin.Put("/homeworks/{id:string}/submissions/{userId:string}/grade", controller.AdminConfirmHomeworkGrade)
	api.Get("/stats", controller.Stats)
	api.Get("/dashboard", controller.Dashboard)
	api.Get("/learning/profile", controller.LearningProfile)
	api.Get("/learning/plan", controller.SmartLearningPlan)
	api.Post("/learning/plan/regenerate", controller.RegenerateSmartLearningPlan)
	api.Post("/learning/plan/tasks/{id:string}/complete", controller.CompleteSmartLearningTask)
	api.Get("/learning/events", controller.LearningEvents)
	api.Get("/settings", controller.Settings)
	api.Post("/settings", controller.SaveSettings)
	api.Get("/content-status", controller.ContentStatus)
	api.Get("/articles", controller.Articles)
	api.Get("/article-progress", controller.ArticleProgress)
	api.Post("/article-progress", controller.SaveArticleProgress)
	api.Get("/articles/{id:string}", controller.Article)
	api.Get("/words", controller.Words)
	api.Get("/word-facets", controller.WordFacets)
	api.Get("/words/{id:path}", controller.Word)
	api.Get("/quiz", controller.Quiz)
	api.Post("/quiz/answer", controller.AnswerQuiz)
	api.Get("/progress", controller.Progress)
	api.Post("/progress/{id:path}", controller.SaveProgress)
	api.Get("/mistakes", controller.Mistakes)
	api.Post("/mistakes/{id:string}/resolve", controller.ResolveMistake)
	api.Get("/review/today", controller.TodayReview)
	api.Get("/exams", controller.Exams)
	api.Get("/exams/attempts", controller.ExamAttempts)
	api.Post("/exams/submit", controller.SubmitExam)
	api.Get("/exams/{id:string}", controller.Exam)
	api.Get("/agent/status", controller.AgentStatus)
	api.Post("/agent/chat", controller.AgentChat)
	api.Get("/homeworks", controller.MyHomeworks)
	api.Post("/homeworks/{id:string}/submit", controller.SubmitHomework)
	app.HandleDir("/", filepath.Join(root, "web"))
}
