// 小学基础语法知识卡
// ---------------------------------------------------------------------------
// 面向小学阶段（三～六年级）的入门语法，形态与 topics.js 的初中专题一致：
//   speed 卡（forms）、用法要点（points 的 good/bad 例句）、易错提醒（pitfalls）、
//   记忆卡（memoryCard）。区别只在 kind: "card" —— 知识卡没有真题与讲义，
//   渲染层据此隐藏「讲义精讲 / 专项练习」两块，只显示速查与要点。
// 导航分组：ia.js 的 primary 组（小学基础），在页面里排在最前。
// 数据来源：人教版 PEP 三～六年级教材语法项目，按「先形式、后用法、再易错」排列。

export const primaryGrammarCards = [
  {
    id: "p-be-verb",
    title: "be 动词（am / is / are）",
    short: "be 动词",
    kind: "card",
    category: "小学基础",
    difficulty: 1,
    summary: "be 动词是小学英语的第一块砖：我用 am，你用 are，is 连着他她它。先分清主语是谁，再选对 be 动词。",
    forms: [
      { name: "第一人称单数", pattern: "I + am", note: "I am a student. 缩写 I'm。" },
      { name: "第三人称单数", pattern: "he / she / it + is", note: "He is my friend. 缩写 He's。" },
      { name: "其他所有人称", pattern: "you / we / they + are", note: "You are kind. 缩写 You're。" },
      { name: "否定与疑问", pattern: "be + not；be 提到句首", note: "I am not late. / Are you ready?" },
    ],
    points: [
      {
        title: "先找主语，再定 be 动词",
        desc: "主语是 I 用 am；主语是 he / she / it 或一个人、一件东西用 is；主语是 you / we / they 或不止一个人用 are。",
        good: ["I am nine years old.", "She is my English teacher.", "They are in the playground."],
        bad: ["I is nine years old.", "They is in the playground."],
      },
      {
        title: "be 动词后面跟名词或形容词",
        desc: "be 动词表示「是、在、怎么样」，后面常接名词（身份）、形容词（状态）或地点。",
        good: ["This is my schoolbag.", "The flowers are beautiful.", "My book is on the desk."],
        bad: ["This my schoolbag.", "The flowers beautiful."],
      },
      {
        title: "否定句和一般疑问句都改 be 动词",
        desc: "否定在 be 后面加 not；疑问把 be 提到主语前面，句末加问号。",
        good: ["He is not my brother.", "Is she your sister?"],
        bad: ["He not is my brother.", "She is your sister?"],
      },
    ],
    pitfalls: [
      "am / is / are 不能与实义动词一起用：错 I am like apples，对 I like apples。",
      "缩写要认：I'm / you're / he's / isn't / aren't，回答 Yes, I am. 不能缩写。",
      "回答 Is this your pen? 要用 Yes, it is. / No, it isn't.，不要用 Yes, this is.",
    ],
    memoryCard: ["我用 am，你用 are，is 连着他她它。", "单数 is，复数 are。"],
  },
  {
    id: "p-personal-pronoun",
    title: "人称代词与物主代词",
    short: "代词",
    kind: "card",
    category: "小学基础",
    difficulty: 2,
    summary: "用代词代替人或物，句子才不啰嗦。重点记住两对：主格 / 宾格，形容词性物主代词 / 名词性物主代词。",
    forms: [
      { name: "主格", pattern: "I / you / he / she / it / we / they", note: "放在动词前面，作主语。" },
      { name: "宾格", pattern: "me / you / him / her / it / us / them", note: "放在动词或介词后面。" },
      { name: "形容词性物主代词", pattern: "my / your / his / her / its / our / their + 名词", note: "后面必须跟名词。" },
      { name: "名词性物主代词", pattern: "mine / yours / his / hers / its / ours / theirs", note: "后面不再跟名词。" },
    ],
    points: [
      {
        title: "动词前面用主格，后面用宾格",
        desc: "主语位置用主格；动词后面、介词后面用宾格。",
        good: ["I like English.", "Please help me.", "Look at him."],
        bad: ["Me like English.", "Please help I."],
      },
      {
        title: "形容词性物主代词后一定带名词",
        desc: "表示「……的」，要带上被修饰的名词；不带名词时改用名词性物主代词。",
        good: ["This is my pencil.", "Her dress is new.", "The red pen is mine."],
        bad: ["This is my.（想说「这是我的」用 mine）", "This book is her."],
      },
      {
        title: "并列时 I 放在后面",
        desc: "说「我和……」，英语习惯把自己放在最后。",
        good: ["My friends and I play football.", "You and I are good friends."],
        bad: ["I and my friends play football."],
      },
    ],
    pitfalls: [
      "its 是「它的」，it's 是「它是」，两个写法只差一个撇号，意思完全不同。",
      "并列主语用主格（My friends and I），并列宾语用宾格（between you and me）。",
      "his 既是形容词性也是名词性：This is his book. / This book is his.",
    ],
    memoryCard: ["主格作主，宾格作宾。", "有名词用形容词性，没名词用名词性。"],
  },
  {
    id: "p-noun-plural",
    title: "名词单复数",
    short: "单复数",
    kind: "card",
    category: "小学基础",
    difficulty: 2,
    summary: "英语里「一个」和「多个」写法不同。记住三类变化：直接加 -s、加 -es、特殊变化。",
    forms: [
      { name: "一般情况", pattern: "名词 + s", note: "book → books，pen → pens。" },
      { name: "s / x / sh / ch / o 结尾", pattern: "名词 + es", note: "bus → buses，box → boxes，watch → watches，tomato → tomatoes。" },
      { name: "辅音字母 + y 结尾", pattern: "变 y 为 i 再加 es", note: "baby → babies，city → cities。" },
      { name: "不规则变化", pattern: "特殊记忆", note: "man → men，child → children，foot → feet，mouse → mice。" },
    ],
    points: [
      {
        title: "数量词决定单复数",
        desc: "one / a / an 后用单数；two、three、many、some 等后面用复数。",
        good: ["I have two books.", "There are many apples here.", "one apple / two apples"],
        bad: ["I have two book.", "There are many apple here."],
      },
      {
        title: "辅音字母 + y 要先变 i",
        desc: "元音字母（a / e / i / o / u）+ y 直接加 s：boy → boys，day → days。",
        good: ["baby → babies", "boy → boys", "day → days"],
        bad: ["baby → babys", "boy → boies"],
      },
      {
        title: "不可数名词没有复数",
        desc: "water、rice、bread、milk、juice 等不可数，不能加 s，要借量词表示数量。",
        good: ["a glass of water", "two pieces of bread"],
        bad: ["two waters", "three breads"],
      },
    ],
    pitfalls: [
      "three 后面必须跟复数：three books（不是 three book）。",
      "sheep、fish、deer 单复数同形，不能写成 sheeps。",
      "有些词加了 s 意思会变：chicken（鸡肉）与 chickens（小鸡）。",
    ],
    memoryCard: ["一般加 s，s / x / sh / ch 加 es。", "辅音 + y 变 i 加 es。"],
  },
  {
    id: "p-article",
    title: "冠词 a / an / the",
    short: "冠词",
    kind: "card",
    category: "小学基础",
    difficulty: 2,
    summary: "a 和 an 用于「第一次提到的一个」，the 用于「双方都知道的、唯一的」。先听读音，再决定用 a 还是 an。",
    forms: [
      { name: "辅音音素开头", pattern: "a + 辅音音素", note: "a book，a pen，a university（发音 /j/）。" },
      { name: "元音音素开头", pattern: "an + 元音音素", note: "an apple，an egg，an hour（h 不发音）。" },
      { name: "特指", pattern: "the + 名词", note: "第二次提到、或明确指某一个。" },
      { name: "不用冠词", pattern: "复数泛指 / 不可数泛指", note: "I like apples. / We drink water." },
    ],
    points: [
      {
        title: "看发音，不看字母",
        desc: "a 和 an 取决于后面单词开头的音素：元音音素用 an，辅音音素用 a。",
        good: ["an orange", "an English book", "a useful book", "an hour"],
        bad: ["a orange", "an useful book"],
      },
      {
        title: "第一次用 a / an，第二次用 the",
        desc: "第一次提到某人某物用 a / an；再提到同一个时改用 the。",
        good: ["I have a cat. The cat is white."],
        bad: ["I have a cat. A cat is white."],
      },
      {
        title: "世界上唯一的、最高级的用 the",
        desc: "the sun、the moon、the earth、the Great Wall，以及最高级前用 the。",
        good: ["The sun is big.", "He is the tallest in our class."],
        bad: ["Sun is big."],
      },
    ],
    pitfalls: [
      "an 不是「元音字母开头」的意思：an hour 的 h 不发音，读元音开头。",
      "球类运动、三餐、学科前一般不用冠词：play basketball、have breakfast、like maths。",
      "乐器前要用 the：play the piano、play the violin。",
    ],
    memoryCard: ["元音音素用 an，辅音音素用 a。", "第一次 a / an，再提到 the。"],
  },
  {
    id: "p-demonstrative",
    title: "this / that / these / those",
    short: "指示代词",
    kind: "card",
    category: "小学基础",
    difficulty: 1,
    summary: "指东西先看两件事：离得近还是远，一个还是多个。四个词就是这两条线的组合。",
    forms: [
      { name: "近处单数", pattern: "this", note: "This is my book." },
      { name: "近处复数", pattern: "these", note: "These are my books." },
      { name: "远处单数", pattern: "that", note: "That is his pen." },
      { name: "远处复数", pattern: "those", note: "Those are his pens." },
    ],
    points: [
      {
        title: "看距离：近的用 this / these，远的用 that / those",
        desc: "用手能指到的用 this / these；离得远的用 that / those。",
        good: ["This is my seat. That is yours.", "These apples are fresh. Those are old."],
        bad: ["This are my books."],
      },
      {
        title: "单数配 is，复数配 are",
        desc: "this / that 后面用 is；these / those 后面用 are。",
        good: ["That is a map.", "Those are my friends."],
        bad: ["Those is my friends."],
      },
      {
        title: "回答时用 it 或 they",
        desc: "问 Is this your ruler? 答 Yes, it is.；问 Are these your books? 答 Yes, they are.",
        good: ["Are these your books? Yes, they are."],
        bad: ["Are these your books? Yes, these are."],
      },
    ],
    pitfalls: [
      "these / those 是复数，不能接单数名词：these book 是错的。",
      "打电话时用 this 介绍自己，用 that 问对方是谁。",
    ],
    memoryCard: ["近 this / these，远 that / those。", "单数 is，复数 are。"],
  },
  {
    id: "p-present-simple",
    title: "一般现在时与第三人称单数",
    short: "一般现在时",
    kind: "card",
    category: "小学基础",
    difficulty: 3,
    summary: "一般现在时表示经常发生的事、习惯和事实。主语是第三人称单数时，动词要「变身」，这是小学生最容易丢分的地方。",
    forms: [
      { name: "一般情况", pattern: "主语 + 动词原形", note: "I go to school on foot." },
      { name: "第三人称单数", pattern: "he / she / it + 动词 + s", note: "He goes to school by bus." },
      { name: "动词变化规则", pattern: "+s / +es / 变 y 为 i 加 es / have → has", note: "plays / watches / studies / has。" },
      { name: "否定与疑问", pattern: "don't / doesn't + 动词原形", note: "He doesn't like milk. / Does she dance?" },
    ],
    points: [
      {
        title: "第三人称单数动词要加 s",
        desc: "主语是 he、she、it 或一个人、一件东西时，动词要加 s 或 es。",
        good: ["My father works in a hospital.", "She studies English every day.", "It has a long tail."],
        bad: ["My father work in a hospital.", "She study English every day."],
      },
      {
        title: "否定和疑问用助动词，动词回原形",
        desc: "第三人称单数用 doesn't / does，动词必须回到原形，s 已经跑到助动词上了。",
        good: ["He doesn't play football.", "Does she like apples?"],
        bad: ["He doesn't plays football.", "Does she likes apples?"],
      },
      {
        title: "常和频率词一起出现",
        desc: "always、usually、often、sometimes、never、every day 是一般现在时的信号词。",
        good: ["I usually get up at six.", "We have PE class twice a week."],
        bad: ["I usually am get up at six."],
      },
    ],
    pitfalls: [
      "does 后面动词还原：Does he go...（不是 Does he goes...）。",
      "have 的第三人称单数是 has，不是 haves。",
      "动词加 s 的读音有三种：/s/、/z/、/ɪz/，读句子要跟读录音纠正。",
    ],
    memoryCard: ["经常做的事用一般现在时。", "三单动词加 s，does 后面回原形。"],
  },
  {
    id: "p-present-continuous",
    title: "现在进行时",
    short: "现在进行时",
    kind: "card",
    category: "小学基础",
    difficulty: 3,
    summary: "现在进行时表示「现在这一刻正在做」。公式只有一句话：be + 动词 ing，两个都不能少。",
    forms: [
      { name: "肯定句", pattern: "主语 + am / is / are + 动词 ing", note: "She is reading a book." },
      { name: "否定句", pattern: "be + not + 动词 ing", note: "They are not sleeping." },
      { name: "疑问句", pattern: "be 提到主语前", note: "Are you listening to me?" },
      { name: "动词 ing 规则", pattern: "+ing / 去 e 加 ing / 双写末尾字母加 ing", note: "playing / writing / running。" },
    ],
    points: [
      {
        title: "be 和 ing 一个都不能少",
        desc: "进行时是 be + ing 的组合，少了 be 或少了 ing 都是错句。",
        good: ["I am drawing a picture.", "Look! The birds are flying."],
        bad: ["I drawing a picture.", "Look! The birds flying."],
      },
      {
        title: "看见 Look! / Listen! / now 就用进行时",
        desc: "这些词提示动作正在发生，是进行时的常见信号。",
        good: ["Listen! Someone is singing.", "What are you doing now?"],
        bad: ["Listen! Someone sings."],
      },
      {
        title: "重读闭音节要双写末尾字母",
        desc: "run → running，swim → swimming，put → putting（最后三个字母是辅音 + 元音 + 辅音）。",
        good: ["He is running.", "They are swimming."],
        bad: ["He is runing.", "They are swiming."],
      },
    ],
    pitfalls: [
      "以不发音 e 结尾的动词先去 e：write → writing，dance → dancing。",
      "like、know、want 这类表示状态或感觉的词一般不用进行时：I like it.（不说 I am liking it.）",
      "进行时与一般现在时别混：every day 用一般现在时，now 用进行时。",
    ],
    memoryCard: ["正在进行：be + ing。", "Look、Listen、now 是信号词。"],
  },
  {
    id: "p-there-be",
    title: "There be 句型",
    short: "There be",
    kind: "card",
    category: "小学基础",
    difficulty: 3,
    summary: "「某处有某物」用 There be，而不是 have。is 还是 are，看紧跟其后的第一个名词。",
    forms: [
      { name: "单数 / 不可数", pattern: "There is + 单数名词 / 不可数名词", note: "There is a book on the desk." },
      { name: "复数", pattern: "There are + 复数名词", note: "There are two books on the desk." },
      { name: "否定与疑问", pattern: "There is / are + not；be 提到 there 前", note: "There aren't any cats. / Are there any apples?" },
      { name: "就近原则", pattern: "看 be 后面的第一个名词", note: "There is a pen and two books." },
    ],
    points: [
      {
        title: "is 还是 are 看后面第一个名词",
        desc: "紧跟 be 的名词是单数用 is，是复数用 are，这叫「就近原则」。",
        good: ["There is a cat and two dogs.", "There are two dogs and a cat."],
        bad: ["There are a cat and two dogs."],
      },
      {
        title: "There be 表示「有」的存在，have 表示「拥有」",
        desc: "桌上有一本书用 There is；我有一本书用 I have。别把两者混用。",
        good: ["There is a map on the wall.", "I have a new bike."],
        bad: ["The wall has a map.", "There is I have a new bike."],
      },
      {
        title: "疑问和否定都改 be 动词",
        desc: "疑问把 is / are 提到 there 前面；否定在 be 后加 not。",
        good: ["Is there a park near here?", "There aren't any birds in the tree."],
        bad: ["There is a park near here?", "There not is a park."],
      },
    ],
    pitfalls: [
      "名词前用 some 时，否定和疑问里改成 any：There are some apples. → Are there any apples?",
      "There be 后面不能接动词原形：错 There is a boy play，对 There is a boy playing.",
      "回答 Is there...? 用 Yes, there is. / No, there isn't.，不要用 Yes, it is.",
    ],
    memoryCard: ["某处有某物：There be。", "单数 is，复数 are，看后面第一个名词。"],
  },
  {
    id: "p-can",
    title: "情态动词 can",
    short: "can",
    kind: "card",
    category: "小学基础",
    difficulty: 2,
    summary: "can 表示「能、会、可以」。它最大的特点是：后面永远跟动词原形，自己也不随人称变化。",
    forms: [
      { name: "肯定句", pattern: "主语 + can + 动词原形", note: "I can swim." },
      { name: "否定句", pattern: "can + not = can't", note: "He can't dance." },
      { name: "疑问句", pattern: "Can 提到主语前", note: "Can you help me?" },
      { name: "回答", pattern: "Yes, I can. / No, I can't.", note: "两个 can 都不变。" },
    ],
    points: [
      {
        title: "can 后面永远跟动词原形",
        desc: "can 是情态动词，后面的动词不加 s、不加 ing、不加 ed。",
        good: ["She can play the piano.", "We can go there by bus."],
        bad: ["She can plays the piano.", "We can going there."],
      },
      {
        title: "can 不随主语变化",
        desc: "不管主语是 I 还是 he，can 的写法都一样，也不需要助动词。",
        good: ["He can swim. / They can swim.", "I can't swim."],
        bad: ["He cans swim.", "He doesn't can swim."],
      },
      {
        title: "can 还能表示「请求许可」",
        desc: "Can I...? 是礼貌的请求，回答常用 Sure. / Of course. / Sorry, you can't.",
        good: ["Can I use your ruler?", "Can you pass me the book, please?"],
        bad: ["Can I to use your ruler?"],
      },
    ],
    pitfalls: [
      "can 没有第三人称单数形式，不能写 cans。",
      "can't 是 cannot 的缩写，不是 can not 的随意拼写。",
      "「会弹钢琴」是 play the piano，乐器前要有 the。",
    ],
    memoryCard: ["can 后面跟原形。", "can 不随人称变，否定是 can't。"],
  },
  {
    id: "p-past-simple-intro",
    title: "一般过去时初步",
    short: "一般过去时",
    kind: "card",
    category: "小学基础",
    difficulty: 4,
    summary: "说昨天、上周发生的事要用过去时：动词要变成过去式。规则变化加 -ed，不规则变化要单独记。",
    forms: [
      { name: "规则变化", pattern: "动词 + ed", note: "play → played，watch → watched。" },
      { name: "不规则变化", pattern: "特殊记忆", note: "go → went，eat → ate，see → saw，buy → bought。" },
      { name: "be 动词过去式", pattern: "am / is → was，are → were", note: "I was at home. They were happy." },
      { name: "否定与疑问", pattern: "didn't / did + 动词原形", note: "He didn't go. / Did you see it?" },
    ],
    points: [
      {
        title: "先找时间词，再决定时态",
        desc: "yesterday、last weekend、two days ago、just now 都是一般过去时的信号。",
        good: ["I visited my grandma last weekend.", "We went to the zoo yesterday."],
        bad: ["I visit my grandma last weekend."],
      },
      {
        title: "did 后面动词回原形",
        desc: "否定和疑问里用了 did / didn't，后面的动词必须是原形，过去的意思已经由 did 表达了。",
        good: ["She didn't watch TV last night.", "Did you play football yesterday?"],
        bad: ["She didn't watched TV.", "Did you played football?"],
      },
      {
        title: "be 动词的过去式单独记",
        desc: "was 配 I / he / she / it，were 配 you / we / they。",
        good: ["I was tired yesterday.", "They were at the park."],
        bad: ["I were tired yesterday.", "They was at the park."],
      },
    ],
    pitfalls: [
      "不规则动词表要背：go-went、eat-ate、take-took、buy-bought、ride-rode。",
      "读音也要注意：played 读 /d/，watched 读 /t/，visited 读 /ɪd/。",
      "today、now、every day 不能和过去时一起用。",
    ],
    memoryCard: ["过去的事用过去式。", "did 后面回原形；was 配 I / he / she / it。"],
  },
  {
    id: "p-comparative",
    title: "形容词比较级初步",
    short: "比较级",
    kind: "card",
    category: "小学基础",
    difficulty: 4,
    summary: "两个东西比一比，形容词要变比较级，句子里常常配一个 than。规则加 -er，长单词用 more。",
    forms: [
      { name: "短形容词", pattern: "形容词 + er + than", note: "taller than，older than。" },
      { name: "以 e 结尾", pattern: "+ r", note: "nice → nicer，large → larger。" },
      { name: "辅音 + y 结尾", pattern: "变 y 为 i 加 er", note: "happy → happier，heavy → heavier。" },
      { name: "重读闭音节", pattern: "双写末尾字母加 er", note: "big → bigger，thin → thinner。" },
    ],
    points: [
      {
        title: "比较级常和 than 一起出现",
        desc: "「A 比 B 更……」就是 A + 比较级 + than + B。",
        good: ["I am taller than my brother.", "This book is heavier than that one."],
        bad: ["I am taller my brother.", "This book is more heavy than that one."],
      },
      {
        title: "短词加 er，长词用 more",
        desc: "单音节和部分双音节词加 er；beautiful、interesting 这类长词前面加 more。",
        good: ["bigger / smaller / stronger", "more beautiful / more interesting"],
        bad: ["beautifuler", "more bigger"],
      },
      {
        title: "比较级是两者相比",
        desc: "三者或三者以上比「最」要用最高级（the + est / the most），不要和比较级混。",
        good: ["Tom is taller than Jim.", "Tom is the tallest in his class."],
        bad: ["Tom is taller than Jim and Jack and Mike."],
      },
    ],
    pitfalls: [
      "不规则比较级要单独记：good → better，bad → worse，many / much → more。",
      "more 和 er 不能同时用：错 more taller。",
      "比较的对象要同类：My bike is newer than yours.（不是 than you）",
    ],
    memoryCard: ["两者相比用比较级，后面常跟 than。", "短词加 er，长词用 more。"],
  },
  {
    id: "p-preposition-place",
    title: "方位介词 in / on / under / behind",
    short: "方位介词",
    kind: "card",
    category: "小学基础",
    difficulty: 2,
    summary: "描述东西在哪里，全靠这几个小词。看图记位置：里面 in、上面 on、下面 under、后面 behind。",
    forms: [
      { name: "里面", pattern: "in", note: "in the box / in the classroom。" },
      { name: "表面上", pattern: "on", note: "on the desk / on the wall。" },
      { name: "下面", pattern: "under", note: "under the chair。" },
      { name: "旁边 / 后面 / 前面", pattern: "next to / behind / in front of", note: "next to the door，behind the tree，in front of the house。" },
    ],
    points: [
      {
        title: "in 在里面，on 在表面",
        desc: "东西被包住用 in，东西放在平面上用 on。",
        good: ["The pen is in the pencil box.", "The book is on the desk."],
        bad: ["The pen is on the pencil box.（除非真的放在盒子上）"],
      },
      {
        title: "Where 问位置，回答用方位介词",
        desc: "Where is...? 的答句常用 It's + 方位短语。",
        good: ["Where is my cat? It's under the bed.", "Where are the keys? They're next to the TV."],
        bad: ["Where is my cat? It's the bed under."],
      },
      {
        title: "in front of 与 behind 成对",
        desc: "「在……前面」是 in front of，「在……后面」是 behind。",
        good: ["There is a tree in front of the house.", "The bike is behind the door."],
        bad: ["He is in front the house."],
      },
    ],
    pitfalls: [
      "in the tree 表示「（生在/停在树上）」，on the tree 表示「长在树上」，用法不同。",
      "in front of 是「在物体外部的前面」；in the front of 是「在物体内部的前部」。",
    ],
    memoryCard: ["里 in，上 on，下 under，后 behind。"],
  },
  {
    id: "p-wh-question",
    title: "疑问词与特殊疑问句",
    short: "疑问词",
    kind: "card",
    category: "小学基础",
    difficulty: 3,
    summary: "问问题先选疑问词：问东西用 what，问人用 who，问地点用 where，问时间用 when，问方式或程度用 how。",
    forms: [
      { name: "what", pattern: "问物品、事情、姓名", note: "What's this? / What's your name?" },
      { name: "who / whose", pattern: "问人 / 问所属", note: "Who is she? / Whose bag is this?" },
      { name: "where / when", pattern: "问地点 / 时间", note: "Where is my ball? / When do you get up?" },
      { name: "how / how many", pattern: "问方式、程度 / 问可数数量", note: "How do you go to school? / How many books?" },
    ],
    points: [
      {
        title: "疑问词 + 一般疑问句语序",
        desc: "特殊疑问句的结构是「疑问词 + 助动词 / be + 主语 + 动词」。",
        good: ["Where do you live?", "What does she like?", "How old are you?"],
        bad: ["Where you live?", "What she likes?"],
      },
      {
        title: "how many 后面接可数名词复数",
        desc: "问可数数量用 how many + 复数；问不可数数量用 how much。",
        good: ["How many apples do you have?", "How much water is there?"],
        bad: ["How many apple do you have?"],
      },
      {
        title: "有些疑问词本身就是主语",
        desc: "Who 作主语时后面直接跟动词，不需要助动词：Who wants to try?",
        good: ["Who is your English teacher?", "Who wants to try?"],
        bad: ["Who does want to try?"],
      },
    ],
    pitfalls: [
      "how old 问年龄，how tall 问身高，how heavy 问体重，别混用。",
      "回答特殊疑问句不能用 Yes / No，要给出具体信息。",
      "What's the weather like? 和 How's the weather? 意思一样。",
    ],
    memoryCard: ["什么 what，谁 who，哪里 where，何时 when，怎样 how。"],
  },
  {
    id: "p-imperative",
    title: "祈使句与 Let's",
    short: "祈使句",
    kind: "card",
    category: "小学基础",
    difficulty: 2,
    summary: "祈使句用来提出请求或发出命令：直接以动词原形开头，主语 you 一般不写出来，句末用句号或感叹号。",
    forms: [
      { name: "肯定祈使句", pattern: "动词原形 + 其他", note: "Open the door, please." },
      { name: "否定祈使句", pattern: "Don't + 动词原形", note: "Don't run in the hall." },
      { name: "建议", pattern: "Let's + 动词原形", note: "Let's go home." },
      { name: "礼貌后缀", pattern: "句子 + please", note: "Sit down, please." },
    ],
    points: [
      {
        title: "祈使句以动词原形开头",
        desc: "开头就是动词原形，没有主语，也没有 am / is / are。",
        good: ["Stand up, please.", "Come here."],
        bad: ["You stand up please.", "To open the door."],
      },
      {
        title: "否定在句首加 Don't",
        desc: "表示「不要做」，用 Don't + 动词原形，不要用 not 或 no。",
        good: ["Don't be late.", "Don't talk in class."],
        bad: ["Not be late.", "No talk in class.（No 用于标语）"],
      },
      {
        title: "Let's 后面跟动词原形",
        desc: "Let's 是 Let us 的缩写，后面接动词原形，表示一起做某事。",
        good: ["Let's play basketball.", "Let's go to the park."],
        bad: ["Let's to play basketball.", "Let's playing basketball."],
      },
    ],
    pitfalls: [
      "please 放句末时前面通常加逗号：Sit down, please.",
      "祈使句答语常用 OK. / All right. / Sure.，不用 Yes / No。",
      "Never 也能引导祈使句，语气更强：Never give up.",
    ],
    memoryCard: ["祈使句用动词原形开头。", "否定加 Don't，建议用 Let's。"],
  },
  {
    id: "p-possessive",
    title: "名词所有格（'s 的用法）",
    short: "所有格",
    kind: "card",
    category: "小学基础",
    difficulty: 3,
    summary: "表示「谁的」要在名词后面加 's。单数加 's，以 s 结尾的复数只加撇号 '。",
    forms: [
      { name: "单数名词", pattern: "名词 + 's", note: "Tom's bag，the cat's tail。" },
      { name: "以 s 结尾的复数", pattern: "名词 + '", note: "the students' books，my parents' room。" },
      { name: "词尾不带 s 的复数", pattern: "名词 + 's", note: "the children's day，the men's room。" },
      { name: "并列所有", pattern: "各加 's 表示各自所有", note: "Tom's and Jim's books（各自的书）。" },
    ],
    points: [
      {
        title: "人名和动物名后面也能加 's",
        desc: "人、动物、时间都可以用所有格表示所属。",
        good: ["This is Lily's ruler.", "Today's homework is easy.", "The dog's ears are long."],
        bad: ["This is Lily ruler.", "The dog ears are long."],
      },
      {
        title: "以 s 结尾的复数只加撇号",
        desc: "复数名词已经有 s，所有格不再加一个 s，只在末尾加 '。",
        good: ["the teachers' office", "my friends' names"],
        bad: ["the teachers's office"],
      },
      {
        title: "'s 与 is 的缩写要看语境",
        desc: "He's 通常是 He is；人名 + 's 通常是所有格。看后面跟的是名词还是形容词。",
        good: ["Tom's book is new.（所有格）", "He's happy.（= He is）"],
        bad: ["Toms book is new."],
      },
    ],
    pitfalls: [
      "不规则复数要加 's：children's、men's、women's。",
      "所有格不能和 of 混着乱用：the name of the book 或 the book's name 都可以，但 the book of name 不行。",
      "物主代词本身已表示所有，不能再加 's：错 my's book。",
    ],
    memoryCard: ["单数加 's，s 结尾复数加 '。", "不规则复数照样加 's。"],
  },
];