// 七年级上册 Starter Homework 2: Know your school —— 题目、答案与补充资料
export default {
  id: "tb7a-starter-2",
  book: "七年级上册",
  unit: "Starter",
  title: "Homework 2: Know your school",
  subtitle: "校园场所 · 介绍学校",
  source: "基础同步达标手册 七年级上（北京市三帆中学）",
  pages: "P4–P5",
  vocab: [
    { word: "building", phonetic: "ˈbɪldɪŋ", pos: "n.", meaning: "建筑物", use: "a tall building 高楼" },
    { word: "teaching building", phonetic: "ˈtiːtʃɪŋ ˈbɪldɪŋ", pos: "词组", meaning: "教学楼", use: "in Teaching Building One 在一号教学楼" },
    { word: "dining hall", phonetic: "ˈdaɪnɪŋ hɔːl", pos: "词组", meaning: "食堂（餐厅）", use: "have lunch in the dining hall" },
    { word: "together", phonetic: "təˈɡeðə(r)", pos: "adv.", meaning: "一起，共同，一齐，一块儿", use: "play football together" },
    { word: "lab", phonetic: "læb", pos: "n.", meaning: "实验室", use: "laboratory 的缩写，复数为 labs" },
    { word: "start", phonetic: "stɑːt", pos: "v.", meaning: "开始", use: "start to do / start doing" },
    { word: "playground", phonetic: "ˈpleɪɡraʊnd", pos: "n.", meaning: "操场", use: "on the playground" },
    { word: "library", phonetic: "ˈlaɪbrəri", pos: "n.", meaning: "图书馆", use: "borrow books from the library" },
    { word: "classroom", phonetic: "ˈklɑːsruːm", pos: "n.", meaning: "教室", use: "in the classroom" },
    { word: "floor", phonetic: "flɔː(r)", pos: "n.", meaning: "楼层；地板", use: "on the second floor 在二楼" },
  ],
  phrases: [
    { en: "go around", zh: "四处转一转，四处逛逛", tip: "go around the school 参观校园" },
    { en: "do morning exercises", zh: "做早操", tip: "exercise 表示“体操”时用复数" },
    { en: "in the library", zh: "在图书馆里", tip: "borrow books in the library" },
    { en: "play football", zh: "踢足球", tip: "球类运动前不加 the" },
    { en: "have seven lessons", zh: "上七节课", tip: "have lessons 上课" },
    { en: "on the second floor", zh: "在二楼", tip: "楼层用序数词，介词用 on" },
    { en: "next to", zh: "在……旁边", tip: "next to an art room" },
  ],
  patterns: [
    { en: "Welcome to our school. Let's go around it together.", zh: "欢迎来到我们学校。让我们一起转转吧。", note: "Let's + 动词原形。" },
    { en: "There is a library and two dining halls in my school.", zh: "我学校有一座图书馆和两个餐厅。", note: "There be 就近原则：be 与最近的主语一致。" },
    { en: "Our lab is on the second floor.", zh: "我们的实验室在二楼。", note: "楼层前用介词 on。" },
    { en: "— Where is Class Three? — It's on the first floor.", zh: "——三班在哪里？——在一楼。", note: "班级用基数词，楼层用序数词。" },
    { en: "We can watch many students take sports activities after class.", zh: "课后我们可以看到很多学生参加体育活动。", note: "watch sb do sth 看到某人做某事（全过程）。" },
  ],
  grammar: [
    {
      title: "There be 句型的就近原则",
      points: [
        "There is/are + 主语 + 地点：be 动词的单复数与最靠近它的名词一致。",
        "例：There is a library and two dining halls in my school.（最近的是 a library，用 is）",
        "变疑问句把 be 提前：Is there a library in your school?",
      ],
    },
    {
      title: "介词 in / on / at 表示地点",
      points: [
        "on the second floor / on the playground（在平面上）。",
        "in the classroom / in the library / in the dining hall（在空间内部）。",
        "at the gate / at school / at home（在某一具体点）。",
      ],
    },
    {
      title: "序数词与基数词",
      points: [
        "基数词表示数量：one, two, three；序数词表示顺序：first, second, third。",
        "“几班”用基数词（Class Three），“几层”用序数词（the third floor）。",
        "序数词前一般加 the：on the fourth floor。",
      ],
    },
    {
      title: "名词复数的特殊变化",
      points: [
        "一般加 -s：floor → floors，student → students。",
        "以 s, x, sh, ch 结尾加 -es：dish → dishes, box → boxes。",
        "以辅音字母 + y 结尾，变 y 为 i 再加 -es：city → cities。",
      ],
    },
  ],
  examPoints: [
    "There be 就近原则（There is a ... and two ...）。",
    "楼层表达用 on the + 序数词 floor。",
    "read books and magazines —— 情态动词 can 后接动词原形 read，而非 reading。",
    "do morning exercises 中 exercise 的复数形式（表示“体操”）。",
    "dining → dining hall；dine（动词）→ dining（动名词作定语）。",
  ],
  sections: [
    {
      id: "words",
      title: "一、单词巩固（看音标和中文写单词）",
      tip: "注意合成词的写法：teaching building、dining hall。",
      type: "dictation",
      items: [
        { q: "[ˈbɪldɪŋ] n. 建筑物", a: "building", note: "build + ing" },
        { q: "[ˈtiːtʃɪŋ ˈbɪldɪŋ]（词组）教学楼", a: "teaching building", note: "teaching 作定语" },
        { q: "[ˈdaɪnɪŋ hɔːl]（词组）食堂", a: "dining hall", note: "dine → dining" },
        { q: "[təˈɡeðə(r)] adv. 一起，共同，一齐，一块儿", a: "together", note: "ge 读 /ɡe/" },
        { q: "[læb] n. 实验室", a: "lab", note: "复数为 labs" },
        { q: "[stɑːt] v. 开始", a: "start", note: "start to do / start doing" },
      ],
    },
    {
      id: "phrases",
      title: "二、词组过关（按提示补全句子）",
      type: "fill",
      items: [
        { q: "Let's ____ ____（在……转一转）the school together.", a: "go around", zh: "让我们一起在校园里转一转吧。", note: "Let's 后接动词原形" },
        { q: "This is our playground. We ____ ____ ____（做早操）here.", a: "do morning exercises", zh: "这是我们的操场。我们在这里做早操。", note: "exercise 表示“体操”用复数" },
        { q: "There are reading rooms ____ ____ ____（在图书馆里）.", a: "in the library", zh: "图书馆里有阅览室。", note: "在图书馆内部用 in" },
        { q: "After school, we come to run or ____ ____（踢足球）here.", a: "play football", zh: "放学后我们来这里跑步或踢足球。", note: "球类运动前不加 the" },
        { q: "I love my school. We ____ ____ ____（上七节课）.", a: "have seven lessons", zh: "我爱我的学校。我们上七节课。", note: "have lessons 上课" },
      ],
    },
    {
      id: "wordform",
      title: "三、根据句意、音标、首字母或汉语提示写单词",
      type: "fill",
      items: [
        { q: "There're different kinds of books and we can read and borrow books there. It's a ____ .", a: "library", zh: "那里有各种各样的书，我们可以在那里读书、借书。它是图书馆。", note: "borrow books 借书" },
        { q: "We have most classes in it. It's a ____ .", a: "classroom", zh: "我们大部分课都在里面上。它是教室。", note: "have classes 上课" },
        { q: "There are 3 ____（实验室）in our school.", a: "labs", zh: "我们学校有 3 个实验室。", note: "3 后接复数" },
        { q: "The ____ ____ [ˈtiːtʃɪŋ ˈbɪldɪŋ] in our new school has five floors.", a: "teaching building", zh: "我们新学校的教学楼有五层。", note: "谓语用 has（单数主语）" },
        { q: "Students often play football ____ [təˈɡeðə(r)] in the playground after school.", a: "together", zh: "放学后学生们经常一起在操场上踢足球。", note: "副词修饰 play" },
      ],
    },
    {
      id: "choice",
      title: "四、单项选择",
      type: "choice",
      items: [
        {
          q: "There ____ a library and two dining halls in my school.",
          options: ["is", "are", "was", "were"],
          a: "A",
          explain: "There be 句型遵循就近原则，最近的主语 a library 是单数，故用 is。",
        },
        {
          q: "Our lab is ____ the second floor. It's next to an art room.",
          options: ["in", "at", "from", "on"],
          a: "D",
          explain: "“在第几层”用介词 on：on the second floor。in 用于空间内部，at 用于具体地点。",
        },
        {
          q: "— Where is Class ____?\n— It's on the ____ floor.",
          options: ["Three; one", "Three; first", "Third; one", "Third, first"],
          a: "B",
          explain: "班级名称用基数词（Class Three），楼层用序数词（the first floor）。",
        },
        {
          q: "The food in the dining hall is ____ and delicious. We all like it a lot!",
          options: ["expensive", "bad", "healthy", "interesting"],
          a: "C",
          explain: "与 delicious（美味的）并列且被大家喜欢，用 healthy（健康的）。",
        },
        {
          q: "Have a look at this class photo. ____ our class teacher, Ms Zhang.",
          options: ["This is", "That is", "Who is", "Whose is"],
          a: "A",
          explain: "介绍照片中的人用 This is；这是介绍他人时的固定表达。",
        },
      ],
    },
    {
      id: "cloze",
      title: "五、语法填空（首字母及括号提示）",
      type: "cloze",
      passage: [
        "Hello, everyone! Let me tell you something about my new school. It is very big. There are two teaching buildings in my school. There are six {{1}} (floor) in Teaching Building One. All the classrooms {{2}} (be) in this building. There are science {{3}} , computer rooms, music rooms, art rooms and a dance hall in Teaching Building Two. There is also a library on the {{4}} (two) floor. We can {{5}} (reading) books and magazines in it.",
        "Look! {{6}} is a big playground in the middle. We run, do morning {{7}} (exercise) and hold school sports events there. We can also play football, basketball or table tennis there after school. We can watch many {{8}} (student) take sports activities after class. The {{9}} (dine) hall is near the playground. We can enjoy different {{10}} (dish) in it. The food in our dining hall is healthy and delicious. We all like it.",
        "This is my beautiful school. I love it very much.",
      ],
      blanks: [
        { n: 1, a: "floors", hint: "floor", explain: "six 后接可数名词复数。" },
        { n: 2, a: "are", hint: "be", explain: "主语 All the classrooms 是复数，用 are。" },
        { n: 3, a: "labs", hint: "无提示，结合语境", explain: "与 computer rooms 并列，指“科学实验室”，用复数 labs。" },
        { n: 4, a: "second", hint: "two", explain: "楼层用序数词，two → second。" },
        { n: 5, a: "read", hint: "reading", explain: "情态动词 can 后接动词原形 read。" },
        { n: 6, a: "There", hint: "首字母提示", explain: "There is a big playground ... 表示“有一个大操场”。注意句首大写。" },
        { n: 7, a: "exercises", hint: "exercise", explain: "do morning exercises 做早操，固定用复数。" },
        { n: 8, a: "students", hint: "student", explain: "many 后接可数名词复数。" },
        { n: 9, a: "dining", hint: "dine", explain: "dine（动词）→ dining hall 餐厅，用动名词作定语。" },
        { n: 10, a: "dishes", hint: "dish", explain: "different 后接名词复数，dish → dishes。" },
      ],
    },
    {
      id: "translate",
      title: "六、根据中文意思和英文提示词语写出句子",
      type: "translate",
      items: [
        { zh: "我的学校并不大，但是很漂亮。(but)", a: "My school is not big, but it is beautiful.", note: "but 连接两个分句，后一分句要有主语 it。" },
        { zh: "我们可以在新校园四处逛逛。(go around)", a: "We can go around the new school.", note: "go around + 名词，表示“在……四处逛逛”；注意加 the。" },
        { zh: "这是我们的北教学楼。它有四层。(floor)", a: "This is our north teaching building. It has four floors.", note: "两句之间用句号断句，第二句要有主语 It。" },
        { zh: "放学后我和我的同学会来操场跑步。(after school)", a: "After school, my classmates and I come to the playground to run.", note: "英语中“我和某人”习惯先说别人、后说 I；用动词不定式表目的。" },
        { zh: "图书馆里有阅览室。同学们可以在这里读书和学习。(there be)", a: "There is a reading room in the library. Students can read and study here.", note: "There be 句型表示“有”；read and study 并列动词原形。" },
      ],
    },
  ],
};