// 七年级上册 Starter Homework 3: Get to know each other —— 题目、答案与补充资料
export default {
  id: "tb7a-starter-3",
  book: "七年级上册",
  unit: "Starter",
  title: "Homework 3: Get to know each other",
  subtitle: "自我介绍 · 兴趣爱好",
  source: "基础同步达标手册 七年级上（北京市三帆中学）",
  pages: "P6–P7",
  vocab: [
    { word: "each other", phonetic: "ˌiːtʃ ˈʌðə(r)", pos: "词组", meaning: "互相，彼此", use: "help each other 互相帮助" },
    { word: "explore", phonetic: "ɪkˈsplɔː(r)", pos: "v.", meaning: "探索；探讨；探究", use: "explore the world of English" },
    { word: "introduce", phonetic: "ˌɪntrəˈdjuːs", pos: "v.", meaning: "介绍", use: "introduce A to B 把 A 介绍给 B" },
    { word: "hobby", phonetic: "ˈhɒbi", pos: "n.", meaning: "业余爱好，嗜好", use: "复数 hobbies" },
    { word: "nervous", phonetic: "ˈnɜːvəs", pos: "adj.", meaning: "神经紧张的；焦虑不安的", use: "be nervous about sth" },
    { word: "everyone", phonetic: "ˈevriwʌn", pos: "pron.", meaning: "每个人，人人", use: "作主语时谓语用单数" },
    { word: "fun", phonetic: "fʌn", pos: "n.", meaning: "乐趣", use: "have fun 玩得开心" },
    { word: "yourself", phonetic: "jɔːˈself", pos: "pron.", meaning: "你自己（复数 yourselves）", use: "Believe in yourself!" },
    { word: "a bit", phonetic: "ə bɪt", pos: "词组", meaning: "有点儿，稍微", use: "a bit tired 有点儿累" },
    { word: "all of you", phonetic: "ɔːl əv juː", pos: "词组", meaning: "你们所有人", use: "I'm glad to see all of you." },
  ],
  phrases: [
    { en: "each other", zh: "互相，彼此", tip: "作宾语，不能作主语" },
    { en: "a bit", zh: "有点儿，稍微", tip: "修饰形容词，a bit tired" },
    { en: "play the piano", zh: "弹钢琴", tip: "乐器前加 the" },
    { en: "read books", zh: "读书", tip: "read books and magazines" },
    { en: "the world of English", zh: "英语的世界", tip: "explore the world of English" },
    { en: "introduce oneself", zh: "介绍某人自己", tip: "introduce yourselves 介绍你们自己" },
    { en: "make friends with sb", zh: "与某人交朋友", tip: "make friends with all of you" },
  ],
  patterns: [
    { en: "I'm so happy to see all of you.", zh: "见到你们所有人我非常高兴。", note: "be happy to do sth 高兴做某事。" },
    { en: "I like playing the piano, reading books and travelling.", zh: "我喜欢弹钢琴、读书和旅行。", note: "like doing sth 表示长期爱好；多个动名词并列。" },
    { en: "Now, it's your turn to introduce yourselves.", zh: "现在轮到你们介绍自己了。", note: "It's one's turn to do sth 轮到某人做某事。" },
    { en: "Nice to meet you!", zh: "很高兴见到你！", note: "初次见面用语，回答 Nice to meet you, too." },
    { en: "Would you like to be friends with me?", zh: "你愿意和我做朋友吗？", note: "Would you like to do sth? 提出请求。" },
  ],
  grammar: [
    {
      title: "动词不定式作宾语或状语",
      points: [
        "be happy / glad / sorry to do sth：I'm happy to see all of you.",
        "It's one's turn to do sth：It's your turn to introduce yourselves.",
        "would like to do sth：Would you like to be friends with me?",
      ],
    },
    {
      title: "like doing 与 like to do",
      points: [
        "like doing sth 强调长期的兴趣爱好：I like playing the piano.",
        "like to do sth 强调某次具体的动作：I like to swim today.",
        "常见后接动名词的动词：enjoy, finish, practise, mind, keep。",
      ],
    },
    {
      title: "复合不定代词与 everyone 的主谓一致",
      points: [
        "everyone / everybody 作主语时，谓语动词用第三人称单数：Everyone needs free time.",
        "反身代词 oneself 要与主语一致：Believe in yourself.（主语是 you）",
      ],
    },
    {
      title: "一般现在时与一般将来时",
      points: [
        "We live in the same neighbourhood, so we go to school together every morning.（习惯动作用一般现在时）",
        "This year, we'll explore the world of English together.（will + 动词原形表将来）",
      ],
    },
  ],
  examPoints: [
    "introduce sb to sb：把你介绍给某人用介词 to。",
    "everyone 作主语 → 谓语用单数（Everyone needs ...）。",
    "believe in oneself 用反身代词 yourself/yourselves，与主语一致。",
    "like 后接动名词或不定式：like helping people。",
    "a bit + 形容词（a bit tired），修饰不可数名词时用 a bit of。",
  ],
  sections: [
    {
      id: "words",
      title: "一、单词巩固（看音标和中文写单词）",
      tip: "注意 hobby（复数 hobbies）、nervous 的拼写。",
      type: "dictation",
      items: [
        { q: "[ˌiːtʃ ˈʌðə(r)]（词组）互相，彼此", a: "each other", note: "两个词分开写" },
        { q: "[ɪkˈsplɔː(r)] v. 探索；探讨，探究", a: "explore", note: "ex- 开头" },
        { q: "[ˌɪntrəˈdjuːs] v. 介绍", a: "introduce", note: "名词形式 introduction" },
        { q: "[ˈhɒbi] n. 业余爱好，嗜好", a: "hobby", note: "y 结尾，复数为 hobbies" },
        { q: "[ˈnɜːvəs] adj. 神经紧张的；焦虑不安的", a: "nervous", note: "be nervous about" },
        { q: "[ˈevriwʌn] pron. 每个人，人人", a: "everyone", note: "合成词 every + one" },
        { q: "[fʌn] n. 乐趣", a: "fun", note: "不可数名词，have fun" },
        { q: "[jɔːˈself] pron. (pl. yourselves) 你自己", a: "yourself", note: "反身代词" },
        { q: "[ə bɪt]（词组）有点儿，稍微", a: "a bit", note: "a bit + 形容词" },
      ],
    },
    {
      id: "phrases",
      title: "二、词组过关（按提示补全句子）",
      type: "fill",
      items: [
        { q: "I'm so happy ____ ____ ____ ____（见到你们所有人）.", a: "to see all of you", zh: "见到你们所有人我非常高兴。", note: "be happy to do sth" },
        { q: "I like ____ ____ ____, ____ ____（弹钢琴，读书）, and travelling.", a: "playing the piano, reading books", accept: ["playing the piano reading books"], zh: "我喜欢弹钢琴、读书，还有旅行。", note: "like doing sth；乐器前加 the" },
        { q: "This year, we'll ____ ____ ____ ____ ____（探索英语的世界）together.", a: "explore the world of English", zh: "今年我们将一起探索英语的世界。", note: "the world of English 英语的世界" },
        { q: "Now, it's your turn ____ ____ ____（介绍你们自己）.", a: "to introduce yourselves", zh: "现在轮到你们介绍自己了。", note: "It's one's turn to do sth；yourselves 与 you 一致" },
      ],
    },
    {
      id: "wordform",
      title: "三、根据句意、音标、首字母或汉语提示写单词",
      type: "fill",
      items: [
        { q: "— I am a b____ tired. Can I have a rest?\n— Of course you can.", a: "bit", zh: "——我有点儿累。我可以休息一下吗？——当然可以。", note: "a bit tired 有点儿累" },
        { q: "Friendship makes it possible for ____ [ˈevriwʌn] to change.", a: "everyone", zh: "友谊使每个人都有改变的可能。", note: "for everyone 对每个人来说" },
        { q: "I want to i____ my sister to you.", a: "introduce", zh: "我想把我姐姐介绍给你。", note: "introduce sb to sb" },
        { q: "Please tell me your name and ____（爱好）.", a: "hobby", zh: "请告诉我你的名字和爱好。", note: "单数 hobby，多个用 hobbies" },
        { q: "Lily is always very ____（紧张的；焦虑的）before the exam. I want to tell her to relax.", a: "nervous", zh: "莉莉考试前总是很紧张。我想告诉她放松。", note: "形容词作表语" },
      ],
    },
    {
      id: "choice",
      title: "四、单项选择",
      type: "choice",
      items: [
        {
          q: "— I feel so ____. What should I do?\n— You'd better listen to music that helps you relax (放松).",
          options: ["happy", "excited", "nervous", "busy"],
          a: "C",
          explain: "由答语“听音乐帮你放松”可知说话人感到紧张，用 nervous。",
        },
        {
          q: "— Dad, I'm afraid I can't do well in my Maths test (考试) tomorrow.\n— Don't worry. Believe (相信) in ____.",
          options: ["you", "your", "yourself", "yourselves"],
          a: "C",
          explain: "believe in oneself 相信某人自己；主语是 you（单数对方），用 yourself。",
        },
        {
          q: "— Nancy, let me introduce my new friend ____ you. His name is Li Xing.\n— Glad to meet you. I'm Nancy.",
          options: ["with", "to", "in", "on"],
          a: "B",
          explain: "introduce sb to sb 把某人介绍给某人，固定搭配用 to。",
        },
        {
          q: "Everyone ____ free time for rest, so school shouldn't give too much homework.",
          options: ["needs", "need", "needed", "is going to need"],
          a: "A",
          explain: "everyone 作主语视为第三人称单数，一般现在时用 needs。",
        },
        {
          q: "I like ____ people with their difficulties (困难), so I have a lot of friends.",
          options: ["help", "helping", "helps", "helped"],
          a: "B",
          explain: "like doing sth 表示习惯性的爱好，用 helping。help sb with sth 帮助某人做某事。",
        },
      ],
    },
    {
      id: "cloze",
      title: "五、语法填空（首字母及括号提示）",
      type: "cloze",
      passage: [
        "My name is Fred. Nice {{1}} (meet) you! I'm 13 {{2}} (year) old, and I'm a student of Grade 7 in No. 1 Middle School. My birthday is {{3}} July. I am often in a white jacket. White is my favourite colour. Do you know what my favourite subject is? It's science.",
        "I can {{4}} (do) a lot of things. I love sports and I can play football {{5}} (good). I can draw beautiful {{6}} (picture). I can speak some simple Chinese, like “nihao” and “zaijian”.",
        "I like {{7}} (make) friends. Bill is my first friend in the middle school. His mother is our English teacher Mrs Black. We {{8}} (live) in the same neighbourhood (同一个社区), so we {{9}} (go) to school together every morning. I have some other friends in the middle school. Jack is one of them. He is also my cousin. He is in No. 1 Middle School, too. But we are in different grades. He is in Grade 8. Jack and I {{10}} (be) both in the same sports club.",
        "This is me. Would you like to be friends with me?",
      ],
      blanks: [
        { n: 1, a: "to meet", hint: "meet", explain: "Nice to meet you! 固定用语。" },
        { n: 2, a: "years", hint: "year", explain: "13 后接可数名词复数；13 years old 十三岁。" },
        { n: 3, a: "in", hint: "无提示", explain: "月份前用介词 in：in July。" },
        { n: 4, a: "do", hint: "do", explain: "情态动词 can 后接动词原形。" },
        { n: 5, a: "well", hint: "good", explain: "修饰动词 play 用副词 well。" },
        { n: 6, a: "pictures", hint: "picture", explain: "draw beautiful pictures 画漂亮的画，用复数。" },
        { n: 7, a: "making", hint: "make", explain: "like doing sth 表示爱好，用动名词 making。" },
        { n: 8, a: "live", hint: "live", explain: "主语 We，一般现在时用原形 live。" },
        { n: 9, a: "go", hint: "go", explain: "主语 We，一般现在时用原形 go。" },
        { n: 10, a: "are", hint: "be", explain: "主语 Jack and I 是复数，用 are。" },
      ],
    },
    {
      id: "translate",
      title: "六、根据中文意思和英文提示词语写出句子",
      type: "translate",
      items: [
        { zh: "我叫李大明。我 14 岁。(name; year)", a: "My name is Li Daming. I'm fourteen years old.", note: "表示年龄用 ... years old。" },
        { zh: "我的生日在八月。(birthday)", a: "My birthday is in August.", note: "月份前用介词 in；August 首字母大写。" },
        { zh: "我有很多爱好。我最喜欢打篮球和弹钢琴。(hobby; best)", a: "I have many hobbies. I like playing basketball and the piano best.", note: "hobby 用复数 hobbies；like ... best 最喜欢；乐器前加 the。" },
        { zh: "我有点紧张，但是我很开心见到你们。(nervous; meet)", a: "I'm a little nervous, but I'm very happy to meet you.", note: "a little = a bit；be happy to do sth。" },
        { zh: "我想和你们所有人做朋友。(make friends)", a: "I want to make friends with all of you.", note: "make friends with sb 与某人交朋友。" },
      ],
    },
  ],
};