// 七年级上册 Starter Homework 1: Get ready —— 题目、答案与补充资料
export default {
  id: "tb7a-starter-1",
  book: "七年级上册",
  unit: "Starter",
  title: "Homework 1: Get ready",
  subtitle: "开学准备 · 文具与衣物",
  source: "基础同步达标手册 七年级上（北京市三帆中学）",
  pages: "P2–P3",
  vocab: [
    { word: "ready", phonetic: "ˈredi", pos: "adj.", meaning: "准备好（做某事）的", use: "be ready for sth / be ready to do sth" },
    { word: "textbook", phonetic: "ˈtekstbʊk", pos: "n.", meaning: "教科书，教材，课本", use: "an English textbook" },
    { word: "eraser", phonetic: "ɪˈreɪzə(r)", pos: "n.", meaning: "橡皮", use: "an eraser / two erasers" },
    { word: "junior", phonetic: "ˈdʒuːniə(r)", pos: "adj.", meaning: "低年级的；初级的", use: "junior high 初级中学" },
    { word: "geography", phonetic: "dʒiˈɒɡrəfi", pos: "n.", meaning: "地理", use: "a geography teacher" },
    { word: "biology", phonetic: "baɪˈɒlədʒi", pos: "n.", meaning: "生物", use: "study biology" },
    { word: "history", phonetic: "ˈhɪstəri", pos: "n.", meaning: "历史", use: "in history class" },
    { word: "grey", phonetic: "ɡreɪ", pos: "adj.", meaning: "灰色的", use: "a grey scarf（英式拼写，美式为 gray）" },
    { word: "jacket", phonetic: "ˈdʒækɪt", pos: "n.", meaning: "夹克，短上衣", use: "a sports jacket" },
    { word: "scarf", phonetic: "skɑːf", pos: "n.", meaning: "围巾；头巾；披肩", use: "red scarf 红领巾" },
    { word: "T-shirt", phonetic: "ˈtiːʃɜːt", pos: "n.", meaning: "T 恤衫，短袖运动衫", use: "a white T-shirt" },
    { word: "uniform", phonetic: "ˈjuːnɪfɔːm", pos: "n.", meaning: "制服", use: "school uniform 校服" },
    { word: "of course", phonetic: "əv kɔːs", pos: "词组", meaning: "当然", use: "— Can you help me? — Of course." },
    { word: "forget", phonetic: "fəˈɡet", pos: "v.", meaning: "忘记，遗忘", use: "forget to do sth 忘记要做某事 / forget doing sth 忘记做过某事" },
  ],
  phrases: [
    { en: "junior high", zh: "初级中学", tip: "junior high school 初中" },
    { en: "red scarf", zh: "红领巾", tip: "佩戴红领巾 wear a red scarf" },
    { en: "school uniform", zh: "校服", tip: "穿校服 wear the school uniform" },
    { en: "of course", zh: "当然", tip: "答语，相当于 sure / certainly" },
    { en: "put ... in ...", zh: "把……放进……", tip: "put them in your schoolbag" },
    { en: "how about ...", zh: "……怎么样呢", tip: "how about + 名词/代词/动名词" },
    { en: "welcome to ...", zh: "欢迎来到……", tip: "Welcome to our school!" },
  ],
  patterns: [
    { en: "Welcome to junior high!", zh: "欢迎来到初中！", note: "Welcome to + 地点；welcome 后接 here/there/home 时不加 to。" },
    { en: "Are you ready?", zh: "你做好准备了吗？", note: "be ready for + 名词；be ready to do sth。" },
    { en: "Put them in your schoolbag.", zh: "把它们放进你的书包里。", note: "代词作宾语要放中间：put it/them in ..." },
    { en: "How about you, Li Meng?", zh: "你怎么样呢，李萌？", note: "How about + 代词/动名词，用来征求意见。" },
    { en: "Don't forget your red scarf.", zh: "别忘了你的红领巾。", note: "否定祈使句 Don't + 动词原形。" },
  ],
  grammar: [
    {
      title: "be going to 表示打算（一般将来时）",
      points: [
        "结构：主语 + be (am/is/are) + going to + 动词原形。",
        "常与 tomorrow, next week, this evening 等将来时间状语连用。",
        "例：I am going to wear my new clothes tomorrow. / He is going to meet his new classmates.",
      ],
    },
    {
      title: "名词的数（可数与不可数）",
      points: [
        "可数名词复数前有 two, three, five 等基数词时要变复数：two sweaters, three skirts, four pens, five pencils。",
        "注意不规则或易错复数：scarf → scarves（也可 scarfs）。",
        "成双成对的名词常用复数：shoes, trousers, socks；谓语用 are。",
      ],
    },
    {
      title: "一般现在时的三单",
      points: [
        "主语是第三人称单数时，实义动词加 -s / -es：My mum often washes my shoes。",
        "以 s, x, sh, ch, o 结尾加 -es：watches, goes, does。",
      ],
    },
  ],
  examPoints: [
    "冠词辨析：第一次提到、以元音音素开头的可数名词单数用 an（an eraser），辅音音素开头用 a（a pen）。",
    "forget to do sth（忘记要做）与 forget doing sth（忘记做过）的区别。",
    "学科名词辨义：geography / history / biology / music 与不同 places in the world 的搭配。",
    "Will you ...? 的肯定答语常用 Of course / Yes, I will。",
    "trousers, shoes 等复数名词作主语，be 动词用 are。",
  ],
  sections: [
    {
      id: "words",
      title: "一、单词巩固（看音标和中文写单词）",
      tip: "先读准音标，再动笔拼写，注意字母组合。",
      type: "dictation",
      items: [
        { q: "[ˈredi] adj. 准备好（做某事）的", a: "ready", note: "ea 读 /e/" },
        { q: "[ˈtekstbʊk] n. 教科书，教材，课本", a: "textbook", note: "text + book 合成词" },
        { q: "[ɪˈreɪzə(r)] n. 橡皮", a: "eraser", note: "-er 结尾表示物" },
        { q: "[ˈdʒuːniə(r)] adj. 低年级的", a: "junior", note: "ju 读 /dʒuː/" },
        { q: "[ˌdʒuːniə(r) ˈhaɪ]（词组）初级中学", a: "junior high", note: "也作 junior high school" },
        { q: "[dʒiˈɒɡrəfi] n. 地理", a: "geography", note: "geo- 表示“地球、土地”" },
        { q: "[baɪˈɒlədʒi] n. 生物", a: "biology", note: "biology ← bio（生命）" },
        { q: "[ˈhɪstəri] n. 历史", a: "history", note: "注意与 story 区分" },
        { q: "[ɡreɪ] adj. 灰色的", a: "grey", note: "美式拼写 gray" },
        { q: "[ˈdʒækɪt] n. 夹克，短上衣", a: "jacket", note: "ck 读 /k/" },
        { q: "[skɑːf] n. 围巾；头巾；披肩", a: "scarf", note: "复数为 scarves" },
        { q: "[red skɑːf]（词组）红领巾", a: "red scarf", note: "佩戴 wear a red scarf" },
        { q: "[ˈtiːʃɜːt] n. T 恤衫，短袖运动衫", a: "T-shirt", note: "大写 T + shirt" },
        { q: "[ˈjuːnɪfɔːm] n. 制服", a: "uniform", note: "u 读 /juː/" },
        { q: "[skuːl ˈjuːnɪfɔːm]（词组）校服", a: "school uniform", note: "穿校服 wear the school uniform" },
        { q: "[əv kɔːs]（词组）当然", a: "of course", note: "答语中常用" },
        { q: "[fəˈɡet] v. 忘记，遗忘", a: "forget", note: "forget to do / forget doing" },
      ],
    },
    {
      id: "phrases",
      title: "二、词组过关（按提示补全句子）",
      tip: "先判断用哪个短语，再检查动词形式。",
      type: "fill",
      items: [
        { q: "____ ____（欢迎来到）junior high! You'll also meet new teachers and classmates.", a: "Welcome to", zh: "欢迎来到初中！你还会遇到新老师和同学。", note: "Welcome to + 地点" },
        { q: "____ you ____（你做好准备了吗）? Let's start! It'll be fun!", a: "Are you ready", accept: ["are ready"], zh: "你做好准备了吗？我们开始吧！会很有趣的！", note: "be ready 的疑问句把 be 提到句首；题面中 you 已印出，两个空分别填 Are 和 ready。" },
        { q: "And your textbooks? ____ ____ ____（把它们放入）your schoolbag.", a: "Put them in", zh: "那你的课本呢？把它们放进书包里。", note: "代词放 put 和 in 之间" },
        { q: "____ ____ ____（你怎么样呢）, Li Meng?", a: "How about you", zh: "你怎么样呢，李萌？", note: "How about + 代词/动名词" },
        { q: "Oh, ____ ____（别忘了）your red scarf.", a: "don't forget", zh: "哦，别忘了你的红领巾。", note: "否定祈使句" },
      ],
    },
    {
      id: "wordform",
      title: "三、根据句意、音标、首字母或汉语提示写单词",
      type: "fill",
      items: [
        { q: "I need to buy some ____（橡皮）for my exam.", a: "erasers", zh: "我需要为考试买些橡皮。", note: "some 后接可数名词复数" },
        { q: "— Do you have any idea for the weekend?\n— How about ____ (take) a walk in the park?", a: "taking", zh: "——周末有什么打算吗？——去公园散步怎么样？", note: "How about + 动名词" },
        { q: "I would like a pair of sports ____（鞋）for my birthday.", a: "shoes", zh: "我生日想要一双运动鞋。", note: "a pair of shoes 一双鞋" },
        { q: "The sky is ____（灰色的）. It's going to rain later!", a: "grey", zh: "天空是灰色的，以后要下雨！", note: "形容词作表语" },
        { q: "On Monday, we have to wear the school ____ [ˈjuːnɪfɔːm].", a: "uniform", zh: "星期一我们必须穿校服。", note: "have to 后接动词原形 wear" },
      ],
    },
    {
      id: "choice",
      title: "四、单项选择",
      type: "choice",
      items: [
        {
          q: "There is ____ eraser and ____ pen in my pencil case.",
          options: ["a; an", "an; an", "an; a", "a; a"],
          a: "C",
          explain: "eraser 以元音音素 /ɪ/ 开头用 an；pen 以辅音音素 /p/ 开头用 a。故选 an; a。",
        },
        {
          q: "Jack often forgets ____ his homework to school.",
          options: ["to take", "take", "taking", "will take"],
          a: "A",
          explain: "forget to do sth 表示“忘记去做某事（还没做）”，这里指忘记带作业，用 to take。",
        },
        {
          q: "My favorite subject is ____, because I can know about different places in the world.",
          options: ["history", "geography", "biology", "music"],
          a: "B",
          explain: "由 different places in the world（世界上不同的地方）可知是 geography（地理）。",
        },
        {
          q: "Weifang ____ her white sports shoes to school tomorrow.",
          options: ["wear", "wears", "is going to wear", "wore"],
          a: "C",
          explain: "tomorrow 提示一般将来时，主语 Weifang 是第三人称单数，用 is going to wear。",
        },
        {
          q: "— Will you come to help me with the party?\n— Yes, ____ I will.",
          options: ["I don't know", "of course", "no way", "thanks a lot"],
          a: "B",
          explain: "表示爽快答应，用 of course。Will you ...? 的肯定答语为 Yes, of course / Yes, I will。",
        },
      ],
    },
    {
      id: "cloze",
      title: "五、语法填空（首字母及括号提示）",
      type: "cloze",
      passage: [
        "I am a new student in a middle school. Tomorrow, I {{1}} (wear) my new clothes. I have two red sweaters and three yellow {{2}} (skirt). My sports {{3}} (jacket) is soft and warm. My sports trousers {{4}} (be) pretty and colourful. I will also wear black socks and brown shoes. My {{5}} (shoe) are comfortable. My mum often {{6}} (wash) my shoes for me. I {{7}} (have) a new blue pencil case. In it, you can see four red pens and five green {{8}} (pencil). I {{9}} (keep) all my school things tidy every day. Tomorrow I {{10}} (meet) my new classmates.",
        "I am ready to make new friends. I will be a good student and have fun in my new school.",
      ],
      blanks: [
        { n: 1, a: "am going to wear", hint: "wear", explain: "Tomorrow 提示一般将来时，主语 I 用 am going to + 动词原形。" },
        { n: 2, a: "skirts", hint: "skirt", explain: "three 后接可数名词复数。" },
        { n: 3, a: "jacket", hint: "jacket", explain: "主语 My sports jacket 是单数，用原形。" },
        { n: 4, a: "are", hint: "be", explain: "trousers 是复数名词，be 动词用 are。" },
        { n: 5, a: "shoes", hint: "shoe", explain: "由后面的 are 可知主语是复数 shoes。" },
        { n: 6, a: "washes", hint: "wash", explain: "主语 My mum 是第三人称单数，一般现在时加 -es。" },
        { n: 7, a: "have", hint: "have", explain: "主语 I，用动词原形 have。" },
        { n: 8, a: "pencils", hint: "pencil", explain: "five 后接可数名词复数。" },
        { n: 9, a: "keep", hint: "keep", explain: "every day 提示一般现在时，主语 I 用原形。" },
        { n: 10, a: "am going to meet", hint: "meet", explain: "Tomorrow 提示一般将来时，主语 I 用 am going to + 动词原形。" },
      ],
    },
    {
      id: "translate",
      title: "六、根据中文意思和英文提示词语写出句子",
      type: "translate",
      items: [
        { zh: "我为初中生活做好了准备。(ready)", a: "I am ready for junior high.", note: "be ready for + 名词。" },
        { zh: "我明天要穿一双新的运动鞋。(a pair of)", a: "I am going to wear a pair of new sports shoes tomorrow.", note: "a pair of 后接复数名词；将来时用 be going to。" },
        { zh: "我们有些新学科，比如地理、生物和历史。(subject)", a: "We have some new subjects, like geography, biology and history.", note: "“比如”用 like / such as。" },
        { zh: "我铅笔盒里有两支铅笔、一块橡皮和三把尺子。(pencil case)", a: "There are two pencils, an eraser and three rulers in my pencil case.", note: "表示“有”用 There be；多件物品并列时 be 动词与最近的主语一致（就近原则）。" },
        { zh: "别忘了戴你的红领巾。(forget)", a: "Don't forget to wear your red scarf.", note: "forget to do sth；否定祈使句 Don't + 动词原形。" },
      ],
    },
  ],
};