// 七年级上册 Starter Homework 4: Making a wish tree —— 题目、答案与补充资料
export default {
  id: "tb7a-starter-4",
  book: "七年级上册",
  unit: "Starter",
  title: "Homework 4: Making a wish tree",
  subtitle: "许愿树 · 计划与打算",
  source: "基础同步达标手册 七年级上（北京市三帆中学）",
  pages: "P8–P9",
  vocab: [
    { word: "join", phonetic: "dʒɔɪn", pos: "v.", meaning: "成为……的一员，加入", use: "join us 加入我们 / join the football team" },
    { word: "team", phonetic: "tiːm", pos: "n.", meaning: "（游戏或体育比赛的）队", use: "a football team 足球队" },
    { word: "take part in", phonetic: "teɪk pɑːt ɪn", pos: "词组", meaning: "参加，参与", use: "take part in sports 参加运动" },
    { word: "wish", phonetic: "wɪʃ", pos: "n./v.", meaning: "愿望；希望", use: "make a wish 许愿" },
    { word: "plan", phonetic: "plæn", pos: "n./v.", meaning: "计划", use: "make a plan for sth 为……制定计划" },
    { word: "share", phonetic: "ʃeə(r)", pos: "v.", meaning: "分享", use: "share sth with sb 与某人分享某物" },
    { word: "be made of", phonetic: "biː meɪd əv", pos: "词组", meaning: "由……制成（看得出原料）", use: "The leaves are made of paper." },
    { word: "practice", phonetic: "ˈpræktɪs", pos: "v./n.", meaning: "练习", use: "practice doing sth 练习做某事" },
    { word: "village", phonetic: "ˈvɪlɪdʒ", pos: "n.", meaning: "村庄", use: "a small village" },
  ],
  phrases: [
    { en: "make a wish tree", zh: "制作许愿树", tip: "make a wish 许愿" },
    { en: "join the football team", zh: "加入足球队", tip: "join + 组织/团队" },
    { en: "make more friends", zh: "交更多的朋友", tip: "make friends with sb" },
    { en: "get better at English", zh: "更擅长英语", tip: "be good at → get better at" },
    { en: "learn to dance / learn to play the piano", zh: "学会跳舞 / 学会弹钢琴", tip: "learn to do sth；乐器前用 the" },
    { en: "make a plan for sth", zh: "为……制定一个计划", tip: "for 后接计划的对象" },
    { en: "share sth with sb", zh: "与某人分享某物", tip: "share it with the class" },
    { en: "take part in sports", zh: "参加运动", tip: "take part in + 活动" },
    { en: "be made of", zh: "由……制成", tip: "看得出原料用 be made of，看不出用 be made from" },
  ],
  patterns: [
    { en: "I'm going to make a plan for my wish and share it with my friends.", zh: "我将为我的愿望制订一个计划，并把它与朋友们分享。", note: "be going to + 动词原形表示打算。" },
    { en: "To make more friends, I'm going to join some after-school clubs.", zh: "为了交更多朋友，我打算加入一些课外俱乐部。", note: "动词不定式 To do 放句首表目的。" },
    { en: "I want to learn to dance, and I will practice every day.", zh: "我想学会跳舞，并会每天练习。", note: "want to do sth；learn to do sth。" },
    { en: "Practising every day can make me better at dancing.", zh: "每天练习会让我更擅长跳舞。", note: "动名词作主语；make sb + 形容词。" },
    { en: "Miss Green asked us to write down our wishes on the 'leaves'.", zh: "格林老师让我们把愿望写在“叶子”上。", note: "ask sb to do sth；write down 写下。" },
  ],
  grammar: [
    {
      title: "be going to 与 will 表示计划",
      points: [
        "计划、打算：be going to + 动词原形：I'm going to join some after-school clubs.",
        "临时的决定或承诺：will + 动词原形：I will practice every day.",
        "疑问句：What are you going to do this weekend? / Do you have any plans for your holiday?",
      ],
    },
    {
      title: "动词不定式表目的与固定搭配",
      points: [
        "To get there on time, we must get up earlier.（To do 放句首表目的）",
        "ask sb to do sth：Miss Green asked us to write down our wishes.",
        "want / would like / learn / hope + to do sth。",
      ],
    },
    {
      title: "形容词与副词的比较等级",
      points: [
        "两者比较用比较级 + than：Tom speaks English better than me.",
        "good / well → better → best；Which is a better exercise, running or swimming?",
        "get better at sth 变得更擅长：get better at English / dancing。",
      ],
    },
    {
      title: "make 的常用结构",
      points: [
        "make sb do sth 让某人做某事（不带 to）。",
        "make sb + 形容词：Miss Green's words made me feel happy.",
        "be made of / from：The “leaves” are made of paper.",
      ],
    },
  ],
  examPoints: [
    "learn to do sth 学会做某事，不能直接跟动词原形。",
    "比较级 + than 表两者比较；good/well → better。",
    "To do 结构放句首表示目的。",
    "join 后接组织、团队；take part in 后接活动比赛。",
    "share sth with sb、make a plan for sth 的介词搭配。",
    "ask sb to do sth 中不定式符号 to 不能省略。",
  ],
  sections: [
    {
      id: "words",
      title: "一、单词巩固（看音标和中文写单词）",
      type: "dictation",
      items: [
        { q: "[dʒɔɪn] v. 成为……的一员，加入", a: "join", note: "join us / join the team" },
        { q: "[tiːm] n.（游戏或体育比赛的）队", a: "team", note: "a football team" },
        { q: "[teɪk pɑːt ɪn]（词组）参加，参与", a: "take part in", note: "后接活动、比赛" },
      ],
    },
    {
      id: "phrases",
      title: "二、词组过关（写出对应的英文表达）",
      tip: "注意动名词或不定式形式：作主语或 like 后用 doing，表目的用 to do。",
      type: "translate",
      items: [
        { zh: "制作许愿树", a: "make a wish tree", note: "make a wish 许愿" },
        { zh: "加入足球队", a: "join the football team", note: "join + 团队" },
        { zh: "交更多的朋友", a: "make more friends", note: "make friends with sb" },
        { zh: "读更多的书", a: "read more books", note: "more + 可数名词复数" },
        { zh: "更擅长英语", a: "get better at English", note: "be good at → get better at" },
        { zh: "学会跳舞", a: "learn to dance", note: "learn to do sth" },
        { zh: "学会弹钢琴", a: "learn to play the piano", note: "乐器前加 the" },
        { zh: "为……制定一个计划 / 与……分享它（____ your wish and ____ the class）", a: "make a plan for your wish and share it with the class", accept: ["make a plan for ... share it with ..."], note: "make a plan for sth；share sth with sb" },
        { zh: "我将参加运动。(To make more friends, I'm going to ____ ____ ____)", a: "take part in sports", note: "be going to + 动词原形" },
      ],
    },
    {
      id: "wordform",
      title: "三、根据句意、音标、首字母或汉语提示写单词或词组",
      type: "fill",
      items: [
        { q: "We want to play a new game. Do you want to j____ us?", a: "join", zh: "我们想玩个新游戏。你想加入我们吗？", note: "join us 加入我们" },
        { q: "Before blowing out (吹灭) the birthday candles, you can make a w____（愿望）.", a: "wish", zh: "吹灭生日蜡烛前，你可以许个愿。", note: "make a wish 许愿" },
        { q: "Tom speaks English b____ than me, so I am going to learn from him.", a: "better", zh: "汤姆英语说得比我好，所以我要向他学习。", note: "than 前用比较级 better" },
        { q: "Our football ____ [tiːm] is playing very well this season (赛季). I think they will be the champion (冠军).", a: "team", zh: "我们足球队这个赛季踢得很好。我认为他们会是冠军。", note: "作主语，谓语用 is" },
        { q: "Which sport do you want to ____ ____ ____（参与）?", a: "take part in", zh: "你想参与哪项运动？", note: "want to do sth；take part in + 活动" },
      ],
    },
    {
      id: "choice",
      title: "四、单项选择",
      type: "choice",
      items: [
        {
          q: "David wants to learn ____ after school, so he joins a swimming club.",
          options: ["swim", "swims", "to swim", "swam"],
          a: "C",
          explain: "learn to do sth 学会做某事，用不定式 to swim。",
        },
        {
          q: "Which is a ____ exercise, running or swimming?",
          options: ["good", "better", "best", "well"],
          a: "B",
          explain: "running 与 swimming 两者比较，用比较级 better。",
        },
        {
          q: "The holiday is coming. Do you have any ____ for your holiday?",
          options: ["teams", "plans", "wishes", "friends"],
          a: "B",
          explain: "由 for your holiday 可知问的是假期的计划，用 plans。",
        },
        {
          q: "— What's your plan for your coming weekend?\n— I ____ a movie with my new friends.",
          options: ["watch", "watches", "watched", "am going to watch"],
          a: "D",
          explain: "coming weekend 提示将来，谈计划用 be going to + 动词原形。",
        },
        {
          q: "____ there on time, we must get up earlier.",
          options: ["To get", "Getting", "Get", "Gets"],
          a: "A",
          explain: "句首用动词不定式表示目的：“为了按时到那里”。",
        },
      ],
    },
    {
      id: "cloze",
      title: "五、语法填空（首字母及括号提示）",
      type: "cloze",
      passage: [
        "My name is Julie. I come {{1}} (from) a small village. Today is my {{2}} (one) day of junior high. The class teacher, Miss Green, asked us {{3}} (write) down our wishes on the “leaves”. The “leaves” are made of paper. And then we put them {{4}} the “wishing tree”.",
        "Miss Green asked us to share our {{5}} (wish) with the classmates. I was nervous, but I still stood up bravely and said, “My wish is to get {{6}} (good) at English, so I {{7}} (work) harder in English. I hope my teacher and classmates can help me {{8}} my English.”",
        "“Believe in {{9}} (you) and we will help you!” Miss Green's words made me feel {{10}} (happy).",
      ],
      blanks: [
        { n: 1, a: "from", hint: "from", explain: "come from 来自……" },
        { n: 2, a: "first", hint: "one", explain: "“第几天”用序数词，one → first。" },
        { n: 3, a: "to write", hint: "write", explain: "ask sb to do sth 让某人做某事。" },
        { n: 4, a: "on", hint: "无提示", explain: "把愿望挂在树上用 put ... on the tree。" },
        { n: 5, a: "wishes", hint: "wish", explain: "our 后接可数名词复数 wishes。" },
        { n: 6, a: "better", hint: "good", explain: "get better at sth 变得更擅长。" },
        { n: 7, a: "will work|am going to work", hint: "work", explain: "表将来的打算，用 will + 动词原形。" },
        { n: 8, a: "with", hint: "无提示", explain: "help sb with sth 在某方面帮助某人。" },
        { n: 9, a: "yourself", hint: "you", explain: "believe in oneself 相信某人自己，主语是 you（单数对方）用 yourself。" },
        { n: 10, a: "happy", hint: "happy", explain: "make sb + 形容词，feel happy 感到开心。" },
      ],
    },
    {
      id: "translate",
      title: "六、根据中文意思和英文提示词语写出句子",
      type: "translate",
      items: [
        { zh: "我将为我的愿望制订一个计划，并把它与我的朋友们分享。(plan; share)", a: "I am going to make a plan for my wish and share it with my friends.", note: "be going to；make a plan for；share sth with sb。" },
        { zh: "我打算结交更多朋友。(be going to)", a: "I am going to make more friends.", note: "make friends 交朋友。" },
        { zh: "为了交更多的朋友，我打算加入一些课外俱乐部。(after-school clubs)", a: "To make more friends, I'm going to join some after-school clubs.", note: "To do 放句首表目的；join + 组织。" },
        { zh: "我也想学会跳舞，并会每天练习。(learn; practice)", a: "I want to learn to dance, and I am going to practice every day.", note: "learn to do sth 学会做某事。" },
        { zh: "每天练习会让我更擅长跳舞。(make sb better at...)", a: "Practising every day can make me better at dancing.", note: "动名词作主语，谓语用单数；make sb better at sth。" },
      ],
    },
  ],
};