// 七年级上册 Unit 1 Homework 1: Starting out + Understanding Ideas (1)
export default {
  id: "tb7a-u1-1",
  book: "七年级上册",
  unit: "Unit 1",
  title: "Homework 1: Starting out (1)",
  subtitle: "初中新生活 · 思考与学习",
  source: "基础同步达标手册 七年级上（北京市三帆中学）",
  pages: "P10–P11",
  vocab: [
    { word: "without", phonetic: "wɪˈðaʊt", pos: "prep.", meaning: "缺乏，没有", use: "without water 没有水" },
    { word: "sentence", phonetic: "ˈsentəns", pos: "n.", meaning: "句子", use: "the meaning of the sentence" },
    { word: "point", phonetic: "pɔɪnt", pos: "v.", meaning: "（用手或细的物体）指", use: "point at sth 指向某物" },
    { word: "point out", phonetic: "pɔɪnt aʊt", pos: "词组", meaning: "指出，指明", use: "point out the mistake" },
    { word: "mistake", phonetic: "mɪˈsteɪk", pos: "n.", meaning: "错误", use: "make mistakes 犯错误" },
    { word: "polite", phonetic: "pəˈlaɪt", pos: "adj.", meaning: "有礼貌的，客气的", use: "It is polite of sb to do sth" },
    { word: "mind", phonetic: "maɪnd", pos: "n.", meaning: "头脑；思想，思维", use: "go into one's mind 进入脑海" },
    { word: "hers", phonetic: "hɜːz", pos: "pron.", meaning: "她的（名词性物主代词）", use: "This book is hers." },
    { word: "dry", phonetic: "draɪ", pos: "adj.", meaning: "干的，干燥的", use: "hot and dry 又热又干" },
    { word: "meaning", phonetic: "ˈmiːnɪŋ", pos: "n.", meaning: "意义，意思，含义", use: "the meaning of the sentence" },
    { word: "fact", phonetic: "fækt", pos: "n.", meaning: "事实；真相", use: "in fact 事实上" },
    { word: "need", phonetic: "niːd", pos: "v.", meaning: "需要", use: "need to do sth" },
    { word: "remember", phonetic: "rɪˈmembə(r)", pos: "v.", meaning: "记住，记得", use: "remember to do sth 记得去做" },
    { word: "really", phonetic: "ˈriːəli", pos: "adv.", meaning: "确切地，的确", use: "really important 确实重要" },
    { word: "important", phonetic: "ɪmˈpɔːtnt", pos: "adj.", meaning: "重要的", use: "an important lesson 重要的一课" },
  ],
  phrases: [
    { en: "point out", zh: "指出，指明", tip: "point out the mistake" },
    { en: "in fact", zh: "事实上", tip: "常用于句首，起强调作用" },
    { en: "learn from", zh: "向……学习", tip: "learn from great thinkers" },
    { en: "think about", zh: "思考，考虑", tip: "think about the meaning" },
    { en: "take ... to ...", zh: "把……带给……", tip: "take flowers to their teachers" },
    { en: "be polite to sb", zh: "对某人有礼貌", tip: "polite 常与 to 搭配" },
    { en: "put up one's hand", zh: "举手", tip: "put up 举起" },
  ],
  patterns: [
    { en: "Is it OK to point out the mistake?", zh: "指出这个错误可以吗？", note: "Is it OK to do sth? 询问是否可以做某事。" },
    { en: "You need to think more in your learning.", zh: "你需要在学习中多思考。", note: "need to do sth；think more 多思考。" },
    { en: "We should learn from great thinkers.", zh: "我们应该向伟大的思想家学习。", note: "should + 动词原形；learn from 向……学习。" },
    { en: "I never go travelling without a book.", zh: "我旅行时从不不带书。", note: "without 表示“没有”，后接名词或动名词。" },
    { en: "It is polite of students to say hello to their teachers.", zh: "学生向老师问好是有礼貌的。", note: "It is + 形容词 + of sb + to do sth。" },
  ],
  grammar: [
    {
      title: "It is + 形容词 + of/for sb + to do sth",
      points: [
        "描述人的品质用 of：It is polite of students to say hello to their teachers.",
        "描述事情的性质用 for：It is important for us to learn English well.",
        "It is OK to do sth 表示“做某事是可以的”。",
      ],
    },
    {
      title: "without 的用法",
      points: [
        "without 是介词，后接名词、代词或动名词：without water / without writing anything。",
        "反义词是 with：with a book 带着一本书。",
      ],
    },
    {
      title: "need 的用法",
      points: [
        "need to do sth（人作主语）：You need to think more.",
        "need 作名词：free time for rest is a need。",
        "needn't do sth 表示“不必做某事”。",
      ],
    },
    {
      title: "人称代词与物主代词",
      points: [
        "形容词性物主代词 + 名词：her book；名词性物主代词单独使用：The book is hers.",
        "I smile at her.（人称代词宾格） / Most of them are writing.（them 作介词宾语）",
      ],
    },
  ],
  examPoints: [
    "介词 without 后接动名词：without writing anything。",
    "put up one's hand 举手；put on 穿上；put away 收起来。",
    "时间点前用 at（at 8:00 a.m.），具体某天用 on，月份、年份用 in。",
    "Is it OK to do sth? 与 It is polite of sb to do sth 中的 it 作形式主语。",
    "learn from（向……学习）与 think about（思考）的搭配。",
  ],
  sections: [
    {
      id: "words",
      title: "一、单词巩固（看音标和中文写单词）",
      type: "dictation",
      items: [
        { q: "[wɪˈðaʊt] prep. 缺乏，没有", a: "without", note: "反义词 with" },
        { q: "[ˈsentəns] n. 句子", a: "sentence", note: "the meaning of the sentence" },
        { q: "[pɔɪnt] v.（用手或细的物体）指", a: "point", note: "point at / point out" },
        { q: "[pɔɪnt aʊt]（词组）指出，指明", a: "point out", note: "短语动词" },
        { q: "[mɪˈsteɪk] n. 错误", a: "mistake", note: "make mistakes 犯错误" },
        { q: "[pəˈlaɪt] adj. 有礼貌的，客气的", a: "polite", note: "be polite to sb" },
        { q: "[maɪnd] n. 头脑；思想，思维", a: "mind", note: "go into one's mind" },
        { q: "[hɜːz] pron. 她的", a: "hers", note: "名词性物主代词" },
        { q: "[draɪ] adj. 干的，干燥的", a: "dry", note: "hot and dry" },
        { q: "[ˈmiːnɪŋ] n. 意义，意思，含义", a: "meaning", note: "mean → meaning" },
        { q: "[fækt] n. 事实；真相", a: "fact", note: "in fact 事实上" },
        { q: "[ɪn ˈfækt]（词组）事实上", a: "in fact", note: "句首常用" },
        { q: "[niːd] v. 需要", a: "need", note: "need to do sth" },
        { q: "[rɪˈmembə(r)] v. 记住，记得", a: "remember", note: "remember to do / doing" },
        { q: "[ˈriːəli] adv. 确切地，的确", a: "really", note: "修饰形容词" },
        { q: "[ɪmˈpɔːtnt] adj. 重要的", a: "important", note: "an important lesson" },
      ],
    },
    {
      id: "phrases",
      title: "二、词组过关（按提示补全句子）",
      type: "fill",
      items: [
        { q: "New students ____ flowers ____（把……给……）their teachers.", a: "take to", accept: ["give to"], zh: "新生们把花送给他们的老师。", note: "take sth to sb 把某物带给某人。" },
        { q: "Is it OK to ____ ____（指出）the mistake?", a: "point out", zh: "指出这个错误可以吗？", note: "point out 指出，短语动词。" },
        { q: "But then I ____ ____ ____（多思考）the meaning of the sentence.", a: "think more about", zh: "但接着我更多地思考这个句子的意思。", note: "think about 思考。" },
        { q: "You need to ____ ____（在学习中多思考）in your learning.", a: "think more", zh: "你需要在学习中多思考。", note: "need to do sth。" },
        { q: "We should ____ ____（向……学习）great thinkers.", a: "learn from", zh: "我们应该向伟大的思想家学习。", note: "learn from sb 向某人学习。" },
      ],
    },
    {
      id: "wordform",
      title: "三、根据句意、音标、首字母或汉语提示写单词",
      type: "fill",
      items: [
        { q: "Don't be angry when your kid makes ____ [mɪˈsteɪks].", a: "mistakes", zh: "孩子犯错时不要生气。", note: "make mistakes 犯错误，用复数。" },
        { q: "It is ____ [pəˈlaɪt] of students to say hello to their teachers.", a: "polite", zh: "学生向老师问好是有礼貌的。", note: "It is + adj. + of sb + to do sth。" },
        { q: "A good idea went into my ____ [maɪnd]. I can't wait to tell you right now.", a: "mind", zh: "一个好主意进入了我的脑海。我迫不及待要告诉你。", note: "go into one's mind 进入脑海。" },
        { q: "As summer comes, it is hot and ____ [draɪ].", a: "dry", zh: "夏天到了，天气又热又干。", note: "与 hot 并列的形容词。" },
        { q: "Fish can't live w____ water.", a: "without", zh: "鱼离开水不能生存。", note: "without 缺乏，没有。" },
      ],
    },
    {
      id: "choice",
      title: "四、单项选择",
      type: "choice",
      items: [
        {
          q: "— Reading is a good way to kill time on the plane.\n— That's true. I never go travelling ____ a book.",
          options: ["without", "from", "on"],
          a: "A",
          explain: "never ... without ... 双重否定表肯定：我旅行时总是带着书。",
        },
        {
          q: "Please ____ your hand if you know the answer.",
          options: ["put on", "put up", "put away"],
          a: "B",
          explain: "put up one's hand 举手；put on 穿上；put away 收起来。",
        },
        {
          q: "School starts ____ 8:00 a.m. from Monday to Friday.",
          options: ["at", "on", "in"],
          a: "A",
          explain: "具体的时间点前用介词 at，如 at 8:00 a.m.。",
        },
        {
          q: "— I came first in the long jump.\n— ____! I'm so proud of you.",
          options: ["Good luck", "Never mind", "Well done"],
          a: "C",
          explain: "对方取得好成绩应祝贺，用 Well done（干得好）。",
        },
        {
          q: "— I don't know how to solve this problem. It's too difficult.\n— Don't worry. Let's ____ it and find another (另外的) way.",
          options: ["learn from", "wait for", "think about"],
          a: "C",
          explain: "遇到难题要“思考”它，用 think about。",
        },
      ],
    },
    {
      id: "cloze",
      title: "五、语法填空（首字母及括号提示）",
      type: "cloze",
      passage: [
        "I am Mr Li. In my maths class today, I walk to the blackboard and write down a formula (公式): a² + b² = c².",
        "After writing it down, I turn around {{1}} say to the class, “Now, everyone, please write this formula down in your {{2}} (notebook) and think about when we can use it.”",
        "Then I start {{3}} (walk) around the classroom to check on the students. There are 40 students. Most of {{4}} (they) are busily writing, but I see a girl — Lily. The girl is sitting there thinking, without {{5}} (write) anything.",
        "Suddenly, Lily puts up her hand. I nod (点头). She {{6}} (stand) up and says, “Mr Li, I think we can only use this formula when we meet right-angled triangles (直角三角形).”",
        "I smile at {{7}} (she) and say, “Well done, Lily!” Then I say to the class, “In fact, you are now in junior high school, and maths will be {{8}} (much) difficult. Always think carefully in your {{9}} (learn)! That's {{10}} (real) an important lesson!”",
      ],
      blanks: [
        { n: 1, a: "and", hint: "无提示", explain: "turn around 与 say 是两个并列动作，用 and 连接。" },
        { n: 2, a: "notebooks", hint: "notebook", explain: "your 后接可数名词复数 notebooks。" },
        { n: 3, a: "to walk", hint: "walk", explain: "start to do sth 开始做某事。" },
        { n: 4, a: "them", hint: "they", explain: "of 是介词，后接人称代词宾格 them。" },
        { n: 5, a: "writing", hint: "write", explain: "without 是介词，后接动名词 writing。" },
        { n: 6, a: "stands", hint: "stand", explain: "一般现在时，主语 She 是第三人称单数，用 stands。" },
        { n: 7, a: "her", hint: "she", explain: "at 是介词，后接宾格 her。" },
        { n: 8, a: "more", hint: "much", explain: "much 的比较级是 more，more difficult 更难。" },
        { n: 9, a: "learning", hint: "learn", explain: "your 后接名词，用动名词 learning（学习）。" },
        { n: 10, a: "really", hint: "real", explain: "修饰形容词 important 用副词 really。" },
      ],
    },
    {
      id: "translate",
      title: "六、根据中文意思和英文提示词语写出句子",
      type: "translate",
      items: [
        { zh: "我对开启初中生活感到很兴奋。(excited)", a: "I'm excited about my junior high school life.", note: "be excited about sth 对……感到兴奋。" },
        { zh: "开学第一天，新生们和他们的父母一起参观学校。(parent)", a: "On the first day of school, new students visit the school with their parents.", note: "with 表示“和……一起”；first day 用序数词。" },
        { zh: "在学习中犯错没关系。(OK; mistake)", a: "It's OK to make mistakes in your learning.", note: "It's OK to do sth；make mistakes 犯错误。" },
        { zh: "我突然想到一个问题。(jump into)", a: "A problem suddenly jumped into my mind.", note: "jump into one's mind 突然想到。" },
        { zh: "在我的英语课上，我学到了很重要的一课。(learn)", a: "I learned a very important lesson in my English class.", note: "learn a lesson 学到一课。" },
      ],
    },
  ],
};