// 七年级上册 Unit 1 Homework 2: Understanding Ideas (2) —— 人称代词与物主代词专项
export default {
  id: "tb7a-u1-2",
  book: "七年级上册",
  unit: "Unit 1",
  title: "Homework 2: Understanding ideas (2)",
  subtitle: "人称代词与物主代词专项",
  source: "基础同步达标手册 七年级上（北京市三帆中学）",
  pages: "P12–P13",
  vocab: [
    { word: "cousin", phonetic: "ˈkʌzn", pos: "n.", meaning: "堂（表）兄弟姐妹", use: "my cousins 我的堂（表）兄弟姐妹" },
    { word: "university", phonetic: "ˌjuːnɪˈvɜːsəti", pos: "n.", meaning: "大学", use: "university student 大学生" },
    { word: "camera", phonetic: "ˈkæmərə", pos: "n.", meaning: "照相机", use: "a white camera" },
    { word: "dictionary", phonetic: "ˈdɪkʃənri", pos: "n.", meaning: "词典，字典", use: "borrow your dictionary" },
    { word: "borrow", phonetic: "ˈbɒrəʊ", pos: "v.", meaning: "借（入）", use: "borrow sth from sb 向某人借某物" },
    { word: "teach", phonetic: "tiːtʃ", pos: "v.", meaning: "教", use: "teach sb sth / teach sb to do sth" },
    { word: "silly", phonetic: "ˈsɪli", pos: "adj.", meaning: "愚蠢的，傻的", use: "a silly answer" },
    { word: "lucky", phonetic: "ˈlʌki", pos: "adj.", meaning: "幸运的", use: "be lucky to do sth" },
    { word: "smile", phonetic: "smaɪl", pos: "n./v.", meaning: "微笑", use: "with a smile 带着微笑" },
    { word: "clever", phonetic: "ˈklevə(r)", pos: "adj.", meaning: "聪明的", use: "clever words 聪明的话" },
  ],
  phrases: [
    { en: "a new friend of mine", zh: "我的一个新朋友", tip: "“a friend of + 名词性物主代词”表示“我的一个朋友”" },
    { en: "with a smile", zh: "带着微笑", tip: "with + 名词，在句中作状语" },
    { en: "make sb feel better", zh: "使某人感觉更好", tip: "make sb do sth / make sb + adj." },
    { en: "be lucky to do sth", zh: "幸运地做某事", tip: "You are lucky to have a good friend like her." },
    { en: "introduce oneself", zh: "介绍某人自己", tip: "反身代词要与主语一致：introduce himself" },
    { en: "in junior high", zh: "在初中", tip: "junior high (school) 初中" },
    { en: "help sb do sth", zh: "帮助某人做某事", tip: "help us to work better" },
  ],
  patterns: [
    { en: "Ava is her new friend at junior high.", zh: "Ava 是她在初中的一位新朋友。", note: "也可以用 Ava is a new friend of hers." },
    { en: "Our English teacher asks us to introduce ourselves.", zh: "我们的英语老师让我们做自我介绍。", note: "ask sb to do sth；ourselves 与 us 一致。" },
    { en: "He gave a silly answer, and then his face turned red.", zh: "他给出了一个傻傻的答案，然后他的脸红了。", note: "turn + 颜色 表示“变成……色”。" },
    { en: "Ms Lin looks at us with a smile.", zh: "林老师面带微笑地看着我们。", note: "look at sb with a smile。" },
    { en: "You are lucky to have a good friend like her.", zh: "你很幸运有一位像她这样的好朋友。", note: "be lucky to do sth。" },
  ],
  grammar: [
    {
      title: "人称代词（主格与宾格）",
      points: [
        "主格：I, you, he, she, it, we, you, they —— 在句中作主语。",
        "宾格：me, you, him, her, it, us, you, them —— 在句中作动词或介词的宾语。",
        "例：We all make mistakes. / He doesn't believe me. / Most of them are writing.",
        "口语中宾格可作表语：— Who is it? — It's me.",
      ],
    },
    {
      title: "it 的用法",
      points: [
        "指代前面提到的事物或不明身份的人：It's a fine day today.",
        "表示时间、天气、距离等：It's 11 o'clock. / It's 20 km from here.",
        "作形式主语：It is polite of students to say hello to their teachers. / It takes me 20 minutes to walk home.",
      ],
    },
    {
      title: "人称代词的排列顺序",
      points: [
        "单数按“二、三、一”排列：you, he/she, I —— You, he and I are all students.",
        "复数按“一、二、三”排列：we, you, they。",
        "表示承认错误、承担责任时，把第一人称 I / we 放在最前面：I and Tom broke the window.",
      ],
    },
    {
      title: "物主代词（形容词性与名词性）",
      points: [
        "形容词性物主代词后必须跟名词：my book, your pen, its tail, their school。",
        "名词性物主代词起名词作用，后面不再跟名词：mine, yours, his, hers, its, ours, yours, theirs。",
        "“a friend of + 名词性物主代词”：Kate is a friend of his.",
        "例：The red one is yours (= your pencil). And the blue one is mine (= my pencil).",
      ],
    },
  ],
  examPoints: [
    "动词、介词后接人称代词宾格：help us / look at me / most of them。",
    "名词前用形容词性物主代词，单独使用用名词性物主代词：my dictionary / It's mine。",
    "its（它的）与 it's（it is）的区别：its tail；It's a fine day.。",
    "a friend of mine / his 等“of + 名词性物主代词”结构。",
    "单数人称代词按“二、三、一”排列，复数按“一、二、三”排列。",
  ],
  sections: [
    {
      id: "phrases",
      title: "一、词组过关（按提示补全句子）",
      type: "fill",
      items: [
        { q: "Fang Wei is ____ ____ ____（我的一个新朋友）.", a: "my new friend", zh: "方伟是我的一个新朋友。", note: "也可说 a new friend of mine。" },
        { q: "He ____ to introduce ____（介绍他自己）.", a: "likes himself", accept: ["wants himself", "hopes himself", "would like himself", "likes his"], zh: "他喜欢介绍他自己。", note: "反身代词与主语 he 一致，用 himself。" },
        { q: "But Mr Pan just looks at me ____ ____（带着微笑）.", a: "with a smile", zh: "但潘老师只是微笑着看着我。", note: "with a smile 作状语。" },
        { q: "His clever words ____ ____ ____（让……感觉）better.", a: "make me feel", zh: "他聪明的话语让我感觉好多了。", note: "make sb do sth 后接动词原形。" },
        { q: "I ____ ____ ____（如此幸运能……）have a teacher like him.", a: "am so lucky to", zh: "我很幸运能有一位像他这样的老师。", note: "be lucky to do sth。" },
      ],
    },
    {
      id: "grammar-recap",
      title: "二、语法回顾（补全代词知识）",
      tip: "这一部分是代词体系的知识梳理，先想清楚“作什么成分”，再决定用哪种代词。",
      type: "fill",
      items: [
        { q: "人称代词是用来 ____（代替）人或事物的词，有人称、数和格的变化。", a: "代替", zh: "人称代词替代人或事物。", note: "人称代词有主格和宾格之分。" },
        { q: "人称代词在句中作 ____ 时用主格形式，作 ____ 时一般用宾格形式。", a: "主语 宾语", accept: ["主语 宾语"], zh: "主格作主语，宾格作宾语。", note: "We all make mistakes.（主格） / He doesn't believe me.（宾格）" },
        { q: "it 除指代人和事物外，还可以表示 ____、____、____ 等。", a: "时间 天气 距离", accept: ["时间 天气 距离"], zh: "it 可指时间、天气、距离。", note: "It's 11 o'clock. / It's a fine day. / It's 20 km from here." },
        { q: "英语中单数人称代词通常按“二、三、一”排列，即 ____。", a: "you, she/he, I", accept: ["you she he I", "you, he, I"], zh: "单数顺序：you, she/he, I。", note: "You, he and I are all students." },
        { q: "英语中复数人称代词通常按“一、二、三”排列，即 ____。", a: "we, you, they", accept: ["we you they"], zh: "复数顺序：we, you, they。", note: "We, you and they are all here." },
        { q: "在表示承认错误、承担责任时，应该把 ____ 放在首位。", a: "第一人称", accept: ["I", "第一人称 I"], zh: "承认错误时第一人称放前面。", note: "I and Tom broke the window." },
        { q: "物主代词是表示 ____ 的代词，分为形容词性物主代词和名词性物主代词。", a: "所有关系", zh: "物主代词表示所有关系。", note: "my / mine, your / yours ..." },
        { q: "形容词性物主代词起形容词的作用，其后要跟 ____。", a: "名词", zh: "形容词性物主代词后必须跟名词。", note: "my book, your pen, its tail。" },
        { q: "名词性物主代词起名词的作用，其后不再跟 ____。", a: "名词", zh: "名词性物主代词后不再跟名词。", note: "The book is mine." },
        { q: "Look at the two pencils. The red one is ____ (= your pencil). And the blue one is mine (= ____).", a: "yours my pencil", accept: ["yours, my pencil"], zh: "红的那支是你的，蓝的是我的。", note: "yours = your pencil；mine = my pencil。" },
        { q: "在“a friend of ...” “a classmate of ...” 等后面应用 ____ 物主代词。", a: "名词性", zh: "of 后用名词性物主代词。", note: "Kate is a friend of his." },
      ],
    },
    {
      id: "choice",
      title: "三、单项选择",
      type: "choice",
      items: [
        {
          q: "These are my cousins. ____ are both university students.",
          options: ["We", "You", "They", "She"],
          a: "C",
          explain: "指代上句的 my cousins（复数），作主语用主格 They。",
        },
        {
          q: "Using AI tools in the right way can help ____ to work better.",
          options: ["we", "us", "our", "ours"],
          a: "B",
          explain: "help 后接人称代词宾格作宾语，用 us。",
        },
        {
          q: "Mike's aunt is ____ English teacher. We all like ____.",
          options: ["our; she", "our; her", "we; she", "we; her"],
          a: "B",
          explain: "名词前用形容词性物主代词 our；like 后接宾格 her。",
        },
        {
          q: "— Leo, is this white camera your brother's?\n— Yes, it's ____. My mother bought it for ____ a week ago.",
          options: ["his; him", "he's; him", "he's; he", "his; he"],
          a: "A",
          explain: "名词性物主代词 his 单独使用；for 后接宾格 him。",
        },
        {
          q: "— Jim, may I borrow ____ dictionary?\n— Oh, sorry. ____ is at home.",
          options: ["your; Mine", "your; My", "yours; Mine", "yours; My"],
          a: "A",
          explain: "dictionary 前用形容词性物主代词 your；第二空单独作主语用名词性物主代词 Mine。",
        },
      ],
    },
    {
      id: "wordform",
      title: "四、用所给词的适当形式填空",
      type: "fill",
      items: [
        { q: "Tony often brings ____ (he) favourite books to school and shares ____ (they) with ____ (I).", a: "his them me", accept: ["his, them, me"], zh: "托尼常把他最喜欢的书带到学校，并与我分享。", note: "名词前用 his；shares 后接宾格 them；with 后接宾格 me。" },
        { q: "Mr Pan teaches ____ English. (we)", a: "us", zh: "潘老师教我们英语。", note: "teach sb sth，用宾格 us。" },
        { q: "The monkey is 40 cm tall, and ____ (it) tail is about 30 cm long.", a: "its", zh: "这只猴子 40 厘米高，它的尾巴大约 30 厘米长。", note: "its 是形容词性物主代词，注意与 it's 区分。" },
        { q: "My classroom is on the first floor. What about ____ (you)?", a: "yours", zh: "我的教室在一楼。你的呢？", note: "What about + 名词性物主代词 yours。" },
        { q: "____ (we) school is big, and ____ (they) is big, too.", a: "Our theirs", accept: ["Our, theirs"], zh: "我们的学校很大，他们的也很大。", note: "Our + 名词；theirs 单独使用。" },
      ],
    },
    {
      id: "translate",
      title: "五、根据中文意思和英文提示词语写出句子",
      type: "translate",
      items: [
        { zh: "Ava 是她在初中的一位新朋友。(junior high)", a: "Ava is her new friend at junior high.", note: "也可说 Ava is a new friend of hers at junior high." },
        { zh: "我们的英语老师让我们做自我介绍。(ask)", a: "Our English teacher asks us to introduce ourselves.", note: "ask sb to do sth；ourselves 与 us 一致。" },
        { zh: "他给出了一个傻傻的答案，然后他的脸红了。(silly)", a: "He gave a silly answer, and then his face turned red.", note: "两个动作并列用 and；turn red 变红。" },
        { zh: "Ms Lin 面带微笑地看着我们。(with a smile)", a: "Ms Lin looks at us with a smile.", note: "look at sb with a smile。" },
        { zh: "你很幸运有一位像她这样的好朋友。(lucky)", a: "You are lucky to have a good friend like her.", note: "be lucky to do sth；like her 像她一样。" },
      ],
    },
  ],
};