// 七年级上册 Unit 1 Homework 3: Developing Ideas (Listening and Speaking)
export default {
  id: "tb7a-u1-3",
  book: "七年级上册",
  unit: "Unit 1",
  title: "Homework 3: Developing ideas (3)",
  subtitle: "任务与建议 · 语音辨析",
  source: "基础同步达标手册 七年级上（北京市三帆中学）",
  pages: "P15",
  vocab: [
    { word: "plan", phonetic: "plæn", pos: "v./n.", meaning: "计划", use: "plan the time well" },
    { word: "problem", phonetic: "ˈprɒbləm", pos: "n.", meaning: "问题，难题；困难", use: "state our problem 陈述我们的问题" },
    { word: "homework", phonetic: "ˈhəʊmwɜːk", pos: "n.", meaning: "家庭作业，功课", use: "不可数名词" },
    { word: "task", phonetic: "tɑːsk", pos: "n.", meaning: "工作，任务", use: "a big task 一个大任务" },
    { word: "project", phonetic: "ˈprɒdʒekt", pos: "n.", meaning: "（学校的）课题，研究项目", use: "be busy with the project" },
    { word: "advice", phonetic: "ədˈvaɪs", pos: "n.", meaning: "意见，建议；忠告，劝告", use: "不可数名词；a piece of advice" },
    { word: "activity", phonetic: "ækˈtɪvəti", pos: "n.", meaning: "活动", use: "all kinds of activities" },
    { word: "hold", phonetic: "həʊld", pos: "v.", meaning: "举行，举办", use: "hold a sports meeting" },
    { word: "state", phonetic: "steɪt", pos: "v.", meaning: "陈述，说明", use: "state our problem" },
    { word: "turn ... into ...", phonetic: "tɜːn ˈɪntuː", pos: "词组", meaning: "把……变成……", use: "turn a big task into small ones" },
  ],
  phrases: [
    { en: "hold all kinds of activities", zh: "举办各种活动", tip: "hold 举办；activity 复数 activities" },
    { en: "sports meeting", zh: "运动会", tip: "美式常用 sports meet" },
    { en: "be good at sth", zh: "擅长某事", tip: "be good at + 名词/动名词" },
    { en: "turn ... into ...", zh: "把……变成……", tip: "turn a big task into small ones" },
    { en: "work on them", zh: "从事（处理）它们", tip: "work on sth 着手做某事" },
    { en: "state our problem", zh: "陈述我们的问题", tip: "state 作动词，表示“陈述”" },
    { en: "for example", zh: "例如", tip: "后接一个例子，用逗号隔开" },
    { en: "give sb some advice", zh: "给某人一些建议", tip: "advice 不可数，用 some 修饰" },
  ],
  patterns: [
    { en: "Students' unions help to hold all kinds of activities, such as cultural festivals and sports meetings.", zh: "学生会帮助举办各种活动，例如文化节和运动会。", note: "help to do sth；such as 列举。" },
    { en: "You can turn a big task into small ones. Then work on them day by day.", zh: "你可以把一个大任务分解成小任务，然后一天天去做。", note: "ones 代替前面提到的可数名词复数。" },
    { en: "We can first state our problem to get help. For example, it's hard to plan time.", zh: "我们可以先陈述问题以获得帮助。例如，很难安排好时间。", note: "first ... then ... 表示顺序。" },
    { en: "Can you give me some advice?", zh: "你能给我一些建议吗？", note: "advice 不可数，不能说 an advice。" },
  ],
  grammar: [
    {
      title: "advice 与 suggestion",
      points: [
        "advice 是不可数名词：some advice / a piece of advice。",
        "suggestion 是可数名词：a suggestion / some suggestions。",
        "常见搭配：give sb some advice on sth；ask sb for advice。",
      ],
    },
    {
      title: "ones 代替可数名词复数",
      points: [
        "one 代替前面提到的可数名词单数，ones 代替复数：turn a big task into small ones。",
        "注意：it / them 指同一个事物，one / ones 指同类中的一个（些）。",
      ],
    },
    {
      title: "常见字母组合的发音",
      points: [
        "ar 在 car, hard 中读 /ɑː/，但在 hat 中 a 读 /æ/，make 中 a-e 读 /eɪ/。",
        "a 在 apple, fact, jacket, lab 中读 /æ/；在 eraser, advice, geography 中读 /ɪ/ 或 /ə/。",
        "e 在 bed, red, head 中读 /e/；在 eat 中 ea 读 /iː/；在 delicious, remember 中 e 读 /ɪ/。",
        "i 在 friend 中 ie 读 /e/。",
      ],
    },
  ],
  examPoints: [
    "hold 与 have 辨析：hold a meeting / hold a sports meeting（举办、举行）。",
    "turn A into B 中 into 不能换成 in。",
    "advice 不可数，用 some/much 修饰，没有复数形式。",
    "work on sth（从事、处理）与 work at sth（致力于）的区别。",
    "元音字母在开音节、闭音节中的不同读音（car-hard, apple-fact, bed-head）。",
  ],
  sections: [
    {
      id: "words",
      title: "一、单词巩固（看音标和中文写单词）",
      type: "dictation",
      items: [
        { q: "[plæn] v. 计划", a: "plan", note: "plan to do sth" },
        { q: "[ˈprɒbləm] n. 问题，难题；困难", a: "problem", note: "solve the problem" },
        { q: "[ˈhəʊmwɜːk] n. 家庭作业，功课", a: "homework", note: "不可数名词" },
        { q: "[tɑːsk] n. 工作，任务", a: "task", note: "a big task" },
        { q: "[ˈprɒdʒekt] n.（学校的）课题，研究项目", a: "project", note: "do a project" },
        { q: "[ədˈvaɪs] n. 意见，建议；忠告，劝告", a: "advice", note: "不可数名词" },
      ],
    },
    {
      id: "phrases",
      title: "二、词组过关（按提示补全句子）",
      type: "fill",
      items: [
        { q: "Students' unions help to ____（举办）all kinds of ____（活动）, such as cultural festivals and ____ ____（运动会）.", a: "hold activities sports meeting", accept: ["hold, activities, sports meeting"], zh: "学生会帮助举办各种活动，如文化节和运动会。", note: "hold 举办；activity 复数为 activities。" },
        { q: "It's hard to ____ ____ ____（在……方面做得好）exams.", a: "be good at", zh: "要在考试中表现出色很难。", note: "be good at + 名词/动名词。" },
        { q: "You can ____ a big task ____（把……变成）small ones. Then ____ ____ ____（从事它们）day by day.", a: "turn into work on them", accept: ["turn, into, work on them"], zh: "你可以把大任务变成小任务，然后一天天去做。", note: "turn A into B；work on sth。" },
        { q: "We can first ____ ____ ____（陈述我们的问题）to get help. ____ ____（例如）, it's hard to plan time.", a: "state our problem For example", accept: ["state our problem, For example"], zh: "我们可以先陈述问题来获得帮助。例如，很难安排好时间。", note: "state 作动词“陈述”。" },
        { q: "Can you ____ ____ ____ ____（给我一些建议）?", a: "give me some advice", zh: "你能给我一些建议吗？", note: "advice 不可数，用 some 修饰。" },
      ],
    },
    {
      id: "wordform",
      title: "三、根据句意、音标、首字母或汉语提示写单词",
      type: "fill",
      items: [
        { q: "I asked the teacher for a ____ first, and then took action.", a: "task", accept: ["problem"], zh: "我先向老师要了一项任务，然后采取行动。", note: "task 任务；也可理解为 problem（问题）。" },
        { q: "It's difficult to complete so many ____（任务）in a short period of time.", a: "tasks", zh: "在短时间内完成这么多任务很困难。", note: "many 后接可数名词复数。" },
        { q: "It's a nice table! The only ____ [ˈprɒbləm] is: It's too big for our room.", a: "problem", zh: "这是张好桌子！唯一的问题是：它对我们房间来说太大了。", note: "the only problem is ... 唯一的问题是……" },
        { q: "— Would you like to go with me to have a trip this weekend?\n— I'd love to, but I'm busy with the ____（研究项目）. I have to finish it next week.", a: "project", zh: "——这个周末你想和我一起去旅行吗？——我想去，但我正忙于这个研究项目。下周我必须完成它。", note: "be busy with sth 忙于某事。" },
        { q: "It's hard to ____（计划）the time well.", a: "plan", zh: "很难把时间计划好。", note: "to 后接动词原形，不要重复写 to。" },
      ],
    },
    {
      id: "phonetics",
      title: "四、选出与划线部分发音相同的单词",
      tip: "先读准划线字母组合的读音，再逐一比较选项。",
      type: "choice",
      items: [
        {
          q: "car（划线 a）",
          options: ["hat", "hard", "make"],
          a: "B",
          explain: "car 中 ar 读 /ɑː/，hard 中 ar 也读 /ɑː/；hat 中 a 读 /æ/，make 中 a-e 读 /eɪ/。",
        },
        {
          q: "apple（划线 a）",
          options: ["eraser", "advice", "fact"],
          a: "C",
          explain: "apple 中 a 读 /æ/，fact 中 a 也读 /æ/；eraser、advice 中的 a 读 /ɪ/ 或 /ə/。",
        },
        {
          q: "friend（划线 ie）",
          options: ["delicious", "red", "remember"],
          a: "B",
          explain: "friend 中 ie 读 /e/，red 中 e 也读 /e/；delicious、remember 中的 e 读 /ɪ/。",
        },
        {
          q: "jacket（划线 a）",
          options: ["lab", "geography", "mistake"],
          a: "A",
          explain: "jacket 中 a 读 /æ/，lab 中 a 也读 /æ/；geography 中 a 读 /ə/，mistake 中 a-e 读 /eɪ/。",
        },
        {
          q: "bed（划线 e）",
          options: ["hers", "eat", "head"],
          a: "C",
          explain: "bed 中 e 读 /e/，head 中 ea 也读 /e/；hers 中 er 读 /ɜː/，eat 中 ea 读 /iː/。",
        },
      ],
    },
    {
      id: "cloze",
      title: "五、语法填空（阅读下面短文，填入适当的词或正确形式）",
      type: "cloze",
      passage: [
        "On the first day of school, there is a new student in our class. He is very small, so we call him “Chibi”. He {{1}} (wear) a cap every day. He sits in the back of {{2}} (we) classroom. The boy walks to school on weekdays. “Chibi” means “little boy” in Japanese. This boy is afraid of our teachers and isn't good at subjects. The other {{3}} (child) don't like him. He doesn't share his ideas {{4}} others.",
        "Five years go by and we are in the sixth grade now. Our new teacher, Mr Isobe, is {{5}} very nice man. He likes to take us to the park behind the school. He is {{6}} (interest) in seeing how much “Chibi” knows about flowers, plants and animals.",
        "This year, “Chibi” wants {{7}} (join) in the school talent show (才艺表演). He will speak like different {{8}} (bird). The boy knows so much {{9}} he walks across the farm every day. And he {{10}} (real) likes nature. Now nobody calls him “Chibi”. And we think we're very lucky to have a classmate like him.",
      ],
      blanks: [
        { n: 1, a: "wears", hint: "wear", explain: "every day 提示一般现在时，主语 He 是第三人称单数，用 wears。" },
        { n: 2, a: "our", hint: "we", explain: "classroom 前用形容词性物主代词 our。" },
        { n: 3, a: "children", hint: "child", explain: "The other 后接可数名词复数，child → children。" },
        { n: 4, a: "with", hint: "无提示", explain: "share sth with sb 与某人分享某物。" },
        { n: 5, a: "a", hint: "无提示", explain: "man 是可数名词单数，第一次提到用 a。" },
        { n: 6, a: "interested", hint: "interest", explain: "be interested in 对……感兴趣，主语是人。" },
        { n: 7, a: "to join", hint: "join", explain: "want to do sth 想做某事。" },
        { n: 8, a: "birds", hint: "bird", explain: "different 后接可数名词复数。" },
        { n: 9, a: "because", hint: "无提示", explain: "so much ... because ... 表示原因；也可理解为 so ... that 结构，结合语境填 because。" },
        { n: 10, a: "really", hint: "real", explain: "修饰动词 likes 用副词 really。" },
      ],
    },
    {
      id: "translate",
      title: "六、根据中文意思和英文提示词语写出句子",
      type: "translate",
      items: [
        { zh: "学生会经常帮助学生们解决他们的问题。(The Students' Union)", a: "The Students' Union often helps students with their problems.", note: "help sb with sth 在某方面帮助某人。" },
        { zh: "我们应该学会好好利用我们的空闲时间。(free time)", a: "We should learn to make good use of our free time.", note: "make good use of 好好利用。" },
        { zh: "天气在一天天地变暖。(warm)", a: "It's getting warmer day by day.", note: "get + 比较级 表示“变得……”；day by day 一天天地。" },
        { zh: "他给我提了两条建议。(piece)", a: "He gave me two pieces of advice.", note: "advice 不可数，两条建议用 two pieces of advice。" },
        { zh: "你需要花一些时间来照顾这些植物。(It takes...; take care of)", a: "It takes you some time to take care of these plants.", note: "It takes sb some time to do sth 某人花一些时间做某事。" },
      ],
    },
  ],
};