// 七年级上册 Unit 1 Homework 4: Developing ideas (Reading for writing 1)
export default {
  id: "tb7a-u1-4",
  book: "七年级上册",
  unit: "Unit 1",
  title: "Homework 4: Developing ideas (Reading for writing 1)",
  subtitle: "启航之信 · 保护与前行",
  source: "基础同步达标手册 七年级上（北京市三帆中学）",
  pages: "P17–P18",
  vocab: [
    { word: "journey", phonetic: "ˈdʒɜːni", pos: "n.", meaning: "旅行，旅程；历程，过程", use: "a new journey in our lives" },
    { word: "something", phonetic: "ˈsʌmθɪŋ", pos: "pron.", meaning: "某物，某事；某些东西", use: "We've got something for you!" },
    { word: "thought", phonetic: "θɔːt", pos: "n.", meaning: "意见，主意，观点", use: "share some thoughts with you" },
    { word: "life", phonetic: "laɪf", pos: "n.", meaning: "生活；生命", use: "Are you ready for your new life?" },
    { word: "primary school", phonetic: "ˈpraɪməri skuːl", pos: "词组", meaning: "小学", use: "Primary school is like a small pool." },
    { word: "pool", phonetic: "puːl", pos: "n.", meaning: "水塘，水洼；游泳池", use: "a small pool 一个小水塘" },
    { word: "protect", phonetic: "prəˈtekt", pos: "v.", meaning: "保护；防护", use: "protect it from winds" },
    { word: "wind", phonetic: "wɪnd", pos: "n.", meaning: "风", use: "a strong wind 大风" },
    { word: "wide", phonetic: "waɪd", pos: "adj.", meaning: "宽的，宽阔的", use: "It is wide and the water moves fast." },
    { word: "sail", phonetic: "seɪl", pos: "v.", meaning: "驾驶（船只）；航行", use: "sail your boat by yourself" },
    { word: "through", phonetic: "θruː", pos: "prep.", meaning: "从一端至另一端，穿过，通过", use: "go through storms" },
    { word: "storm", phonetic: "stɔːm", pos: "n.", meaning: "暴风雨（雪）", use: "go through storms towards the sea" },
    { word: "towards", phonetic: "təˈwɔːdz", pos: "prep.", meaning: "向着，朝着（某个方向）", use: "towards the sea 朝着大海" },
    { word: "hope", phonetic: "həʊp", pos: "v. & n.", meaning: "希望，期望，指望", use: "We hope this letter helps you." },
  ],
  phrases: [
    { en: "share sth with sb", zh: "和某人分享某事", tip: "We want to share some thoughts with you." },
    { en: "protect ... from ...", zh: "保护……免受……", tip: "protect it from winds 保护它免受风吹" },
    { en: "go through", zh: "经历；穿过", tip: "go through storms towards the sea" },
    { en: "stand for", zh: "代表，象征", tip: "What do they stand for? 它们代表什么？" },
    { en: "sail one's boat", zh: "驾驶自己的船（自己闯荡）", tip: "sometimes you have to sail your boat by yourself" },
    { en: "try one's best", zh: "尽某人最大努力", tip: "try your best and work hard" },
    { en: "be ready for", zh: "为……做好准备", tip: "Are you ready for your new life?" },
    { en: "say thanks to sb", zh: "向某人表示感谢", tip: "Say thanks to Dad and Mum." },
  ],
  patterns: [
    { en: "Time flies! You are now in junior high!", zh: "时光飞逝！你现在已经上初中了！", note: "Time flies! 是常用感叹句，表示时间过得快。" },
    { en: "Primary school is like a small pool. Your boat is safe there.", zh: "小学就像一个小水塘，你的小船在那里很安全。", note: "be like 像……，用比喻说明道理。" },
    { en: "Dad and Mum can protect it from winds.", zh: "爸爸妈妈能保护它免受风吹。", note: "protect ... from ... 保护……免受……。" },
    { en: "But junior high is like a river. It is wide and the water moves fast.", zh: "但初中就像一条河，它很宽，水流也很快。", note: "用 river 与 pool 对比，说明初中生活更有挑战。" },
    { en: "But sometimes you have to sail your boat by yourself.", zh: "但有时你必须独自驾驶你的小船。", note: "by oneself 独自，单独；have to 不得不。" },
    { en: "Just try your best and work hard. You will go through storms towards the sea.", zh: "只要尽你最大努力，努力学习。你会穿过暴风雨驶向大海。", note: "will + 动词原形表示将来。" },
    { en: "We hope this letter helps you in the coming years!", zh: "我们希望这封信在未来的日子里对你有帮助！", note: "hope + 从句；in the coming years 在未来的岁月里。" },
  ],
  grammar: [
    {
      title: "反身代词与 by oneself",
      points: [
        "单数：myself / yourself / himself / herself / itself；复数：ourselves / yourselves / themselves。",
        "by oneself 表示“独自，靠自己”：you have to sail your boat by yourself。",
        "反身代词还可表示“亲自”：I made the model plane myself.",
      ],
    },
    {
      title: "一般将来时 will + 动词原形",
      points: [
        "表示将来会发生的事：You will face new problems. / You will go through storms towards the sea.",
        "否定形式为 will not (won't) + 动词原形；一般疑问句把 will 提到句首。",
      ],
    },
    {
      title: "介词后接名词、代词宾格或动名词",
      points: [
        "from winds（名词）／with you（代词宾格）／without thinking（动名词）。",
        "towards the sea、through storms 中的 towards 和 through 都是介词，后面要接宾语。",
      ],
    },
    {
      title: "hope 与 like 的常用结构",
      points: [
        "hope (that) + 从句：We hope this letter helps you.；hope to do sth：I hope to see you soon.",
        "like 作介词表示“像”：Junior high is like a river.；like 作动词表示“喜欢”：I like reading.",
      ],
    },
  ],
  examPoints: [
    "看音标写单词：[ˈdʒɜːni] journey、[θɔːt] thought、[θruː] through、[stɔːm] storm、[təˈwɔːdz] towards、[waɪd] wide。",
    "try one's best to do sth 尽最大努力做某事；by oneself 独自。",
    "hope 的三单形式是 hopes；hope 后接从句或 to do sth，不能接 doing。",
    "decide to do sth（decided to help them）；like doing sth（is like sailing without a compass）。",
    "阅读加油站生词：stay up late 熬夜、finish 完成、break 休息。",
  ],
  sections: [
    {
      id: "words",
      title: "一、单词巩固（看音标和中文写单词）",
      type: "dictation",
      items: [
        { q: "[ˈdʒɜːni] n. 旅行，旅程；历程，过程", a: "journey", note: "a new journey 一段新的旅程" },
        { q: "[ˈsʌmθɪŋ] pron. 某物，某事；某些东西", a: "something", note: "用在肯定句中；疑问、否定句常用 anything" },
        { q: "[θɔːt] n. 意见，主意，观点", a: "thought", note: "share some thoughts with you" },
        { q: "[laɪf] n. 生活；生命", a: "life", note: "复数 lives" },
        { q: "[ˈpraɪməri skuːl]（词组）小学", a: "primary school", note: "at primary school 在小学" },
        { q: "[puːl] n. 水塘，水洼", a: "pool", note: "a small pool 一个小水塘" },
        { q: "[prəˈtekt] v. 保护；防护", a: "protect", note: "protect ... from ... 保护……免受……" },
        { q: "[wɪnd] n. 风", a: "wind", note: "注意与 wind /waɪnd/（蜿蜒）区分" },
        { q: "[waɪd] adj. 宽的，宽阔的", a: "wide", note: "反义词 narrow" },
        { q: "[seɪl] v. 驾驶（船只）", a: "sail", note: "sail your boat 驾驶你的船" },
        { q: "[θruː] prep. 从一端至另一端，穿过，通过", a: "through", note: "go through 穿过；经历" },
        { q: "[stɔːm] n. 暴风雨（雪）", a: "storm", note: "go through storms 经历暴风雨" },
        { q: "[təˈwɔːdz] prep. 向着，朝着（某个方向）", a: "towards", note: "towards the sea 朝着大海" },
        { q: "[həʊp] v. 希望，期望，指望", a: "hope", note: "hope (that) + 从句 / hope to do sth" },
      ],
    },
    {
      id: "phrases",
      title: "二、词组过关（按提示补全句子）",
      type: "fill",
      items: [
        { q: "We want to ____ ____ ____（分享一些想法）with you.", a: "share some thoughts", zh: "我们想和你分享一些想法。", note: "share sth with sb 和某人分享某事。" },
        { q: "Dad and Mum can ____ it ____（保护……免受……）winds.", a: "protect from", zh: "爸爸妈妈能保护它免受风吹。", note: "protect ... from ... 保护……免受……。" },
        { q: "You will ____ ____（经历；穿过）storms towards the sea.", a: "go through", zh: "你会穿过暴风雨驶向大海。", note: "go through 经历；穿过。" },
        { q: "What do a small pool, a river and the sea ____ ____（代表）?", a: "stand for", zh: "一个小水塘、一条河和大海代表什么？", note: "stand for 代表，象征。" },
        { q: "____ ____ ____（向……表示感谢）Dad and Mum.", a: "Say thanks to", accept: ["Thank"], zh: "向爸爸妈妈表示感谢。", note: "say thanks to sb 向某人表示感谢。" },
      ],
    },
    {
      id: "wordform",
      title: "三、根据句意、音标、首字母或汉语提示写单词",
      type: "fill",
      items: [
        { q: "Our parents ____ [prəˈtekt] us when we were young.", a: "protect", zh: "我们小的时候父母保护我们。", note: "根据音标和句意填写动词 protect。" },
        { q: "It's very cold tonight because of the strong w____ and heavy snow.", a: "wind", zh: "今晚很冷，因为风很大还下着大雪。", note: "strong wind 大风。" },
        { q: "While I was going t____ the forest, I fell on the ground.", a: "through", zh: "当我穿过森林时，我摔倒在地上。", note: "go through 穿过。" },
        { q: "Confucius ____（思想）are very helpful for our learning.", a: "thoughts", zh: "孔子的思想对我们的学习很有帮助。", note: "thought 作“思想”讲常用复数 thoughts。" },
        { q: "We feel very comfortable driving on ____ [waɪd] and flat roads.", a: "wide", zh: "行驶在宽阔平坦的路上我们感觉很舒服。", note: "wide and flat 又宽又平。" },
      ],
    },
    {
      id: "formfill",
      title: "四、用所给词的适当形式填空",
      type: "fill",
      items: [
        { q: "Sometimes you have to sail your boat by ____ (you). Just try your best.", a: "yourself", zh: "有时你必须独自驾驶你的小船。", note: "by oneself 独自，用反身代词 yourself。" },
        { q: "Her mother always ____ (hope) that she can get good grades.", a: "hopes", zh: "她妈妈总希望她能取得好成绩。", note: "主语 her mother 是第三人称单数，用 hopes。" },
        { q: "You should try ____ (you) best to finish the task today.", a: "your", zh: "今天你应该尽最大努力完成任务。", note: "try one's best 中的 one's 要用形容词性物主代词 your。" },
        { q: "He heard that the farmers were very poor and decided ____ (help) them.", a: "to help", zh: "他听说农民们很穷，决定帮助他们。", note: "decide to do sth 决定做某事。" },
        { q: "Living without an aim (目标) is like ____ (sail) without a compass (指南针).", a: "sailing", zh: "生活没有目标就像航海没有指南针。", note: "like 是介词，后接动名词 sailing。" },
      ],
    },
    {
      id: "translate",
      title: "五、根据中文意思和英文提示词语写出句子",
      type: "translate",
      items: [
        { zh: "他们想要把这个盒子做成一个飞机模型。(turn; model plane)", a: "They want to turn this box into a model plane.", note: "turn ... into ... 把……变成……。" },
        { zh: "我经常和我的父母分享我的快乐的学校生活。(share)", a: "I often share my happy school life with my parents.", note: "share sth with sb 和某人分享某事。" },
        { zh: "你应该尽最大努力实现自己的梦想。(make ... come true)", a: "You should try your best to make your dream come true.", note: "try one's best to do sth；make sth come true 使梦想成真。" },
        { zh: "在夜里独自一个人出去不安全。(safe)", a: "It is not safe to go out alone at night.", note: "It is + adj. + to do sth；alone 独自。" },
        { zh: "我们需要帽子来保护我们免受日晒。(protect)", a: "We need hats to protect us from the sun.", note: "protect ... from ... 保护……免受……。" },
      ],
    },
    {
      id: "reading",
      title: "六、阅读加油站（阅读短文，从文中找出下列句子的英文并抄写）",
      tip: "高效写作业秘籍。易读度 88.6，词数 269，建议用时 6 分钟。先读题干，再回原文定位。",
      type: "translate",
      passage: [
        "Say goodbye to your homework problems",
        "Do you have the same problem as Lisa? Don't worry. These tips might help you.",
        "1 A good study space is important. A noisy and untidy area makes it hard to focus (专注). Find a quiet place and have everything you need ready — like your books and pens. Most importantly, put your smartphone away or give it to a family member while you study.",
        "2 Before you do your homework, take two minutes to make a plan. It's great to start with the most difficult and important part. Leave the easier homework for later. This way, you'll not only finish faster but also feel less stressed (有压力的) by the end.",
        "3 Many students think that working without breaks will help them get more done. However, taking short breaks is very useful. This can help you focus better and not get too tired. A good idea is to work for 30 to 50 minutes and then take a 5- to 10-minute break. During the break, you can stretch (拉伸), eat, or do something fun to relax (放松).",
        "4 Good study habits can make learning easier. If your homework feels too hard, it might mean you didn't fully understand (理解) the lesson. Before class, try previewing (预习) the lessons to find the parts you have questions about. Then, pay close attention (特别注意) in class. Also remember, taking notes (笔记) is helpful, but it's even more important to listen carefully to the teacher.",
        "(By Wang Yuan)",
      ],
      items: [
        { zh: "找一个安静的地方，把需要的东西都准备好，比如你的书本和笔。", a: "Find a quiet place and have everything you need ready — like your books and pens.", note: "第八框第 1 条：have sth ready 把某物准备好。" },
        { zh: "从最难、最重要的部分开始做会很不错。", a: "It's great to start with the most difficult and important part.", note: "第 2 条：start with 从……开始。" },
        { zh: "一个好方法是学习30到50分钟，然后休息5到10分钟。", a: "A good idea is to work for 30 to 50 minutes and then take a 5- to 10-minute break.", note: "第 3 条：take a break 休息一下。" },
        { zh: "另外要记住，做笔记是有帮助的，但更重要的是认真听老师讲课。", a: "Also remember, taking notes is helpful, but it's even more important to listen carefully to the teacher.", note: "第 4 条：动名词 taking notes 作主语。" },
      ],
    },
  ],
};
