// 七年级上册 Unit 1 Homework 5: Developing ideas (Reading for writing 2)
export default {
  id: "tb7a-u1-5",
  book: "七年级上册",
  unit: "Unit 1",
  title: "Homework 5: Developing ideas (写作与阅读)",
  subtitle: "单元写作 · 难忘的一课",
  source: "基础同步达标手册 七年级上（北京市三帆中学）",
  pages: "P19–P21",
  vocab: [
    { word: "lesson", phonetic: "ˈlesn", pos: "n.", meaning: "课；一节课", use: "one's first lesson 某人的第一节课" },
    { word: "unforgettable", phonetic: "ˌʌnfəˈɡetəbl", pos: "adj.", meaning: "难忘的", use: "An unforgettable lesson" },
    { word: "introduce", phonetic: "ˌɪntrəˈdjuːs", pos: "v.", meaning: "介绍", use: "introduce oneself 自我介绍" },
    { word: "nervous", phonetic: "ˈnɜːvəs", pos: "adj.", meaning: "紧张的", use: "I was very nervous before the lesson." },
    { word: "excited", phonetic: "ɪkˈsaɪtɪd", pos: "adj.", meaning: "兴奋的，激动的", use: "be excited about sth" },
    { word: "interested", phonetic: "ˈɪntrəstɪd", pos: "adj.", meaning: "感兴趣的", use: "be/become/get interested in ..." },
    { word: "term", phonetic: "tɜːm", pos: "n.", meaning: "学期", use: "three terms 三个学期" },
    { word: "rule", phonetic: "ruːl", pos: "n.", meaning: "规则", use: "strict rules 严格的规定" },
    { word: "last", phonetic: "lɑːst", pos: "v.", meaning: "持续", use: "Each term lasts about 10 weeks." },
    { word: "education", phonetic: "ˌedʒuˈkeɪʃn", pos: "n.", meaning: "教育", use: "receive free education 接受免费教育" },
  ],
  phrases: [
    { en: "have a lesson", zh: "上课", tip: "have an English lesson 上一节英语课" },
    { en: "one's first lesson", zh: "某人的第一节课", tip: "I'd like to introduce my first lesson." },
    { en: "ask sb to do sth", zh: "要求某人做某事", tip: "The teacher asks me to introduce myself." },
    { en: "introduce oneself", zh: "自我介绍", tip: "introduce oneself to the class" },
    { en: "ask sb a question", zh: "问某人一个问题", tip: "ask the teacher a question" },
    { en: "work out", zh: "计算出；想出", tip: "work out the answer 算出答案" },
    { en: "be/become/get interested in", zh: "对……感兴趣", tip: "get interested in maths" },
    { en: "look forward to", zh: "期待，盼望", tip: "look forward to 后接名词或动名词" },
    { en: "make a difference", zh: "产生影响，起作用", tip: "small acts of care can make a difference" },
  ],
  patterns: [
    { en: "I'd like to introduce an unforgettable lesson from my junior high school.", zh: "我想介绍一下我初中一节难忘的课。", note: "I'd like to do sth 我想做某事；开篇点题。" },
    { en: "It is my first maths lesson. It's an unforgettable lesson.", zh: "这是我的第一节数学课，一节令人难忘的课。", note: "第一段：点明主题（学科 + 难忘）。" },
    { en: "It's an unforgettable lesson because the teacher is so kind and the class is interesting.", zh: "这是一节难忘的课，因为老师很和蔼，课堂很有趣。", note: "because 引导原因状语从句。" },
    { en: "In the beginning of my first maths lesson, he asks us to introduce ourselves.", zh: "在我第一节数学课开始时，他让我们做自我介绍。", note: "ask sb to do sth；in the beginning of 在……开始时。" },
    { en: "Then he asks me a question. I feel nervous. My face turns red. After seeing me like that, he smiles at me.", zh: "然后他问我一个问题。我感到紧张，脸红了。看到我这样，他对我笑了。", note: "用一般过去时叙述经历，注意动词过去式。" },
    { en: "This is my first maths lesson. I love it so much because it makes me get interested in maths.", zh: "这是我的第一节数学课。我非常喜欢它，因为它让我对数学产生了兴趣。", note: "make sb do sth；get interested in。" },
    { en: "And I'm so lucky to have a teacher like him. I really look forward to my future colourful life at school.", zh: "我很幸运有这样一位老师。我真的很期待未来丰富多彩的学校生活。", note: "第三段：表达感受与期待。" },
  ],
  grammar: [
    {
      title: "一般过去时（写作主时态）",
      points: [
        "规则动词过去式加 -ed：ask → asked、introduce → introduced、smile → smiled、turn → turned。",
        "不规则动词要牢记：be → was/were、have → had、make → made、see → saw、begin → began、say → said、give → gave。",
        "否定句和疑问句用 did：I didn't know the answer. / Did the teacher help you?",
      ],
    },
    {
      title: "记叙文写作结构（三段式）",
      points: [
        "第一段：点明主题——学科 + 难忘（I'd like to introduce an unforgettable lesson ...）。",
        "第二段：写清“难忘”的原因——老师、课堂、你自己的表现（叙述顺序：开始时 → 然后 → 后来）。",
        "第三段：表达感受与期待（I love it so much ... / I look forward to ...）。",
      ],
    },
    {
      title: "写作常用词块与句型",
      points: [
        "have a lesson / one's first lesson / ask sb to do sth / introduce oneself。",
        "be/become/get interested in ...；make sb do sth；be lucky to do sth。",
        "写完后按“格式规范、结构清晰、要点齐全、人称时态、语言准确、语言丰富”六个维度自查。",
      ],
    },
  ],
  examPoints: [
    "写作前先审题：体裁（记叙文）、时态（一般过去时为主）、人称（第一、三人称为主）。",
    "题目三个提示问题都要回答：Which subject? Why unforgettable? How do you feel?",
    "要点齐全：①上课情况 ②任课老师 ③你的感受，缺一项就会被扣分。",
    "阅读加油站：run 运转、end 结束、rule 规则、term 学期、last 持续；last 在此作动词。",
    "匹配题先读选项抓关键词（hairstyles / Saturday / 10 years / two weeks），再回到对应国家定位。",
  ],
  sections: [
    {
      id: "words",
      title: "一、单元写作必备词汇（看中文写英文）",
      type: "dictation",
      items: [
        { q: "①上课", a: "have a lesson", note: "have lessons 上课，have an English lesson 上一节英语课" },
        { q: "②某人的第一节课", a: "one's first lesson", note: "one's 可用 my / his / her 等替换" },
        { q: "③要求某人做某事", a: "ask sb to do sth", note: "ask sb to do sth；ask sb for sth 向某人要某物" },
        { q: "④自我介绍", a: "introduce oneself", note: "introduce oneself to sb 向某人做自我介绍" },
        { q: "⑤问某人一个问题", a: "ask sb a question", note: "ask 后接双宾语：ask sb sth" },
        { q: "⑥计算出", a: "work out", note: "work out the answer 算出答案" },
        { q: "⑦对……感兴趣", a: "be/become/get interested in", accept: ["be interested in", "get interested in", "become interested in"], note: "in 是介词，后接名词或动名词" },
      ],
    },
    {
      id: "writing",
      title: "二、单元写作（An unforgettable lesson）",
      tip: "体裁：记叙文；时态：一般过去时为主；人称：第一人称和第三人称为主。写完后按 P20 评价表自评。",
      type: "translate",
      items: [
        {
          zh: "【写作任务】假设你是李华，请以 An unforgettable lesson 为题，给学校英文网站投稿：介绍你上初中某学科的第一次课是什么、为什么它令你难忘，以及你对这节课的感受。（提示词语：maths, helpful, nervous, smile, learn ... well, excited）",
          a: "An unforgettable lesson  I'd like to introduce an unforgettable lesson from my junior high school. It is my first maths lesson. It's an unforgettable lesson because the teacher is so kind and the class is interesting. Mr Wang is our maths teacher. In the beginning of my first maths lesson, he asks us to introduce ourselves. Then he asks me a question. I feel nervous and my face turns red. After seeing me like that, he smiles at me and says, “You can work it out. Just try your best.” With his help, I work out the answer. I am so excited that I learn it well. This is my first maths lesson. I love it so much because it makes me get interested in maths. And I'm so lucky to have a teacher like him. I really look forward to my future colourful life at school.",
          note: "范文按“点明主题 — 难忘原因 — 表达感受”三段展开；每段第一句都是主旨句。",
        },
        {
          zh: "【段落提纲】第一段：点明主题（学科 + 难忘）——I'd like to introduce an unforgettable lesson from my junior high school. It is my first ... lesson.",
          a: "I'd like to introduce an unforgettable lesson from my junior high school. It is my first English lesson.",
          note: "第一句话就要告诉读者：哪一科、为什么印象深刻。",
        },
        {
          zh: "【段落提纲】第二段：介绍本节课令人难忘的原因—— ... is our ... teacher. In the beginning of my first ... lesson, he asks us to introduce ... Then he asks me ... I feel ... My face turns ... After seeing me like that, he ...",
          a: "Ms Chen is our English teacher. In the beginning of my first English lesson, she asks us to introduce ourselves. Then she asks me a question. I feel nervous. My face turns red. After seeing me like that, she smiles at me and helps me answer it.",
          note: "写清老师做了什么、你有什么反应，用一般过去时。",
        },
        {
          zh: "【段落提纲】第三段：表达感受——This is my first ... lesson. I love it so much because it makes me get interested in ... And I'm so lucky to have a teacher like ... I really look forward to my future colourful life at school.",
          a: "This is my first English lesson. I love it so much because it makes me get interested in English. And I'm so lucky to have a teacher like her. I really look forward to my future colourful life at school.",
          note: "结尾表达感受与期待，与标题 unforgettable 呼应。",
        },
      ],
    },
    {
      id: "reading",
      title: "三、阅读加油站（School days around the world）",
      tip: "易读度 80.1，词数 252，建议用时 6 分钟。先读五个选项抓关键词，再回到对应国家定位。",
      type: "choice",
      passage: [
        "In China, the school year runs from September to mid-July. Students go to school five days a week. The school day usually starts at 7:30 or 8:00 am, and ends around 5:00 pm. Children over six receive free education (接受免费义务教育) at both primary school (grades 1 to 6) and junior secondary school (grades 7 to 9).",
        "In Japan, the school year starts in April and ends the following March. There are three terms, with holidays for summer, winter, and spring. There are strict rules for uniforms (校服), hairstyles, and more.",
        "In Russia, the school year starts on September 1st and ends in late May or early June. There are four terms with holidays in between. The school day is from 8:30 am to 3:00 pm. Students stay together in the same class from grades 1 to 10.",
        "Children in Italy must go to school from age 6 to 16. The school year usually starts in mid-September and ends in mid-June. Most schools have a school week from Monday to Friday, but many also have classes on Saturday. If a school runs for six days, their teaching hours may be from 8:00 am to 1:00 pm.",
        "In Australia, summer holidays run from late December to late January, and the new school year starts afterward (之后). There are four terms, and each term lasts about 10 weeks. Students have two weeks of holidays between each term. The school day is from 9:00 am to 3:30 pm.",
      ],
      items: [
        {
          q: "China （ ）",
          options: ["Strict rules about hairstyles", "Possible Saturday classes", "Free education for grades 1-9", "Same classmates for 10 years", "Two-week holidays between terms"],
          a: "C",
          explain: "中国部分提到 Children over six receive free education at both primary school (grades 1 to 6) and junior secondary school (grades 7 to 9)，对应 C。",
        },
        {
          q: "Japan （ ）",
          options: ["Strict rules about hairstyles", "Possible Saturday classes", "Free education for grades 1-9", "Same classmates for 10 years", "Two-week holidays between terms"],
          a: "A",
          explain: "日本部分提到 There are strict rules for uniforms, hairstyles, and more，对应 A。",
        },
        {
          q: "Russia （ ）",
          options: ["Strict rules about hairstyles", "Possible Saturday classes", "Free education for grades 1-9", "Same classmates for 10 years", "Two-week holidays between terms"],
          a: "D",
          explain: "俄罗斯部分提到 Students stay together in the same class from grades 1 to 10，对应 D。",
        },
        {
          q: "Italy （ ）",
          options: ["Strict rules about hairstyles", "Possible Saturday classes", "Free education for grades 1-9", "Same classmates for 10 years", "Two-week holidays between terms"],
          a: "B",
          explain: "意大利部分提到 many also have classes on Saturday，对应 B。",
        },
        {
          q: "Australia （ ）",
          options: ["Strict rules about hairstyles", "Possible Saturday classes", "Free education for grades 1-9", "Same classmates for 10 years", "Two-week holidays between terms"],
          a: "E",
          explain: "澳大利亚部分提到 Students have two weeks of holidays between each term，对应 E。",
        },
      ],
    },
  ],
};
