// 七年级上册 Unit 2 Homework 1: Starting out + Understanding ideas (1)
export default {
  id: "tb7a-u2-1",
  book: "七年级上册",
  unit: "Unit 2",
  title: "Homework 1: Starting out + Understanding ideas (1)",
  subtitle: "摇滚与二胡 · 音乐爱好",
  source: "基础同步达标手册 七年级上（北京市三帆中学）",
  pages: "P22–P23",
  vocab: [
    { word: "rock music", phonetic: "rɒk ˈmjuːzɪk", pos: "词组", meaning: "摇滚乐", use: "Rock music is coming out of my computer." },
    { word: "electric", phonetic: "ɪˈlektrɪk", pos: "adj.", meaning: "用电的；电动的", use: "play the electric guitar 弹电吉他" },
    { word: "guitar", phonetic: "ɡɪˈtɑː(r)", pos: "n.", meaning: "吉他", use: "play the guitar 弹吉他" },
    { word: "band", phonetic: "bænd", pos: "n.", meaning: "乐队", use: "in the school band 在学校乐队" },
    { word: "sound", phonetic: "saʊnd", pos: "n.", meaning: "声音", use: "the sound of Grandpa's erhu" },
    { word: "different", phonetic: "ˈdɪfrənt", pos: "adj.", meaning: "不同的；不一样的", use: "a different kind of music" },
    { word: "suddenly", phonetic: "ˈsʌdənli", pos: "adv.", meaning: "突然；突如其来地", use: "An idea suddenly hits me." },
    { word: "hit", phonetic: "hɪt", pos: "v.", meaning: "使（某人）突然意识到；击，打", use: "An idea hits me. 我忽然想到一个主意。" },
    { word: "rush", phonetic: "rʌʃ", pos: "v.", meaning: "冲，奔", use: "rush into his room 冲进他的房间" },
    { word: "festival", phonetic: "ˈfestəvəl", pos: "n.", meaning: "（电影、戏剧、音乐等的）节，节日，汇演", use: "an art festival 艺术节" },
    { word: "decide", phonetic: "dɪˈsaɪd", pos: "v.", meaning: "决定", use: "decide to do sth 决定做某事" },
    { word: "practice", phonetic: "ˈpræktɪs", pos: "n.", meaning: "练习", use: "After a week's practice ..." },
    { word: "stage", phonetic: "steɪdʒ", pos: "n.", meaning: "舞台", use: "on the stage 在舞台上" },
    { word: "nod", phonetic: "nɒd", pos: "v.", meaning: "点头", use: "I nod to Grandpa." },
    { word: "instrument", phonetic: "ˈɪnstrəmənt", pos: "n.", meaning: "乐器；仪器", use: "fire up our instruments 让我们的乐器嗨起来" },
    { word: "everybody", phonetic: "ˈevribɒdi", pos: "pron.", meaning: "每个人，人人", use: "Everybody moves with our music." },
    { word: "smile", phonetic: "smaɪl", pos: "n. & v.", meaning: "笑容；微笑", use: "give me a big smile 给我一个大大的笑容" },
    { word: "enjoy", phonetic: "ɪnˈdʒɔɪ", pos: "v.", meaning: "喜欢；享受……的乐趣", use: "enjoy our hobby together" },
  ],
  phrases: [
    { en: "rock music", zh: "摇滚乐", tip: "Rock music is coming out of my computer." },
    { en: "come out of", zh: "从……中出来；（声音）传出", tip: "come out of my computer" },
    { en: "cut in", zh: "插话；突然切入", tip: "the sound of Grandpa's erhu cuts in" },
    { en: "put ... together", zh: "把……合在一起", tip: "Why don't we put our music together?" },
    { en: "take part in", zh: "参加，参与", tip: "decide to take part in it with Grandpa" },
    { en: "at this moment", zh: "就在此时", tip: "Right at this moment ..." },
    { en: "have fun", zh: "玩得开心", tip: "There is so much fun in music." },
    { en: "on the stage", zh: "在舞台上", tip: "After a week's practice, we are on the stage." },
    { en: "smile back", zh: "回以微笑", tip: "Grandpa gives me a big smile, and I smile back." },
  ],
  patterns: [
    { en: "Rock music is coming out of my computer.", zh: "摇滚乐正从我的电脑里传出来。", note: "现在进行时表示正在发生；come out of 从……中传出。" },
    { en: "As a rock music lover, I play the electric guitar in the school band.", zh: "作为一名摇滚乐爱好者，我在学校乐队里弹电吉他。", note: "as 作介词表示“作为”；play + the + 乐器。" },
    { en: "Right at this moment, the sound of Grandpa's erhu cuts in.", zh: "就在这时，爷爷的二胡声插了进来。", note: "right at this moment 就在此刻，用于时间转换。" },
    { en: "An idea suddenly hits me: Why don't we put our music together?", zh: "我忽然想到一个主意：我们为什么不把我们的音乐合在一起呢？", note: "an idea hits sb 某人忽然想到一个主意；Why don't we do sth? 提出建议。" },
    { en: "After a week's practice, we are on the stage.", zh: "经过一周的练习，我们登上了舞台。", note: "a week's practice 一周的练习（名词所有格）。" },
    { en: "I nod to Grandpa and we fire up our instruments.", zh: "我向爷爷点头，然后我们让乐器嗨起来。", note: "nod to sb 向某人点头；fire up 使兴奋起来。" },
    { en: "It feels great to enjoy our hobby together.", zh: "一起享受我们的爱好感觉真好。", note: "It feels great to do sth；it 作形式主语。" },
  ],
  grammar: [
    {
      title: "play 与乐器、球类",
      points: [
        "乐器前加 the：play the electric guitar / play the erhu / play the piano。",
        "球类前不加冠词：play basketball / play football / play chess。",
        "at + the + 乐器也可表示“演奏”：play the erhu in the park。",
      ],
    },
    {
      title: "一般现在时（三单形式）",
      points: [
        "一般情况加 -s：likes / plays / hits；以 s, x, ch, sh, o 结尾加 -es：goes / does / watches。",
        "辅音字母 + y 结尾变 y 为 i 再加 -es：study → studies。",
        "特殊变化：have → has；be 动词：am / is / are。",
      ],
    },
    {
      title: "提建议与征求意见的句型",
      points: [
        "Why don't we do sth? 我们为什么不……呢？（提出建议）",
        "Shall I do sth? 我……好吗？（征求对方意见）",
        "Why not do sth? 为什么不做某事呢？（后接动词原形）",
      ],
    },
  ],
  examPoints: [
    "an idea hits sb 某人忽然想到一个主意；hit 的过去式仍是 hit。",
    "decide to do sth 决定做某事；take part in 参加（活动、比赛）。",
    "After a week's practice 中 practice 是不可数名词，不加 s。",
    "How + 形容词 + it is! 感叹句：How interesting it is!",
    "there be 句型就近原则：there are lots of online friends ...（lots of + 复数用 are）。",
  ],
  sections: [
    {
      id: "words",
      title: "一、单词巩固（看音标和中文写单词）",
      type: "dictation",
      items: [
        { q: "[rɒk ˈmjuːzɪk]（词组）摇滚乐", a: "rock music", note: "摇滚乐；rock 还可作动词，意为“摇摆”" },
        { q: "[ɪˈlektrɪk] adj. 用电的；电动的", a: "electric", note: "electric guitar 电吉他" },
        { q: "[ɡɪˈtɑː(r)] n. 吉他", a: "guitar", note: "play the guitar 弹吉他" },
        { q: "[bænd] n. 乐队", a: "band", note: "in the school band 在学校乐队" },
        { q: "[saʊnd] n. 声音", a: "sound", note: "the sound of music 音乐声" },
        { q: "[ˈdɪfrənt] adj. 不同的；不一样的", a: "different", note: "be different from 与……不同" },
        { q: "[ˈsʌdənli] adv. 突然；突如其来地", a: "suddenly", note: "常置于句首：Suddenly an idea hits me." },
        { q: "[hɪt] v. 使（某人）突然意识到", a: "hit", note: "an idea hits sb 某人忽然想到一个主意" },
        { q: "[rʌʃ] v. 冲，奔", a: "rush", note: "rush into 冲进" },
        { q: "[ˈfestəvəl] n.（电影、戏剧、音乐等的）节，节日，汇演", a: "festival", note: "the art festival 艺术节" },
        { q: "[dɪˈsaɪd] v. 决定", a: "decide", note: "decide to do sth 决定做某事" },
        { q: "[ˈpræktɪs] n. 练习", a: "practice", note: "不可数名词；practise 是动词" },
        { q: "[steɪdʒ] n. 舞台", a: "stage", note: "on the stage 在舞台上" },
        { q: "[nɒd] v. 点头", a: "nod", note: "nod to sb 向某人点头" },
        { q: "[ˈɪnstrəmənt] n. 乐器", a: "instrument", note: "fire up our instruments 让我们的乐器嗨起来" },
        { q: "[ˈevribɒdi] pron. 每个人，人人", a: "everybody", note: "作主语时谓语用单数" },
        { q: "[smaɪl] n. 笑容 v. 微笑", a: "smile", note: "smile at sb 对某人微笑" },
        { q: "[ɪnˈdʒɔɪ] v. 喜欢；享受……的乐趣", a: "enjoy", note: "enjoy doing sth 喜欢做某事" },
      ],
    },
    {
      id: "phrases",
      title: "二、词组过关（按提示补全句子）",
      type: "fill",
      items: [
        { q: "Rock music is ____ ____ ____（正从……中出来）my computer.", a: "coming out of", zh: "摇滚乐正从我的电脑里传出来。", note: "come out of 从……中出来，传出。" },
        { q: "I ____ ____（决定做某事）take part in it with grandpa this year.", a: "decide to", zh: "我决定今年和爷爷一起参加。", note: "decide to do sth 决定做某事。" },
        { q: "After ____ ____ ____（一周的练习）, we are on the stage.", a: "a week's practice", accept: ["a week of practice"], zh: "经过一周的练习，我们登上了舞台。", note: "名词所有格 a week's practice。" },
        { q: "____ ____ ____（为什么不……?）put our music together?", a: "Why don't we", zh: "我们为什么不把音乐合在一起呢？", note: "Why don't we do sth? 提出建议。" },
        { q: "“Grandpa!” I ____ ____ ____ ____（冲进他的房间）.", a: "rush into his room", zh: "“爷爷！”我冲进他的房间。", note: "rush into 冲进。" },
      ],
    },
    {
      id: "wordform",
      title: "三、根据句意、音标、首字母或汉语提示写单词",
      type: "fill",
      items: [
        { q: "School art f____ is coming next week.", a: "festival", zh: "学校艺术节下周就要到了。", note: "art festival 艺术节。" },
        { q: "She ____（点头）to me and says “yes”.", a: "nods", zh: "她向我点点头说“好的”。", note: "主语 she 是第三人称单数，用 nods。" },
        { q: "His ____ [smaɪl] makes everyone happy.", a: "smile", zh: "他的笑容让大家都很开心。", note: "smile 在此作名词，作主语。" },
        { q: "The erhu is a traditional Chinese ____（乐器）.", a: "instrument", zh: "二胡是一种中国传统乐器。", note: "traditional Chinese instrument。" },
        { q: "They will ____（享受）the music show.", a: "enjoy", zh: "他们会享受这场音乐演出。", note: "will + 动词原形。" },
      ],
    },
    {
      id: "choice",
      title: "四、单项选择",
      type: "choice",
      items: [
        {
          q: "I play ____ electric guitar in the school band.",
          options: ["a", "an", "the", "/"],
          a: "C",
          explain: "演奏乐器时，乐器前要加定冠词 the：play the electric guitar。",
        },
        {
          q: "We should ____ to protect the old trees in the park.",
          options: ["take part in", "take place", "take action", "take off"],
          a: "C",
          explain: "take action 采取行动；take part in 参加；take place 发生；take off 起飞、脱下。",
        },
        {
          q: "— I don't like water or tea. ____ I order some coffee?\n— Sure.",
          options: ["Must", "Should", "Shall", "Need"],
          a: "C",
          explain: "Shall I ...? 用于征求对方意见，表示“我……好吗？”，答语用 Sure。",
        },
        {
          q: "— ____ are you feeling about the coming performance?\n— Nervous but excited.",
          options: ["What", "Where", "How", "When"],
          a: "C",
          explain: "How are you feeling about ...? 询问“你觉得……怎么样？”，答语是形容词。",
        },
        {
          q: "Many students don't like traditional music, but I am ____ them. I love erhu music.",
          options: ["the same as", "different from", "interested", "good at"],
          a: "B",
          explain: "but 表示转折，说明“我与他们不同”，用 be different from。",
        },
      ],
    },
    {
      id: "cloze",
      title: "五、语法填空（填入适当的词或括号中所给单词的正确形式）",
      type: "cloze",
      passage: [
        "My grandpa loves playing chess. Every day he plays chess with his {{1}} (friend). Last week, he came to visit us. But he was very sad {{2}} nobody here could play chess with him.",
        "One day, when I came back {{3}} school, my grandpa was sitting quietly in a chair, doing nothing. {{4}} (sudden), an idea hit me. Why not teach him {{5}} (play) online chess on my computer? Then I took him to the computer in my room and taught him how to use {{6}} Internet. At first, he was slow. Then, he became much {{7}} (good) than before. Now he is quite good at playing chess online and there {{8}} (be) lots of online friends playing with him.",
        "“How {{9}} (interest) it is!” he told us. He enjoyed himself when he was playing online chess on my computer. The Internet brought {{10}} (he) a lot. But every coin has two sides. It's not good for him to play too long, so we often advise him to use it properly.",
      ],
      blanks: [
        { n: 1, a: "friends", hint: "friend", explain: "和爷爷下棋的“朋友们”不止一个，用复数 friends。" },
        { n: 2, a: "because", hint: "无提示", explain: "后面说明“伤心的原因”，用连词 because。" },
        { n: 3, a: "from", hint: "无提示", explain: "come back from school 从学校回来。" },
        { n: 4, a: "Suddenly", hint: "sudden", explain: "修饰整个句子用副词，句首首字母大写 Suddenly。" },
        { n: 5, a: "to play", hint: "play", explain: "teach sb to do sth 教某人做某事。" },
        { n: 6, a: "the", hint: "无提示", explain: "the Internet 互联网，固定搭配。" },
        { n: 7, a: "better", hint: "good", explain: "than 前用比较级，good 的比较级是 better。" },
        { n: 8, a: "are", hint: "be", explain: "there be 就近原则，lots of online friends 是复数，用 are。" },
        { n: 9, a: "interesting", hint: "interest", explain: "How + 形容词 + it is! 感叹句，修饰事物用 interesting。" },
        { n: 10, a: "him", hint: "he", explain: "brought 后接双宾语，人称代词用宾格 him。" },
      ],
    },
    {
      id: "translate",
      title: "六、根据中文意思和英文提示词语写出句子",
      type: "translate",
      items: [
        { zh: "我在学校乐队弹吉他。(guitar; band)", a: "I play the guitar in the school band.", note: "乐器前加 the；in the school band 在学校乐队。" },
        { zh: "你想去参加艺术节吗？(take part in)", a: "Do you want to take part in the art festival?", note: "take part in 参加（活动）。" },
        { zh: "和朋友一起玩感觉很好。(feel)", a: "It feels good to play with friends.", note: "It feels + adj. + to do sth，it 作形式主语。" },
        { zh: "我突然想到一个主意：我可以去公园。(hit)", a: "An idea suddenly hits me: I can go to the park.", note: "an idea hits sb 某人忽然想到一个主意。" },
        { zh: "她在舞台上唱歌。(stage)", a: "She sings on the stage.", note: "on the stage 在舞台上。" },
      ],
    },
  ],
};
