// 七年级上册 Unit 2 Homework 2: Understanding ideas (2)
export default {
  id: "tb7a-u2-2",
  book: "七年级上册",
  unit: "Unit 2",
  title: "Homework 2: Understanding ideas (2)",
  subtitle: "一般现在时专项 · 爱好与传统艺术",
  source: "基础同步达标手册 七年级上（北京市三帆中学）",
  pages: "P24–P27",
  vocab: [
    { word: "skate", phonetic: "skeɪt", pos: "v.", meaning: "滑冰，溜冰", use: "go skating 去滑冰" },
    { word: "club", phonetic: "klʌb", pos: "n.", meaning: "俱乐部；社团", use: "a music club 音乐社团" },
    { word: "volleyball", phonetic: "ˈvɒlibɔːl", pos: "n.", meaning: "排球（运动）", use: "play volleyball 打排球" },
    { word: "traditional", phonetic: "trəˈdɪʃənəl", pos: "adj.", meaning: "传统的；习俗的；惯例的", use: "traditional Chinese art" },
    { word: "paper-cutting", phonetic: "ˈpeɪpə(r) ˈkʌtɪŋ", pos: "词组", meaning: "剪纸", use: "enjoy paper-cutting 喜欢剪纸" },
    { word: "Beijing opera", phonetic: "ˌbeɪdʒɪŋ ˈɒprə", pos: "词组", meaning: "京剧", use: "sing Beijing opera 唱京剧" },
    { word: "competition", phonetic: "ˌkɒmpəˈtɪʃn", pos: "n.", meaning: "比赛，竞赛", use: "take part in the competition" },
    { word: "fan", phonetic: "fæn", pos: "n.", meaning: "迷，爱好者", use: "a Beijing opera fan 京剧迷" },
  ],
  phrases: [
    { en: "have fun", zh: "玩得开心", tip: "There is so much fun in music." },
    { en: "write about", zh: "写关于……的内容", tip: "write about the feeling 写关于感受的内容" },
    { en: "an idea hits sb", zh: "某人忽然想到一个主意", tip: "An idea suddenly hits me." },
    { en: "right at this moment", zh: "就在此时", tip: "用于由一件事转到另一件事。" },
    { en: "an art festival", zh: "一个艺术节", tip: "There is an art festival every autumn." },
    { en: "enjoy oneself", zh: "玩得开心", tip: "He enjoyed himself when he was playing online chess." },
    { en: "every Monday", zh: "每周一", tip: "every + 单数名词，表示频率。" },
  ],
  patterns: [
    { en: "Now I am in my room.", zh: "现在我在我的房间里。", note: "be 动词：I 用 am。" },
    { en: "Our school is beautiful. / The man is from Nanjing.", zh: "我们的学校很美。/ 那个人来自南京。", note: "第三人称单数用 is。" },
    { en: "The children are in the classroom.", zh: "孩子们在教室里。", note: "复数主语用 are。" },
    { en: "My sister likes swimming. They want to go to the museum.", zh: "我姐姐喜欢游泳。他们想去博物馆。", note: "主语为第三人称单数时行为动词加 -s/-es。" },
    { en: "It feels great to enjoy our hobby together.", zh: "一起享受我们的爱好感觉真好。", note: "It feels + adj. + to do sth。" },
  ],
  grammar: [
    {
      title: "一般现在时（be 动词）",
      points: [
        "am 只用于 I：I am a student.",
        "is 用于第三人称单数（he / she / it / the man / our school）：Our school is beautiful.",
        "are 用于第二人称和复数：You are right. / The children are in the classroom.",
        "否定句在 be 后加 not（is not = isn t）；一般疑问句把 be 提到句首，回答用 Yes, 主语 + be. / No, 主语 + be + not.",
      ],
    },
    {
      title: "一般现在时（行为动词）",
      points: [
        "主语为一、二人称或复数时，用动词原形：They want to go to the museum.",
        "主语为第三人称单数时用单三形式：一般加 -s（likes / plays）；以 s, x, ch, sh, o 结尾加 -es（goes / watches）；辅音字母 + y 变 y 为 i 加 -es（study → studies）。",
        "特殊变化：have → has；do → does；go → goes。",
        "否定句用 don t / doesn t + 动词原形；疑问句用 Do / Does + 主语 + 动词原形。",
      ],
    },
    {
      title: "特殊疑问句（对主语与对非主语提问）",
      points: [
        "对主语提问：Who wants to go to the zoo?（疑问词直接作主语，后面用陈述语序）",
        "对非主语提问：How does he go to work every day? / When do you have maths?（疑问词 + do/does + 主语 + 动词原形）",
        "be 动词的特殊疑问句：Where are your books? / How is your grandfather?",
      ],
    },
  ],
  examPoints: [
    "often / every day / every Monday 等频率标志词提示用一般现在时。",
    "The sun rises in the east. 客观真理用一般现在时。",
    "否定与疑问要用助动词：We don t watch TV on Monday. / Does your sister often sing English songs?",
    "be 动词与行为动词不能同时作谓语：She walks to the park.（不用 is walk）",
    "翻译题注意固定搭配：take part in（参加）、a history of a thousand years（千年历史）。",
  ],
  sections: [
    {
      id: "words",
      title: "一、单词巩固（看音标和中文写单词）",
      type: "dictation",
      items: [
        { q: "[skeɪt] v. 滑冰，溜冰", a: "skate", note: "go skating 去滑冰" },
        { q: "[klʌb] n. 俱乐部", a: "club", note: "join the club 加入俱乐部" },
        { q: "[ˈvɒlibɔːl] n. 排球（运动）", a: "volleyball", note: "play volleyball 打排球" },
        { q: "[trəˈdɪʃənəl] adj. 传统的；习俗的；惯例的", a: "traditional", note: "traditional Chinese art 中国传统艺术" },
        { q: "[ˈpeɪpə(r) ˈkʌtɪŋ]（词组）剪纸", a: "paper-cutting", note: "enjoy paper-cutting 喜欢剪纸" },
      ],
    },
    {
      id: "phrases",
      title: "二、词组过关（按提示补全句子）",
      type: "fill",
      items: [
        { q: "Grandpa and I put our music together and ____ ____（玩得开心）.", a: "have fun", zh: "爷爷和我把音乐合在一起，玩得很开心。", note: "have fun 玩得开心。" },
        { q: "Sometimes, the writer does not ____ ____（写……的故事）the feeling directly.", a: "write about", zh: "有时作者不直接写这种感受。", note: "write about 写关于……的内容。" },
        { q: "____ ____ ____ ____ ____（我突然想到了一个想法）: “why don't we put our music together?”", a: "An idea suddenly hits me", accept: ["Suddenly an idea hits me"], zh: "我突然想到一个主意：“为什么不把我们的音乐合在一起？”", note: "an idea hits sb 某人忽然想到一个主意。" },
        { q: "____ ____ ____ ____（就在这时）the sound of grandpa's erhu cuts in.", a: "Right at this moment", zh: "就在这时，爷爷的二胡声插了进来。", note: "right at this moment 就在此刻。" },
        { q: "There is ____ ____ ____（一个艺术节）every autumn in my school.", a: "an art festival", zh: "我们学校每年秋天都有一个艺术节。", note: "art 以元音音素开头，用 an。" },
      ],
    },
    {
      id: "recap",
      title: "三、语法回顾（补全一般现在时知识）",
      type: "fill",
      items: [
        { q: "be 动词：Now I ____ in my room.", a: "am", zh: "现在我在我的房间里。", note: "I 用 am。" },
        { q: "Our school ____ beautiful. / The man ____ from Nanjing.", a: "is is", zh: "我们的学校很美。/ 那个人来自南京。", note: "两个空都填 is（第三人称单数）。" },
        { q: "The children ____ in the classroom.", a: "are", zh: "孩子们在教室里。", note: "复数主语用 are。" },
        { q: "肯定句：The girl ____ Lisa's sister.", a: "is", zh: "这个女孩是莉萨的姐姐。", note: "主语 The girl 是第三人称单数。" },
        { q: "否定句：The girl ____ ____ Lisa's sister.", a: "is not", accept: ["isn't"], zh: "这个女孩不是莉萨的姐姐。", note: "be 动词后加 not。" },
        { q: "一般疑问句：____ the girl Lisa's sister? Yes, she ____. / No, she ____.", a: "Is is isn't", zh: "这个女孩是莉萨的姐姐吗？", note: "把 be 提到句首；肯定回答用 is，否定回答用 isn't。" },
        { q: "特殊疑问句（对主语提问）：____（谁）is in the classroom?", a: "Who", zh: "谁在教室里？", note: "对主语提问用 Who。" },
        { q: "特殊疑问句（对主语提问）：____（如何）is your grandfather?", a: "How", zh: "你爷爷身体怎么样？", note: "How is ...? 询问身体状况。" },
        { q: "特殊疑问句（对非主语提问）：____（什么地方）are your books?", a: "Where", zh: "你的书在哪里？", note: "对地点提问用 Where。" },
        { q: "行为动词：My sister ____ (like) swimming.", a: "likes", zh: "我姐姐喜欢游泳。", note: "第三人称单数加 -s。" },
        { q: "行为动词：They ____ (want) to go to the museum.", a: "want", zh: "他们想去博物馆。", note: "主语是复数，用动词原形。" },
        { q: "行为动词特殊变化：have → ____；go → ____；do → ____", a: "has goes does", zh: "三单特殊变化。", note: "have / go / do 的第三人称单数形式。" },
        { q: "肯定句：The animal ____ (eat) tree leaves.", a: "eats", zh: "这种动物吃树叶。", note: "主语为第三人称单数，用 eats。" },
        { q: "否定句：The animal ____ (not eat) eat tree leaves.", a: "doesn't", accept: ["does not"], zh: "这种动物不吃树叶。", note: "doesn't + 动词原形。" },
        { q: "一般疑问句：____ the animal eat tree leaves? Yes, it ____. / No, it ____.", a: "Does does doesn't", zh: "这种动物吃树叶吗？", note: "Does + 主语 + 动词原形。" },
        { q: "特殊疑问句（对主语提问）：____（谁）wants to go to the zoo?", a: "Who", zh: "谁想去动物园？", note: "对主语提问用 Who，后面动词仍用单三形式。" },
        { q: "特殊疑问句（对非主语提问）：____（如何）does he go to work every day?", a: "How", zh: "他每天怎样去上班？", note: "对方式提问用 How。" },
        { q: "特殊疑问句（对非主语提问）：____（什么时候）do you have math?", a: "When", zh: "你什么时候上数学课？", note: "对时间提问用 When。" },
      ],
    },
    {
      id: "choice",
      title: "四、单项选择",
      type: "choice",
      items: [
        { q: "She ____ to the park every morning.", options: ["walk", "walks", "walking", "is walking"], a: "B", explain: "every morning 提示一般现在时，主语 She 是第三人称单数，用 walks。" },
        { q: "____ your sister often ____ English songs?", options: ["Do; sing", "Does; sing", "Do; sings", "Does; sings"], a: "B", explain: "主语 your sister 是第三人称单数，助动词用 Does，后面动词用原形 sing。" },
        { q: "— Where ____ your uncle work?\n— In a factory.", options: ["do", "does", "is", "are"], a: "B", explain: "work 是行为动词，主语 your uncle 是第三人称单数，用 does。" },
        { q: "— ____ they glad about the trip?\n— Yes, they ____.", options: ["Are; are", "Do; do", "Is; is", "Does; does"], a: "A", explain: "glad 是形容词，用 be 动词；主语 they 是复数，用 are。" },
        { q: "The sun ____ in the east.", options: ["rise", "rises", "rising", "is rising"], a: "B", explain: "客观真理用一般现在时；主语 The sun 是第三人称单数，用 rises。" },
      ],
    },
    {
      id: "formfill",
      title: "五、用所给词的适当形式填空",
      type: "fill",
      items: [
        { q: "We often ____ (play) in the playground.", a: "play", zh: "我们经常在操场上玩。", note: "主语 We 用动词原形。" },
        { q: "Alice often ____ (get) up at six o'clock.", a: "gets", zh: "艾丽斯经常六点起床。", note: "主语 Alice 是第三人称单数，用 gets。" },
        { q: "Daniel and Tommy ____ (be) in Class One.", a: "are", zh: "丹尼尔和汤米在一班。", note: "主语是两个人，用 are。" },
        { q: "We ____ ____ (not watch) TV on Monday.", a: "don't watch", accept: ["do not watch"], zh: "我们周一不看电视。", note: "主语 We，否定用 don t + 动词原形。" },
        { q: "Nick ____ ____ (not go) to the zoo on Sunday.", a: "doesn't go", accept: ["does not go"], zh: "尼克周日不去动物园。", note: "主语 Nick 是第三人称单数，否定用 doesn t + 动词原形。" },
      ],
    },
    {
      id: "translate",
      title: "六、根据中文意思和英文提示词语写出句子",
      type: "translate",
      items: [
        { zh: "我的爷爷是京剧迷。(Beijing opera; fan)", a: "My grandpa is a Beijing opera fan.", note: "a ... fan 一个……迷。" },
        { zh: "这门传统艺术有千年历史。(art; thousand)", a: "This traditional art has a history of a thousand years.", accept: ["This traditional art is a thousand years old."], note: "a history of ... 有……的历史。" },
        { zh: "我们想参加京剧比赛。(competition)", a: "We want to take part in the Beijing opera competition.", note: "take part in 参加；want to do sth。" },
        { zh: "学生们每周一起读书。(every week)", a: "Students read together every week.", note: "every week 每周，用一般现在时。" },
        { zh: "她每周一打扫教室。(every Monday)", a: "She cleans the classroom every Monday.", note: "主语 She 是第三人称单数，用 cleans。" },
      ],
    },
    {
      id: "reading",
      title: "七、阅读加油站（Brian's hobby：阅读短文，选择最佳答案）",
      tip: "易读度 84.7，词数 256，建议用时 5 分钟。第 2 题是情感态度题，注意文中表示感受的词汇。",
      type: "choice",
      passage: [
        "Brian's hobby",
        "Hi, I'm Brian, a 12-year-old student. When people ask about my hobby, my answer is always the same: playing the guitar. It's my favourite instrument (乐器).",
        "My love for music started six years ago. I loved the sounds around me and often tried to copy them by tapping on (轻拍) things. Then I began making melodies (旋律) by hitting my desks, chairs, and even pots (锅), and I found I was really good at it!",
        "A big change came when I was 9. My aunt visited from Florida and gave me a guitar for my birthday! I practised a lot and slowly learned how to play the strings (弦). I was so excited when I could play the first song — See You Again. My friends all loved it, and playing it for them made me feel great.",
        "That first success made me want to learn more songs. Now I can play over ten! Even if I've got small cuts on my fingers (手指) from the strings many times, I don't think about giving up. Playing the guitar has taught me a very important lesson: practice makes perfect.",
        "Playing the guitar also gives me a break from thinking too much about the outside world. When I feel sad, I just pick it up. As I play, all the bad feelings go away. I believe it's the amazing power (力量) of music. My hope for the future is to learn more beautiful songs and play them for my family and friends.",
      ],
      items: [
        { q: "What first showed Brian's interest in music?", options: ["Singing difficult songs.", "Playing his aunt's guitar.", "Copying sounds around him.", "Listening to the radio all day."], a: "C", explain: "第二段提到 I loved the sounds around me and often tried to copy them by tapping on things，说明最早体现兴趣的是模仿身边的声音。" },
        { q: "How did Brian feel after he played his first song for his friends?", options: ["Sad.", "Worried.", "Happy.", "Surprised."], a: "C", explain: "playing it for them made me feel great 表示他感觉很好，因此是 happy。" },
        { q: "What happened after Brian's first success?", options: ["He practised even harder.", "He stopped learning new songs.", "He became famous in his school.", "He got a new guitar from his aunt."], a: "A", explain: "第四段说 That first success made me want to learn more songs. Now I can play over ten!，说明他更努力地练习。" },
        { q: "What do we know about Brian?", options: ["Playing the guitar helps him make money.", "He learned to play the guitar from his aunt.", "Playing the guitar is a good way for him to feel better.", "He can now play hundreds of songs in different styles."], a: "C", explain: "最后一段 When I feel sad, I just pick it up. As I play, all the bad feelings go away，说明弹吉他让他心情变好。" },
        { q: "Where might we find this text?", options: ["In a textbook about music.", "In a storybook about hobbies.", "In a guide book about the guitar.", "In a news report about musicians."], a: "B", explain: "文章以第一人称讲述自己的爱好故事，最可能出现在关于爱好的故事书中。" },
      ],
    },  ],
};
