// 七年级上册 Unit 2 Homework 3: Developing ideas (Listening and Speaking)
export default {
  id: "tb7a-u2-3",
  book: "七年级上册",
  unit: "Unit 2",
  title: "Homework 3: Developing ideas (Listening and Speaking)",
  subtitle: "观鸟爱好 · 语音辨析",
  source: "基础同步达标手册 七年级上（北京市三帆中学）",
  pages: "P28–P29",
  vocab: [
    { word: "hold", phonetic: "həʊld", pos: "v.", meaning: "握住，抓住；抱住", use: "hold the baby tightly 紧紧抱住孩子" },
    { word: "weak", phonetic: "wiːk", pos: "adj.", meaning: "虚弱的，不强壮的", use: "He is too weak to go to school." },
    { word: "nature", phonetic: "ˈneɪtʃə(r)", pos: "n.", meaning: "大自然，自然界", use: "learn more about nature" },
    { word: "ground", phonetic: "ɡraʊnd", pos: "n.", meaning: "地，地面", use: "sleep on the ground 睡在地上" },
    { word: "high", phonetic: "haɪ", pos: "adj.", meaning: "高的", use: "from a high place 从高处" },
    { word: "hobby", phonetic: "ˈhɒbi", pos: "n.", meaning: "业余爱好", use: "a special hobby 一个特别的爱好" },
    { word: "silly", phonetic: "ˈsɪli", pos: "adj.", meaning: "愚蠢的，傻的", use: "a silly hobby 一个傻傻的爱好" },
    { word: "indoors", phonetic: "ˌɪnˈdɔːz", pos: "adv.", meaning: "在室内", use: "play indoors 在室内玩" },
    { word: "list", phonetic: "lɪst", pos: "n.", meaning: "清单，名单", use: "keep a list of the birds" },
    { word: "score", phonetic: "skɔː(r)", pos: "n.", meaning: "分数", use: "get a high score 取得高分" },
  ],
  phrases: [
    { en: "take off", zh: "起飞；（飞机）起飞", tip: "take off from a high place" },
    { en: "fly away", zh: "飞走", tip: "The bird flew away." },
    { en: "at the weekend", zh: "在周末", tip: "go bird-watching at the weekend" },
    { en: "spend a lot of time outside", zh: "在户外花很多时间", tip: "spend time (in) doing sth" },
    { en: "keep a list of", zh: "记录……的清单", tip: "keep a list of all the birds" },
    { en: "the best time to do sth", zh: "做某事的最佳时间", tip: "It s the best time to see birds." },
    { en: "in the future", zh: "在将来", tip: "I hope I can see more birds in the future." },
  ],
  patterns: [
    { en: "There is a brown bird over there.", zh: "那边有一只棕色的小鸟。", note: "There be 句型表示“有”，就近一致。" },
    { en: "Could you tell us something about the bird last week?", zh: "你能告诉我们上周那种鸟的情况吗？", note: "Could you ...? 表示委婉请求，比 Can you ...? 更客气。" },
    { en: "They need to take off from a high place.", zh: "它们需要从高处起飞。", note: "need to do sth 需要做某事。" },
    { en: "It helps me learn more about nature.", zh: "它帮助我更多地了解大自然。", note: "help sb (to) do sth。" },
    { en: "Some of my friends think it s a silly hobby because they don t know what it s about.", zh: "我的一些朋友觉得这是个傻傻的爱好，因为他们不了解它。", note: "because 引导原因状语从句；what it s about 作 know 的宾语。" },
    { en: "It s the best time to see birds.", zh: "这是观鸟的最佳时间。", note: "the best time to do sth 做某事的最佳时间。" },
    { en: "I feel very excited! But there are still more to see.", zh: "我感觉非常兴奋！但还有更多（鸟）等着我去看。", note: "人感到兴奋用 excited，事物令人兴奋用 exciting。" },
  ],
  grammar: [
    {
      title: "like to do 与 like doing",
      points: [
        "两者常可互换：I like walking in the park. = I like to walk in the park.",
        "强调一贯的爱好多用 doing；强调某次具体动作多用 to do。",
        "同类结构：enjoy doing sth、spend time doing sth、thank you for doing sth。",
      ],
    },
    {
      title: "-ed 与 -ing 形容词",
      points: [
        "人感到……用 -ed：I feel very excited! / He is interested in birds.",
        "事物令人……用 -ing：It is an exciting hobby. / The film is interesting.",
      ],
    },
    {
      title: "常见字母组合的发音",
      points: [
        "ea 可以读 /iː/（leave, season, bean）或 /e/（ready, bread, weather）。",
        "ear 可以读 /ɜː/（early, learn）或 /ɪə/（near）。",
        "元音字母 i 读短音 /ɪ/（it, into, holiday, tradition）或字母本音 /aɪ/（wide, mine, like, inside）。",
        "词尾 y 常读 /i/（worry, very），但在单音节词中常读 /aɪ/（cry, my）。",
      ],
    },
    {
      title: "There be 句型",
      points: [
        "There is + 可数名词单数 / 不可数名词：There is a brown bird over there.",
        "There are + 可数名词复数：There are over 250 birds on it now.",
        "就近一致：There is a special bird or two. / There are two birds and a cat.",
      ],
    },
  ],
  examPoints: [
    "help sb (to) do sth：It helps me learn more about nature.。",
    "need to do sth：They need to take off from a high place.。",
    "much / very 修饰形容词：much better、very big；feel excited 不用 exciting。",
    "the best time to do sth 中要用不定式作定语。",
    "语音题先判断划线字母组合的读音，再逐项比对：leave → season；teacher → bean。",
  ],
  sections: [
    {
      id: "words",
      title: "一、单词巩固（看音标和中文写单词）",
      type: "dictation",
      items: [
        { q: "[həʊld] v. 握住，抓住；抱住", a: "hold", note: "hold sth tightly 紧紧握着某物" },
        { q: "[wiːk] adj. 虚弱的，不强壮的", a: "weak", note: "too weak to go to school 太虚弱不能上学" },
        { q: "[ˈneɪtʃə] n. 大自然，自然界", a: "nature", note: "learn about nature 了解大自然" },
        { q: "[ɡraʊnd] n. 地，地面", a: "ground", note: "on the ground 在地上" },
        { q: "[haɪ] adj. 高的", a: "high", note: "a high place 高处；a high score 高分" },
      ],
    },
    {
      id: "phrases",
      title: "二、词组过关（按提示补全句子）",
      type: "fill",
      items: [
        { q: "____ ____（那里有）a brown bird over there.", a: "There is", zh: "那边有一只棕色的小鸟。", note: "There be 句型，主语 a brown bird 是单数。" },
        { q: "The bird ____ ____（飞走了）.", a: "flew away", accept: ["flew off"], zh: "那只鸟飞走了。", note: "fly away 飞走，用一般过去时 flew。" },
        { q: "____ ____ ____ ____（你可以告诉我们）something about the bird last week?", a: "Could you tell us", zh: "你能告诉我们上周那种鸟的情况吗？", note: "tell sb sth 告诉某人某事。" },
        { q: "They ____（需要）to ____ ____（起飞）from a high place.", a: "need take off", zh: "它们需要从高处起飞。", note: "need to do sth；take off 起飞。" },
        { q: "It ____ ____ ____（帮我了解）more about nature.", a: "helps me learn", zh: "它帮助我更多地了解大自然。", note: "help sb (to) do sth 帮助某人做某事。" },
      ],
    },
    {
      id: "wordform",
      title: "三、根据句意、音标、首字母或汉语提示写单词",
      type: "fill",
      items: [
        { q: "I just want to enjoy myself in beautiful ____（大自然）.", a: "nature", zh: "我只想在大自然中好好享受。", note: "in nature 在大自然中。" },
        { q: "Jason is ill, and he can t go to school because he is too w____.", a: "weak", zh: "贾森病了，他不能去上学，因为他太虚弱了。", note: "too weak 太虚弱。" },
        { q: "The dog is sleeping on the ____ [ɡraʊnd].", a: "ground", zh: "那只狗睡在地上。", note: "on the ground 在地上。" },
        { q: "The weather is cold, so she h____ the baby tightly in her arms.", a: "holds", zh: "天气很冷，所以她把孩子紧紧抱在怀里。", note: "主语 she 是第三人称单数，用 holds。" },
        { q: "Miley gets a ____ [haɪ] score in her math test and she is happy.", a: "high", zh: "米莉数学测验得了高分，她很高兴。", note: "a high score 高分。" },
      ],
    },
    {
      id: "phonetics",
      title: "四、选出与划线部分发音相同的单词",
      tip: "先读准划线字母组合的读音，再逐一比较选项。",
      type: "choice",
      items: [
        { q: "leave（划线 ea）", options: ["great", "early", "season"], a: "C", explain: "leave 中的 ea 读 /iː/，season 中的 ea 也读 /iː/；great 读 /eɪ/，early 中的 ear 读 /ɜː/。" },
        { q: "teacher（划线 ea）", options: ["ready", "bean", "bread"], a: "B", explain: "teacher 中的 ea 读 /iː/，bean 中的 ea 也读 /iː/；ready 和 bread 中的 ea 读 /e/。" },
        { q: "it（划线 i）", options: ["into", "wide", "mine"], a: "A", explain: "it 中的 i 读短音 /ɪ/，into 中的 i 也读 /ɪ/；wide 和 mine 中的 i 读 /aɪ/。" },
        { q: "tradition（划线 i）", options: ["holiday", "like", "inside"], a: "A", explain: "tradition 中的 i 读短音 /ɪ/，holiday 中的 i 也读短音；like 和 inside 中的 i 读 /aɪ/。" },
        { q: "worry（划线 y）", options: ["very", "yes", "cry"], a: "A", explain: "worry 和 very 词尾的 y 都读 /i/；yes 中的 y 读 /j/，cry 中的 y 读 /aɪ/。" },
      ],
    },
    {
      id: "cloze",
      title: "五、语法填空（填入适当的词或括号中所给单词的正确形式）",
      type: "cloze",
      passage: [
        "I am a fifteen-year-old boy. I have {{1}} special hobby. It is bird-watching. Some of my friends think it s a silly hobby {{2}} they don t know what it s about. I love bird-watching, so I spend a lot of time outside. Many {{3}} (child) spend most of their time indoors playing their games. I also like doing that, but not all day. I like {{4}} (walk) in the park. Most of the time, there is a special {{5}} (bird) or two.",
        "I usually go bird-watching {{6}} the weekend for three or four hours in the afternoon. I sometimes get up {{7}} (real) early in the morning and go bird-watching for an hour before school. It s the best time {{8}} (see) birds. I keep a list (清单) of all the birds that I have seen. The number in this list is very {{9}} (big). There are over 250 birds on it now. I feel very {{10}} (exciting)! But there are still more to see, I hope I can see more birds in the future.",
      ],
      blanks: [
        { n: 1, a: "a", hint: "无提示", explain: "hobby 是可数名词单数，此处表示“一个”，用 a。" },
        { n: 2, a: "because", hint: "无提示", explain: "后面说明朋友觉得这个爱好傻的原因，用 because。" },
        { n: 3, a: "children", hint: "child", explain: "Many 后接可数名词复数，child 的复数是 children。" },
        { n: 4, a: "walking", hint: "walk", explain: "like doing sth 表示一贯的爱好，也可填 to walk。" },
        { n: 5, a: "bird", hint: "bird", explain: "a special bird or two 一两只有特别的鸟，用单数。" },
        { n: 6, a: "at", hint: "无提示", explain: "at the weekend 在周末（美式用 on the weekend，也可接受）。" },
        { n: 7, a: "really", hint: "real", explain: "修饰形容词 early 用副词 really。" },
        { n: 8, a: "to see", hint: "see", explain: "the best time to do sth 做某事的最佳时间。" },
        { n: 9, a: "big", hint: "big", explain: "be very big 很大，very 后接形容词原级。" },
        { n: 10, a: "excited", hint: "exciting", explain: "人感到兴奋用 -ed 形式的形容词 excited。" },
      ],
    },
    {
      id: "translate",
      title: "六、根据中文意思和英文提示词语写出句子",
      type: "translate",
      items: [
        { zh: "学生们想要去操场上玩。(want)", a: "Students want to play on the playground.", note: "want to do sth 想要做某事。" },
        { zh: "爱好能帮我们了解世界。(know)", a: "Hobbies can help us know the world.", note: "help sb (to) do sth。" },
        { zh: "这趟飞机将在大兴机场起飞。(Daxing Airport)", a: "The plane will take off at Daxing Airport.", note: "take off 起飞；具体地点前用 at。" },
        { zh: "现在越来越多的孩子们喜欢上了阅读。(love)", a: "Now more and more children love reading.", note: "more and more 越来越多；love doing sth。" },
        { zh: "你可以在这部电影中了解北京的历史。(get to do sth)", a: "You can get to know the history of Beijing in this film.", note: "get to do sth 有机会/逐渐做某事。" },
      ],
    },
  ],
};
