// 七年级上册 Unit 2 Homework 4: Developing ideas (Reading for writing 1)
export default {
  id: "tb7a-u2-4",
  book: "七年级上册",
  unit: "Unit 2",
  title: "Homework 4: Developing ideas (Reading for writing 1)",
  subtitle: "书架与笔记本 · 阅读之乐",
  source: "基础同步达标手册 七年级上（北京市三帆中学）",
  pages: "P30–P32",
  vocab: [
    { word: "notebook", phonetic: "ˈnəʊtbʊk", pos: "n.", meaning: "笔记本", use: "put the notebook on a shelf" },
    { word: "midnight", phonetic: "ˈmɪdnaɪt", pos: "n.", meaning: "午夜", use: "at midnight 在午夜" },
    { word: "heart", phonetic: "hɑːt", pos: "n.", meaning: "心（脏）", use: "be good for our heart 对我们的心脏有好处" },
    { word: "tap", phonetic: "tæp", pos: "v.", meaning: "（用手指）轻拍，轻叩，轻敲", use: "tap on the door 轻敲房门" },
    { word: "classmate", phonetic: "ˈklɑːsmeɪt", pos: "n.", meaning: "同班同学", use: "my new classmate 我的新同学" },
    { word: "magic", phonetic: "ˈmædʒɪk", pos: "adj. & n.", meaning: "有魔力的，神奇的；魔法", use: "a magic notebook 一本有魔力的笔记本" },
    { word: "shelf", phonetic: "ʃelf", pos: "n.", meaning: "搁板，架子", use: "on a shelf 在架子上（复数为 shelves）" },
    { word: "page", phonetic: "peɪdʒ", pos: "n.", meaning: "（书、报纸、文件等的）页，面", use: "turn to page 8 翻到第 8 页" },
    { word: "awake", phonetic: "əˈweɪk", pos: "adj.", meaning: "醒着的", use: "keep myself awake 让我保持清醒" },
    { word: "appear", phonetic: "əˈpɪə(r)", pos: "v.", meaning: "（尤指突然）出现，呈现", use: "The sun appears behind the clouds." },
    { word: "almost", phonetic: "ˈɔːlməʊst", pos: "adv.", meaning: "几乎，差不多", use: "almost twelve hours 将近十二个小时" },
    { word: "shake", phonetic: "ʃeɪk", pos: "v.", meaning: "摇动", use: "shake one s head 摇头" },
    { word: "lonely", phonetic: "ˈləʊnli", pos: "adj.", meaning: "孤单的，寂寞的", use: "feel lonely 感到孤单" },
    { word: "joy", phonetic: "dʒɔɪ", pos: "n.", meaning: "欢欣，愉快，喜悦", use: "share the joy of reading" },
    { word: "leave", phonetic: "liːv", pos: "v.", meaning: "离开", use: "leave the room 离开房间" },
    { word: "ending", phonetic: "ˈendɪŋ", pos: "n.", meaning: "（故事、电影、活动等的）结局，结尾", use: "the ending of the movie 电影的结局" },
  ],
  phrases: [
    { en: "go over", zh: "走过去；复习", tip: "He goes over and taps on the door." },
    { en: "tap on the door", zh: "轻敲房门", tip: "tap on 轻敲（表面）" },
    { en: "shake one s head", zh: "摇头", tip: "表示不同意或无奈" },
    { en: "stop doing sth", zh: "停止做某事", tip: "stop writing 停止写作" },
    { en: "look around", zh: "环视，四处看", tip: "look around the library 环视图书馆" },
    { en: "put sth on ...", zh: "把某物放在……上", tip: "put the notebook on a shelf" },
    { en: "How about doing sth?", zh: "做某事怎么样？", tip: "How about starting a writing group?" },
    { en: "keep sb awake", zh: "使某人保持清醒", tip: "keep myself awake 让我保持清醒" },
  ],
  patterns: [
    { en: "He goes over and taps on the door.", zh: "他走过去，轻敲房门。", note: "并列谓语用 and 连接。" },
    { en: "Emma shakes her head and stops writing.", zh: "艾玛摇了摇头，停止了写作。", note: "stop doing sth 停止做某事。" },
    { en: "She looks around the library.", zh: "她环视了一下图书馆。", note: "look around 环视。" },
    { en: "Emma puts the notebook on a shelf and leaves.", zh: "艾玛把笔记本放在架子上，然后离开了。", note: "put ... on ... 把……放在……上面；leave 离开。" },
    { en: "How about starting a writing group?", zh: "成立一个写作小组怎么样？", note: "How about + 动名词，用于提建议。" },
    { en: "Doing morning exercises is good for our heart.", zh: "做早操对我们的心脏有好处。", note: "动名词短语作主语，谓语用单数。" },
  ],
  grammar: [
    {
      title: "动名词作主语",
      points: [
        "Doing morning exercises is good for our heart.（谓语用单数 is）",
        "Shaking hands is a way to show that you are polite to others.",
        "常见搭配中的动名词：How about doing sth? / stop doing sth / enjoy doing sth。",
      ],
    },
    {
      title: "stop doing sth 与 stop to do sth",
      points: [
        "stop doing sth 停止正在做的事：She stops writing. 她停止写作。",
        "stop to do sth 停下来去做另一件事：She stops to look at the flowers. 她停下来去看花。",
      ],
    },
    {
      title: "名词复数的特殊变化",
      points: [
        "shelf → shelves；leaf → leaves；knife → knives（f / fe 变 v 加 -es）。",
        "child → children；foot → feet；tooth → teeth；man → men。",
        "page / notebook / ending 等一般直接加 -s：pages / notebooks / endings。",
      ],
    },
    {
      title: "一般现在时的三单变化（复习）",
      points: [
        "shake → shakes；appear → appears；tap → taps；leave → leaves。",
        "Kathy taps on the door and the teacher asks her to come in.",
      ],
    },
  ],
  examPoints: [
    "shelf 的复数是 shelves，做“买两个书架”的题时要变复数。",
    "enjoy 后接动名词：enjoy the ending 中的 ending 是名词，注意词形 end → ending。",
    "动名词作主语时谓语用单数：Shaking hands is a way ...。",
    "shake → shook（过去式）；leave → leaves（三单）。",
    "翻译时注意：make new friends 结交新朋友；share the joy of reading 分享阅读的快乐。",
  ],
  sections: [
    {
      id: "words",
      title: "一、单词巩固（看音标和中文写单词）",
      type: "dictation",
      items: [
        { q: "[ˈnəʊtbʊk] n. 笔记本", a: "notebook", note: "note + book 合成词" },
        { q: "[ˈmɪdnaɪt] n. 午夜", a: "midnight", note: "at midnight 在午夜" },
        { q: "[hɑːt] n. 心（脏）", a: "heart", note: "注意与 hear /hɪə/ 区分" },
        { q: "[tæp] v.（用手指）轻拍/叩/敲", a: "tap", note: "tap on the door 轻敲房门" },
        { q: "[ˈklɑːsmeɪt] n. 同班同学", a: "classmate", note: "class + mate" },
        { q: "[ˈmædʒɪk] adj. 有魔力的，神奇的", a: "magic", note: "a magic notebook 一本神奇的笔记本" },
        { q: "[ʃelf] n. 搁板，架子", a: "shelf", note: "复数 shelves" },
        { q: "[peɪdʒ] n.（书、报纸、文件等的）页，面", a: "page", note: "turn to page 8 翻到第 8 页" },
        { q: "[əˈweɪk] adj. 醒着的", a: "awake", note: "keep sb awake 使某人保持清醒" },
        { q: "[əˈpɪə] v.（尤指突然）出现，呈现", a: "appear", note: "反义词 disappear" },
        { q: "[ˈɔːlməʊst] adv. 几乎，差不多", a: "almost", note: "almost 12 hours 将近十二个小时" },
        { q: "[ʃeɪk] v. 摇动", a: "shake", note: "过去式 shook" },
        { q: "[ˈləʊnli] adj. 孤单的，寂寞的", a: "lonely", note: "feel lonely 感到孤单" },
        { q: "[dʒɔɪ] n. 欢欣，愉快，喜悦", a: "joy", note: "share the joy of reading" },
        { q: "[liːv] v. 离开", a: "leave", note: "三单 leaves" },
        { q: "[ˈendɪŋ] n.（故事、电影、活动等的）结局，结尾", a: "ending", note: "end（v. 结束）+ -ing" },
      ],
    },
    {
      id: "phrases",
      title: "二、词组过关（按提示补全句子）",
      type: "fill",
      items: [
        { q: "He ____ ____（走过去）and ____ ____（轻敲）the door.", a: "goes over taps on", zh: "他走过去，轻敲房门。", note: "go over 走过去；tap on the door 敲门。" },
        { q: "Emma ____ ____ ____（摇了摇头）and ____ ____（停止了写作）.", a: "shakes her head stops writing", zh: "艾玛摇了摇头，停止了写作。", note: "shake one s head 摇头；stop doing sth。" },
        { q: "She ____ ____（环视）the library.", a: "looks around", zh: "她环视了一下图书馆。", note: "look around 环视，四处看。" },
        { q: "Emma ____ the notebook ____（把某物放在……上）a shelf and leaves.", a: "puts on", zh: "艾玛把笔记本放在架子上，然后离开了。", note: "put sth on ... 把某物放在……上。" },
        { q: "____ ____（做某事怎么样）starting a writing group?", a: "How about", zh: "成立一个写作小组怎么样？", note: "How about + 动名词，用于提出建议。" },
      ],
    },
    {
      id: "wordform",
      title: "三、根据句意、音标、首字母或汉语提示写单词",
      type: "fill",
      items: [
        { q: "I always drink coffee to keep myself a____.", a: "awake", zh: "我总喝咖啡来让自己保持清醒。", note: "keep sb awake 使某人保持清醒。" },
        { q: "Doing morning exercises is good for our ____ [hɑːt].", a: "heart", zh: "做早操对我们的心脏有好处。", note: "be good for our heart。" },
        { q: "It takes ____（差不多）12 hours to travel from Beijing to London.", a: "almost", zh: "从北京到伦敦差不多要十二个小时。", note: "almost 几乎，差不多。" },
        { q: "When I arrive at the hotel, it is ____（午夜）.", a: "midnight", zh: "当我到达旅馆时，已是午夜。", note: "at midnight 在午夜。" },
        { q: "Don t forget to close the window when you ____ [liːv] the room.", a: "leave", zh: "你离开房间时别忘了关窗户。", note: "leave the room 离开房间。" },
      ],
    },
    {
      id: "formfill",
      title: "四、用所给词的适当形式填空",
      type: "fill",
      items: [
        { q: "I want to buy two ____ (shelf) to hold all my books.", a: "shelves", zh: "我想买两个书架来放我所有的书。", note: "two 后接复数，shelf → shelves。" },
        { q: "I really enjoy the ____ (end) of this movie.", a: "ending", zh: "我非常喜欢这部电影的结局。", note: "the + 名词，end → ending（结局）。" },
        { q: "____ (shake) hands is a way to show that you are polite to others.", a: "Shaking", zh: "握手是表示你对别人有礼貌的一种方式。", note: "动名词作主语，句首字母大写。" },
        { q: "The rain stops and the sun ____ (appear) behind the clouds.", a: "appears", zh: "雨停了，太阳出现在云层后面。", note: "主语 the sun 是第三人称单数。" },
        { q: "Kathy ____ (tap) on the door and the teacher asks her to come in.", a: "taps", zh: "凯茜轻轻敲门，老师让她进来。", note: "主语 Kathy 是第三人称单数。" },
      ],
    },
    {
      id: "translate",
      title: "五、根据中文意思和英文提示词语写出句子",
      type: "translate",
      items: [
        { zh: "她想要结交新朋友，分享阅读的快乐。(make, joy)", a: "She wants to make new friends and share the joy of reading.", note: "make friends 结交朋友；the joy of reading 阅读的快乐。" },
        { zh: "一个好主意突然浮现在我的脑海。(hit)", a: "A good idea suddenly hit me.", accept: ["Suddenly a good idea hit me."], note: "an idea hits sb 某人忽然想到一个主意。" },
        { zh: "三天之后，那本书仍然在教室的书架上。(later)", a: "Three days later, the book is still on the shelf in the classroom.", note: "three days later 三天之后；on the shelf 在架子上。" },
        { zh: "让我们放学后在操场碰面。(let s do ...)", a: "Let s meet on the playground after school.", note: "Let s do sth 让我们做某事吧。" },
        { zh: "这是这次旅行最好的结局。(ending)", a: "This is the best ending of the trip.", note: "the ending of ... ……的结局。" },
      ],
    },
    {
      id: "reading",
      title: "六、阅读加油站（Different kinds of hobbies：阅读短文，选择最佳答案）",
      tip: "易读度 80.2，词数 259，建议用时 5 分钟。先读题干，再回到对应人物的段落定位。",
      type: "choice",
      passage: [
        "Different kinds of hobbies",
        "In our busy school lives, hobbies are like a breath of fresh air. Four students share their hobbies.",
        "【Jack】Hi, I'm Jack. My hobby is reading. It's my way of learning new things, from how rockets (火箭) fly to why weather changes. Through reading, I can also travel the world and discover different cultures. That's interesting! Every night, I read for half an hour before bed. It's the perfect way to relax.",
        "【Julia】My name is Julia. I love gardening. This hobby brings me closer to nature and the changing seasons. Through this hands-on activity, I've learned many useful skills. Every time my flowers bloom (开花) and my tomato plants grow fruit, I can't wait to show them to everyone. Most importantly, taking care of those plants helps me become a more patient (有耐心的) person.",
        "【Lisa】I'm Lisa, and I'm all about cooking! It's so creative. I love designing (设计) dishes and making food from different countries. I'm really good at making pizza! But the best part is cooking for my family and friends. Seeing their happy faces while they enjoy my food makes me feel proud (骄傲的) and warm inside.",
        "【John】My name is John, and my favourite hobby is basketball. It's a great way for me to stay healthy and build my strength (力量). Whenever I feel down, playing basketball for a while always makes me feel much better. I've made so many friends through basketball. We talk about our favourite NBA players happily, and we even make a plan to play together every weekend.",
      ],
      items: [
        { q: "How long does Jack usually read every night?", options: ["For one hour.", "For two hours.", "For ten minutes.", "For thirty minutes."], a: "D", explain: "原文 Every night, I read for half an hour before bed，半小时即三十分钟。" },
        { q: "How does Julia feel when she sees her plants grow?", options: ["Worried.", "Sad.", "Surprised.", "Excited."], a: "D", explain: "Julia 说 I can't wait to show them to everyone，说明她很兴奋。" },
        { q: "What does Lisa enjoy most about cooking?", options: ["Watching famous cooks on television.", "Winning a cooking competition at school.", "Making her loved ones happy with her food.", "Getting new cooking tools from her parents."], a: "C", explain: "But the best part is cooking for my family and friends. Seeing their happy faces ... makes me feel proud，故选 C。" },
        { q: "What do we know about John?", options: ["Playing basketball brings him a lot of fun.", "He and his friend like the same NBA player.", "He thinks basketball is an easy sport to learn.", "Playing basketball makes him famous at school."], a: "A", explain: "John 说打篮球让他更健康，心情变好，还交到很多朋友，说明篮球给他带来很多乐趣。" },
        { q: "What is the main idea of this text?", options: ["Hobbies can help students a lot.", "Sports hobbies are better than others.", "Schools should offer more hobby classes.", "Students at different ages enjoy different hobbies."], a: "A", explain: "文章开篇说 hobbies are like a breath of fresh air，四位同学都谈到爱好带来的好处，故主题是“爱好对学生帮助很大”。" },
      ],
    },  ],
};
