// 七年级上册 Unit 2 Homework 5: Developing ideas (写作与阅读)
export default {
  id: "tb7a-u2-5",
  book: "七年级上册",
  unit: "Unit 2",
  title: "Homework 5: Developing ideas (写作与阅读)",
  subtitle: "单元写作 · 我最喜欢的爱好",
  source: "基础同步达标手册 七年级上（北京市三帆中学）",
  pages: "P33–P36",
  vocab: [
    { word: "different kinds of", phonetic: "ˈdɪfrənt kaɪndz əv", pos: "词组", meaning: "不同种类的", use: "different kinds of hobbies 不同种类的爱好" },
    { word: "play the electric guitar", phonetic: "pleɪ ði ɪˈlektrɪk ɡɪˈtɑː(r)", pos: "词组", meaning: "弹电吉他", use: "作为摇滚乐爱好者，我在校乐队弹电吉他。" },
    { word: "school band", phonetic: "skuːl bænd", pos: "词组", meaning: "校乐队", use: "in the school band 在校乐队" },
    { word: "write songs", phonetic: "raɪt sɒŋz", pos: "词组", meaning: "写歌", use: "Sometimes I write songs and share them online." },
    { word: "a lot of", phonetic: "ə lɒt əv", pos: "词组", meaning: "许多", use: "a lot of friends 许多朋友" },
    { word: "so much fun", phonetic: "səʊ mʌtʃ fʌn", pos: "词组", meaning: "如此多乐趣", use: "There is so much fun in it." },
    { word: "help sb do sth", phonetic: "help", pos: "词组", meaning: "帮某人做某事", use: "It also helps me to make friends." },
    { word: "rabbit", phonetic: "ˈræbɪt", pos: "n.", meaning: "兔子", use: "a little rabbit 一只小兔子" },
    { word: "snake", phonetic: "sneɪk", pos: "n.", meaning: "蛇", use: "a hognose snake 猪鼻蛇" },
    { word: "vote", phonetic: "vəʊt", pos: "v. & n.", meaning: "投票", use: "Mr. Cooper lets us vote." },
    { word: "mess", phonetic: "mes", pos: "n.", meaning: "混乱，脏乱", use: "make a mess 制造混乱" },
    { word: "scared", phonetic: "skeəd", pos: "adj.", meaning: "害怕的，恐惧的", use: "be scared 害怕" },
  ],
  phrases: [
    { en: "agree with sb", zh: "同意某人（的意见）", tip: "Emily always agrees with Andrea." },
    { en: "make a mess", zh: "制造混乱", tip: "It makes a mess at school." },
    { en: "play dead", zh: "装死", tip: "They play dead when they're scared." },
    { en: "take care of", zh: "照顾，照料", tip: "taking care of those plants helps me ..." },
    { en: "feel down", zh: "情绪低落", tip: "Whenever I feel down, playing basketball makes me feel better." },
    { en: "can't wait to do sth", zh: "迫不及待做某事", tip: "I can't wait to show them to everyone." },
    { en: "make friends", zh: "交朋友", tip: "It also helps me to make friends." },
  ],
  patterns: [
    { en: "I have different kinds of hobbies, and my favourite one is ...", zh: "我有不同种类的爱好，我最喜欢的是……", note: "第一段：点明主题。" },
    { en: "When I'm free, I often do something about ... For example, I ..., sometimes I ...", zh: "我有空时常常做……例如，我……有时我……", note: "第二段：详细描述平时怎么进行这项爱好。" },
    { en: "As a ... lover, I will also ...", zh: "作为一名……爱好者，我也会……", note: "as 作介词表示“作为”。" },
    { en: "... makes my life more interesting. I get ... from it. There is so much fun in it.", zh: "……让我的生活更有趣。我从其中获得……其中有很多乐趣。", note: "第三段：介绍喜欢这个爱好的原因。" },
    { en: "It also helps me to make friends. / That's why it is my favourite hobby.", zh: "它也帮助我交朋友。/ 这就是为什么它是我最喜欢的爱好。", note: "help sb (to) do sth；That's why ... 这就是……的原因。" },
  ],
  grammar: [
    {
      title: "应用文（投稿）写作结构",
      points: [
        "体裁：应用文（校刊投稿）；时态：一般现在时；人称：以第一人称为主。",
        "第一段：点明主题——I have different kinds of hobbies, and my favourite one is ...。",
        "第二段：详细描述平时怎样进行这项爱好——When I'm free, I often ... For example ... As a ... lover, I will also ...。",
        "第三段：说明喜欢的原因——... makes my life more interesting. There is so much fun in it. It also helps me to make friends ...。",
      ],
    },
    {
      title: "一般现在时（复习与运用）",
      points: [
        "描述习惯性动作用一般现在时：I often play basketball with my friends.",
        "主语为第三人称单数时动词加 -s/-es：He likes paper-cutting.",
        "every day / often / sometimes / whenever 等是常见的时间标志词。",
      ],
    },
    {
      title: "一般过去时（叙述故事）",
      points: [
        "阅读理解中的故事用一般过去时：Mr. Cooper lets us vote. / A.J. starts shouting again.",
        "常见不规则过去式：bring → brought、eat → ate、think → thought、say → said、know → knew。",
      ],
    },
  ],
  examPoints: [
    "写作要点齐全：①最喜欢的爱好 ②平时怎么做 ③为什么喜欢，三问都要回答。",
    "阅读理解细节题要回到原文定位人物：Emily agrees with Andrea；Ryan brings Carl the skunk。",
    "任务型阅读要注意疑问词：What animal / How often / What behaviour / Does ...。",
    "play dead 装死；make a mess 制造混乱；agree with sb 同意某人。",
    "概括故事时注意人物关系：Alexia（叙述者）— Andrea（喜欢兔子）— Mr. Cooper（老师）。",
  ],
  sections: [
    {
      id: "words",
      title: "一、单元写作必备词汇（看中文写英文）",
      type: "dictation",
      items: [
        { q: "①不同种类的", a: "different kinds of", note: "kind 种类，复数为 kinds" },
        { q: "②弹电吉他", a: "play the electric guitar", note: "乐器前加 the" },
        { q: "③校乐队", a: "school band", note: "in the school band 在校乐队" },
        { q: "④写歌", a: "write songs", note: "song 歌曲，write songs 写歌" },
        { q: "⑤许多", a: "a lot of", accept: ["lots of"], note: "后接可数名词复数或不可数名词" },
        { q: "⑥如此多乐趣", a: "so much fun", note: "fun 不可数名词" },
        { q: "⑦帮某人做某事", a: "help sb do sth", accept: ["help sb to do sth"], note: "help 后接省略 to 的不定式" },
      ],
    },
    {
      id: "writing",
      title: "二、单元写作（My Favourite Hobby）",
      tip: "体裁：应用文（校刊投稿）；时态：一般现在时；人称：以第一人称为主。写完后按评价表自评。",
      type: "translate",
      items: [
        {
          zh: "【写作任务】每个人都有自己独特的爱好。请你以 My Favourite Hobby 为题，用英语写一篇短文给学校的校刊投稿：介绍你最喜欢的爱好是什么，你平时是怎么进行这项爱好的，以及为什么这是你最喜欢的爱好。（提示词语：different, take photos, play football, so much fun, make friends）",
          a: "My Favourite Hobby  I have different kinds of hobbies, and my favourite one is playing football. When I'm free, I often play football with my friends on the playground. For example, I play it every Saturday afternoon. Sometimes I watch football games on TV with my father. As a football lover, I will also take part in the school football competition. Playing football makes my life more interesting. I get great joy from it. There is so much fun in it. It also helps me to make friends, and it keeps me healthy. That's why it is my favourite hobby.",
          note: "范文按“点明主题 — 详细描述 — 说明原因”三段展开，每段第一句都是主旨句。",
        },
        {
          zh: "【段落提纲】第一段：点明主题——I have different kinds of hobbies, and my favourite one is ...",
          a: "I have different kinds of hobbies, and my favourite one is taking photos.",
          note: "开门见山，直接说明最喜欢的爱好。",
        },
        {
          zh: "【段落提纲】第二段：详细描述你平时怎么进行这项爱好——When I'm free, I often do something about ... For example, I ..., sometimes I ... As a ... lover, I will also ...",
          a: "When I'm free, I often do something about taking photos. For example, I take photos of flowers and birds in the park, and sometimes I go out with my camera at the weekend. As a photo lover, I will also learn more skills online.",
          note: "用 for example / sometimes 把做法写具体。",
        },
        {
          zh: "【段落提纲】第三段：介绍你喜欢这个爱好的原因——... makes my life more interesting. I get ... from ... There is so much fun in it. It also helps me to make friends ...",
          a: "Taking photos makes my life more interesting. I get a lot of fun from it. There is so much fun in it. It also helps me to make friends with people who have the same hobby. That's why it is my favourite hobby.",
          note: "用 It also helps me to ... 补充好处，最后用 That's why ... 收尾。",
        },
      ],
    },
    {
      id: "reading",
      title: "三、阅读加油站（My Weird School: Class Pet Mess! (1)）",
      tip: "易读度 99.6。从方框中选择合适的主语补全句子：Alexia / Andrea / Emily / Mr. Cooper / Ryan，每个名字只选一次。",
      type: "choice",
      passage: [
        "My name is Alexia and I don't like rabbits. Well, not really. But I don't want one as our class pet. Why? Because Andrea does.",
        "“A little rabbit is so cute!” she says on Friday. “So cute,” says Emily. Emily always agrees with Andrea. It's so annoying (令人恼火的).",
        "“I think we should get something cool,” I say, “like a snake.” “YES!” say all the boys. “No!” say all the girls. Mr. Cooper lets us vote (投票). Lucky for me, there are more boys than girls in the class. “No fair!” says Andrea. “Too bad,” A.J. says.",
        "On Monday, Mr. Cooper brings in a box. There is a snake inside! “This is an eastern hognose snake. His name is Bob,” he says. Then Mr. Cooper says that I can feed Bob for the first week!",
        "“He mostly eats live toads (活蟾蜍),” Mr. Cooper says. “Gross (恶心的)!” says Andrea. “Cool!” I say, clapping (拍手) my hands. This is going to be great!",
        "Mr. Cooper tells the class more things about hognose snakes: where they live, how they protect themselves, and so on. All I care about is the toad part. I can't wait to try it.",
        "The next morning, I put a toad into Bob's box. It isn't as exciting as I thought. Bob eats it in one big bite.",
        "For the rest of the week, Mr. Cooper lets students bring their pets to class. Neil brings his bird, Wiggles. It makes a mess (制造混乱) at school. Ryan brings his skunk (臭鼬), Carl. Carl makes the whole school smell (散发异味)! I have to say, Carl is cooler than Bob. (To be continued)",
      ],
      items: [
        { q: "____ always agrees with Andrea.", options: ["Alexia", "Andrea", "Emily", "Mr. Cooper", "Ryan"], a: "C", explain: "原文 Emily always agrees with Andrea，故填 Emily。" },
        { q: "____ allows students to bring pets for a week.", options: ["Alexia", "Andrea", "Emily", "Mr. Cooper", "Ryan"], a: "D", explain: "原文 For the rest of the week, Mr. Cooper lets students bring their pets to class，故填 Mr. Cooper。" },
        { q: "____ thinks rabbits are cute but snakes are gross.", options: ["Alexia", "Andrea", "Emily", "Mr. Cooper", "Ryan"], a: "B", explain: "Andrea 说 a little rabbit is so cute，看到蛇时说 Gross，故填 Andrea。" },
        { q: "____ brings a smelly skunk named Carl to school.", options: ["Alexia", "Andrea", "Emily", "Mr. Cooper", "Ryan"], a: "E", explain: "原文 Ryan brings his skunk, Carl. Carl makes the whole school smell，故填 Ryan。" },
        { q: "____ doesn't want a rabbit because Andrea likes it.", options: ["Alexia", "Andrea", "Emily", "Mr. Cooper", "Ryan"], a: "A", explain: "原文 I don't want one as our class pet. Why? Because Andrea does.（I 指 Alexia），故填 Alexia。" },
      ],
    },
    {
      id: "reading2",
      title: "四、阅读加油站（My Weird School: Class Pet Mess! (2)）",
      tip: "易读度 97.1。根据短文内容完成下面的任务，注意疑问词与答题方式。",
      type: "translate",
      passage: [
        "(Continued) I am still thinking about Bob the next day. When did I last feed him? Let me see, today is Friday. I fed him on ... Tuesday? Oh no!",
        "Just then, Andrea comes in with a little dog. “This is Cupcake! Isn't she sweet?” Cupcake jumps out of Andrea's arms and runs over to Bob's box. She puts her face close to the glass.",
        "“Go away, Cupcake!” I say. I run over there just in time to see Bob fall over! He is lying (躺) on his back. His little tongue (舌头) is hanging out of his mouth. Oh no! BOB IS DEAD!",
        "“Andrea's dog kills Bob!” A.J. shouts. “We have to do something!” shouts Emily. “Kids, calm down!” says Mr. Cooper. But everyone is scared.",
        "I am scared the most, because I know who really kills Bob. “STOP!” I cry. “It's my fault (错误)! I forgot to feed him! He hasn't had any toads since Tuesday!”",
        "“Alexia, he doesn't need to have any more toads,” says Mr. Cooper. “He only eats once a week. Remember?” “Wait, so I don't kill Bob?” I ask. A.J. starts shouting again. “Then it has to be that dog! This is all Andrea's fault!”",
        "“I'm sorry,” Andrea says. “I'll take Bob home and bury (埋葬) him.” She reaches into Bob's box and picks him up. Suddenly, Bob moves! “AAAAAAAAAAH!” shouts Andrea. Her mouth opens so wide.",
        "“Didn't any of you listen when I talked about hognose snakes?” cries Mr. Cooper. “They play dead (装死) when they're scared. Bob is fine!”",
        "Bob is fine. More than fine. He's the best, coolest class pet in the world. Why? Because Andrea really hates him. Will Andrea learn to like Bob? Will we change Bob for a little rabbit? Never! (The end)",
      ],
      items: [
        { zh: "1. What animal does Andrea bring to class?", a: "She brings a little dog (named Cupcake).", note: "原文 Andrea comes in with a little dog. This is Cupcake!。" },
        { zh: "2. How often does Bob actually need to eat?", a: "He only eats once a week.", note: "原文 He only eats once a week.，注意 How often 要回答频率。" },
        { zh: "3. What special behaviour (行为) do hognose snakes have? They ____ when scared.", a: "play dead", note: "原文 They play dead when they're scared.。" },
        { zh: "4. Does Andrea like Bob at the end of the story?", a: "No, she doesn't. She really hates him.", note: "结尾说 Because Andrea really hates him ... Never!，说明 Andrea 始终不喜欢 Bob。" },
      ],
    },
  ],
};
