// 七年级上册 Unit 3 Homework 1: Starting out + Understanding ideas (1)
export default {
  id: "tb7a-u3-1",
  book: "七年级上册",
  unit: "Unit 3",
  title: "Homework 1: Starting out + Understanding ideas (1)",
  subtitle: "沉默的爱 · 父子邮路",
  source: "基础同步达标手册 七年级上（北京市三帆中学）",
  pages: "P37–P38",
  vocab: [
    { word: "silent", phonetic: "ˈsaɪlənt", pos: "adj.", meaning: "不作声的，沉默的", use: "His love may be silent." },
    { word: "along", phonetic: "əˈlɒŋ", pos: "prep.", meaning: "顺着；沿着", use: "Along a mountain road ..." },
    { word: "mountain", phonetic: "ˈmaʊntən", pos: "n.", meaning: "高山，山岳", use: "like a mountain 像一座山" },
    { word: "road", phonetic: "rəʊd", pos: "n.", meaning: "路，道路，公路", use: "a mountain road 山路" },
    { word: "handsome", phonetic: "ˈhænsəm", pos: "adj.", meaning: "（男子）英俊的，漂亮的", use: "a handsome young man" },
    { word: "strict", phonetic: "strɪkt", pos: "adj.", meaning: "严格的，严厉的", use: "with a strict face 表情严肃" },
    { word: "follow", phonetic: "ˈfɒləʊ", pos: "v.", meaning: "跟着，跟随", use: "An older man follows him." },
    { word: "postman", phonetic: "ˈpəʊstmən", pos: "n.", meaning: "邮递员；邮差", use: "serve as the postman 当邮递员" },
    { word: "touching", phonetic: "ˈtʌtʃɪŋ", pos: "adj.", meaning: "感人的；动人的", use: "a touching story 一个感人的故事" },
    { word: "son", phonetic: "sʌn", pos: "n.", meaning: "儿子", use: "the love between father and son" },
    { word: "serve", phonetic: "sɜːv", pos: "v.", meaning: "为……工作；供职", use: "serve as 担任" },
    { word: "area", phonetic: "ˈeəriə", pos: "n.", meaning: "（国家、市镇等的）地区，区域", use: "in this area 在这个地区" },
    { word: "absent", phonetic: "ˈæbsənt", pos: "adj.", meaning: "不在的，缺席的", use: "be absent from home 不在家" },
    { word: "seldom", phonetic: "ˈseldəm", pos: "adv.", meaning: "很少，罕见，不常", use: "The son seldom saw him." },
    { word: "position", phonetic: "pəˈzɪʃən", pos: "n.", meaning: "职位，职务", use: "take over his father's position" },
    { word: "carry", phonetic: "ˈkæri", pos: "v.", meaning: "把……带至……；搬，扛", use: "carry his father across a river" },
    { word: "across", phonetic: "əˈkrɒs", pos: "prep.", meaning: "从一边到另一边；穿过", use: "across a cold river" },
    { word: "memory", phonetic: "ˈmeməri", pos: "n.", meaning: "记忆，回忆", use: "bring back the father's memory" },
    { word: "tear", phonetic: "tɪə", pos: "n.", meaning: "眼泪；泪水", use: "Tears run down his face." },
    { word: "growth", phonetic: "ɡrəʊθ", pos: "n.", meaning: "（性格、智力或情感的）发展，成长", use: "be happy about his son's growth" },
    { word: "hide", phonetic: "haɪd", pos: "v.", meaning: "把……藏起来，隐藏", use: "hide his care in his heart" },
    { word: "care", phonetic: "keə", pos: "n.", meaning: "关心，关爱", use: "show her love and care" },
    { word: "hug", phonetic: "hʌɡ", pos: "n. & v.", meaning: "拥抱", use: "give hugs to sb 拥抱某人" },
    { word: "kiss", phonetic: "kɪs", pos: "n. & v.", meaning: "吻", use: "give kisses to sb 亲吻某人" },
  ],
  phrases: [
    { en: "communicate with sb", zh: "和某人交流", tip: "How do you communicate with your family?" },
    { en: "with a strict face", zh: "表情严肃", tip: "An older man with a strict face follows him." },
    { en: "be absent from", zh: "缺席，不在", tip: "He was often absent from home." },
    { en: "along the way", zh: "一路上，沿途", tip: "Along the way, they start to see into each other's hearts." },
    { en: "bring back", zh: "使回忆起；带回", tip: "It brings back the father's memory." },
    { en: "serve as", zh: "担任，充当", tip: "serve as the postman 当邮递员" },
    { en: "take over", zh: "接管，接任", tip: "The son is taking over his father's position." },
    { en: "see into each other's hearts", zh: "读懂彼此的内心", tip: "see into 看透，了解" },
  ],
  patterns: [
    { en: "Along a mountain road, a handsome young man walks fast.", zh: "沿着山路，一个英俊的年轻人快步走着。", note: "along 作介词，表示“沿着”。" },
    { en: "An older man with a strict face follows him.", zh: "一位表情严肃的长者跟在他身后。", note: "with + 名词短语作后置定语。" },
    { en: "It's a touching story about the love between father and son.", zh: "这是一个关于父子之爱的感人故事。", note: "between ... and ... 表示两者之间。" },
    { en: "For years, the father served as the postman for this area.", zh: "多年来，父亲在这个地区当邮递员。", note: "serve as 担任；for years 多年来。" },
    { en: "Along the way, they start to see into each other's hearts.", zh: "一路上，他们开始读懂彼此的内心。", note: "see into 看透，了解。" },
    { en: "It brings back the father's memory of carrying the son on his shoulders.", zh: "这使父亲回想起把儿子扛在肩上的记忆。", note: "bring back one's memory 使某人回忆起。" },
    { en: "His love may be silent. But like a mountain, it is always there.", zh: "他的爱也许是沉默的，但它像一座山，一直都在。", note: "like a mountain 像山一样；be always there 一直都在。" },
  ],
  grammar: [
    {
      title: "一般过去时（叙述过去的事）",
      points: [
        "规则动词过去式：follow → followed、serve → served、start → started、walk → walked。",
        "不规则动词过去式：carry → carried（变 y 为 i 加 -ed）、hide → hid、give → gave、see → saw。",
        "The father served as the postman for this area. / He was often absent from home.",
      ],
    },
    {
      title: "现在进行时与一般现在时对比",
      points: [
        "现在进行时表示正在发生：Now the son is taking over his father's position.",
        "一般现在时表示经常或客观情况：Everyone has dinner there. / It seldom rains in this area.",
        "quietly / loudly / heavily 等副词修饰动词：move quietly and make little sound。",
      ],
    },
    {
      title: "介词与介词短语",
      points: [
        "along（沿着）/ across（穿过）/ between ... and ...（在……之间）/ with（和……一起）。",
        "along the way 沿途；across a cold river 穿过冰冷的河；with a strict face 表情严肃。",
      ],
    },
    {
      title: "形容词与副词的用法",
      points: [
        "be + 形容词：Steven is absent from school. / He looks very handsome.",
        "实义动词 + 副词：Elephants can move quietly. / Tears quietly run down his face.",
      ],
    },
  ],
  examPoints: [
    "be absent from school 缺课；反义词组是 be present at school。",
    "a good memory 记性好：My grandpa has a good memory.。",
    "serve as a postman 当邮递员；take over one's position 接任某人的职位。",
    "感叹与回应：I can't believe it. 我不相信。；It seldom rains ... so we need water.。",
    "看音标写单词：['hænsəm] handsome、[ə'lɒŋ] along、[pə'zɪʃən] position、[grəʊθ] growth。",
  ],
  sections: [
    {
      id: "words",
      title: "一、单词巩固（看音标和中文写单词）",
      type: "dictation",
      items: [
        { q: "[ˈsaɪlənt] adj. 不作声的", a: "silent", note: "His love may be silent." },
        { q: "[əˈlɒŋ] prep. 顺着；沿着", a: "along", note: "along the road 沿着路" },
        { q: "[ˈmaʊntən] n. 高山，山岳", a: "mountain", note: "like a mountain 像山一样" },
        { q: "[rəʊd] n. 路，道路，公路", a: "road", note: "a mountain road 山路" },
        { q: "[ˈhænsəm] adj.（男子）英俊的，漂亮的", a: "handsome", note: "a handsome young man" },
        { q: "[strɪkt] adj. 严格的，严厉的", a: "strict", note: "with a strict face 表情严肃" },
        { q: "[ˈfɒləʊ] v. 跟着，跟随", a: "follow", note: "follow sb 跟着某人" },
        { q: "[ˈpəʊstmən] n. 邮递员；邮差", a: "postman", note: "serve as the postman 当邮递员" },
        { q: "[ˈtʌtʃɪŋ] adj. 感人的；动人的", a: "touching", note: "a touching story 感人的故事" },
        { q: "[sʌn] n. 儿子", a: "son", note: "注意与 sun /sʌn/ 同音" },
        { q: "[sɜːv] v. 为……工作；供职", a: "serve", note: "serve as 担任" },
        { q: "[ˈeəriə] n.（国家、市镇等的）地区，区域", a: "area", note: "in this area 在这个地区" },
        { q: "[ˈæbsənt] adj. 不在的，缺席的", a: "absent", note: "be absent from 缺席" },
        { q: "[ˈseldəm] adv. 很少，罕见，不常", a: "seldom", note: "反义词 often；置于实义动词前" },
        { q: "[pəˈzɪʃən] n. 职位，职务", a: "position", note: "take over one's position 接任职位" },
        { q: "[ˈkæri] v. 把……带至……", a: "carry", note: "carry sth to sb 把某物带给某人" },
        { q: "[əˈkrɒs] prep. 从一边到另一边；穿过", a: "across", note: "across the river 穿过河" },
        { q: "[ˈmeməri] n. 记忆，回忆", a: "memory", note: "a good memory 好记性" },
        { q: "[tɪə] n. 眼泪；泪水", a: "tear", note: "Tears run down his face." },
        { q: "[ɡrəʊθ] n.（性格、智力或情感的）发展，成长", a: "growth", note: "his son's growth 他儿子的成长" },
        { q: "[haɪd] v. 把……藏起来，隐藏", a: "hide", note: "hide his care in his heart" },
        { q: "[keə] n. 关心", a: "care", note: "show her love and care" },
        { q: "[hʌɡ] n. 拥抱", a: "hug", note: "give sb a hug 拥抱某人" },
        { q: "[kɪs] n. 吻", a: "kiss", note: "give sb a kiss 亲吻某人" },
      ],
    },
    {
      id: "phrases",
      title: "二、词组过关（按提示补全句子）",
      type: "fill",
      items: [
        { q: "How do you ____ ____（和……交流）your family?", a: "communicate with", accept: ["talk with", "talk to"], zh: "你怎样和你的家人交流？", note: "communicate with sb 与某人交流。" },
        { q: "An older man with a ____ ____（严肃的表情）follows him.", a: "strict face", accept: ["strict look"], zh: "一位表情严肃的长者跟在他身后。", note: "课文原句 An older man with a strict face follows him.。" },
        { q: "He was often ____ ____ home（缺席）and the son seldom saw him.", a: "absent from", zh: "他常常不在家，儿子很少见到他。", note: "be absent from home 不在家。" },
        { q: "____ ____ ____（一路上）they start to see into each other's hearts.", a: "Along the way", zh: "一路上，他们开始读懂彼此的内心。", note: "along the way 一路上。" },
        { q: "It ____ ____（使回忆起）the father's memory of carrying the son on his shoulders.", a: "brings back", zh: "这使父亲回想起把儿子扛在肩上的记忆。", note: "bring back one's memory 使某人回忆起。" },
      ],
    },
    {
      id: "wordform",
      title: "三、根据句意、音标、首字母或汉语提示写单词",
      type: "fill",
      items: [
        { q: "Don't talk in the library. We'd better keep s____.", a: "silent", zh: "不要在图书馆里讲话，我们最好保持安静。", note: "keep silent 保持沉默。" },
        { q: "My aunt made a card for me because she wanted to show her love and c____ to me.", a: "care", zh: "姑姑给我做了一张卡片，因为她想表达对我的爱与关心。", note: "show one's love and care 表达爱与关心。" },
        { q: "Climbing the ____（山）is a good way to get close to nature.", a: "mountain", zh: "爬山是亲近大自然的好方式。", note: "climb the mountain 爬山。" },
        { q: "He wears a black jacket and looks very ____ [ˈhænsəm].", a: "handsome", zh: "他穿着黑色夹克，看起来很帅。", note: "look + 形容词，looks handsome。" },
        { q: "Leo likes taking a walk ____ [əˈlɒŋ] the river to relax himself.", a: "along", zh: "利奥喜欢沿着河边散步来放松自己。", note: "along the river 沿着河边。" },
      ],
    },
    {
      id: "choice",
      title: "四、单项选择",
      type: "choice",
      items: [
        { q: "— Is everyone here today?\n— No. Steven is ____ from school because he's ill.", options: ["present", "absent", "far", "different"], a: "B", explain: "因为生病没来上学，用 be absent from school 缺课。" },
        { q: "— Elephants are big, but they can move ____ and make little sound.\n— Oh, I can't believe it.", options: ["loudly", "badly", "quietly", "heavily"], a: "C", explain: "make little sound（几乎没有声音）说明大象移动得很安静，用 quietly。" },
        { q: "My grandpa has a good ____. He can remember things well.", options: ["house", "family", "memory", "book"], a: "C", explain: "能记住事情说明记性好，a good memory。" },
        { q: "My brother ____ as a postman in the post office in our city.", options: ["teaches", "serves", "learns", "sees"], a: "B", explain: "serve as ... 担任……；主语 My brother 是第三人称单数，用 serves。" },
        { q: "— It ____ rains in this area, so we need water.\n— Oh, there's a lot of rain in my hometown every summer.", options: ["often", "always", "seldom", "usually"], a: "C", explain: "因为需要水，说明这里很少下雨，用 seldom（很少）。" },
      ],
    },
    {
      id: "cloze",
      title: "五、语法填空（填入适当的词或括号中所给单词的正确形式）",
      type: "cloze",
      passage: [
        "My dream house is big and clean, and it is near the sea. I can watch the sea and play volleyball on the beach. My grandparents live {{1}} us in this big house. {{2}} (they) room is on the first floor. I always talk with them and help them {{3}} (do) some housework at weekends.",
        "On the second floor, there is {{4}} kitchen and a dining room. Everyone {{5}} (have) dinner there. My bedroom, study and bathroom are on the {{6}} (three) floor. I enjoy {{7}} (listen) to music while reading books in my bedroom.",
        "My parents' room is on the fourth floor. It's very big and clean, too. There is a big {{8}} nice garden behind the big house. There are many {{9}} (flower) and some tall trees in it. In summer, I can sit under the trees with my family. Behind the garden, there is a swimming pool. I can swim in it. I think the life will be very {{10}} (interest) and comfortable (舒适的) in my dream house.",
      ],
      blanks: [
        { n: 1, a: "with", hint: "无提示", explain: "live with us 和我们住在一起。" },
        { n: 2, a: "Their", hint: "they", explain: "修饰名词 room 用形容词性物主代词 Their，句首大写。" },
        { n: 3, a: "do", hint: "do", explain: "help sb (to) do sth 帮助某人做某事，用动词原形。" },
        { n: 4, a: "a", hint: "无提示", explain: "kitchen 是可数名词单数，第一次提到用 a。" },
        { n: 5, a: "has", hint: "have", explain: "Everyone 作主语视为第三人称单数，用 has。" },
        { n: 6, a: "third", hint: "three", explain: "表示楼层用序数词，three → third。" },
        { n: 7, a: "listening", hint: "listen", explain: "enjoy doing sth 喜欢做某事。" },
        { n: 8, a: "and", hint: "无提示", explain: "a big and nice garden，两个形容词之间用 and 连接。" },
        { n: 9, a: "flowers", hint: "flower", explain: "many 后接可数名词复数 flowers。" },
        { n: 10, a: "interesting", hint: "interest", explain: "修饰 the life 用 -ing 形式的形容词 interesting。" },
      ],
    },
    {
      id: "translate",
      title: "六、根据中文意思和英文提示词语写出句子",
      type: "translate",
      items: [
        { zh: "银行在书店和邮局之间。(between ... and ...)", a: "The bank is between the bookshop and the post office.", note: "between ... and ... 在两者之间。" },
        { zh: "泪水正顺着她的脸流下来。(run down)", a: "Tears are running down her face.", note: "run down 顺着……流下。" },
        { zh: "他一直担任我们的校车司机。(serve as)", a: "He always serves as our school bus driver.", note: "serve as 担任；主语第三人称单数用 serves。" },
        { zh: "你将什么时候接管你父亲的生意？(take over; business)", a: "When will you take over your father's business?", note: "take over 接管；一般将来时用 will + 动词原形。" },
        { zh: "我很难弄清他的全部意思。(see into)", a: "It is hard for me to see into all his meaning.", note: "see into 看懂，了解；It is hard for sb to do sth 句型。" },
      ],
    },
  ],
};
