// 七年级上册 Unit 3 Homework 2: Understanding ideas (2)
export default {
  id: "tb7a-u3-2",
  book: "七年级上册",
  unit: "Unit 3",
  title: "Homework 2: Understanding ideas (2)",
  subtitle: "名词所有格专项 · 全家福",
  source: "基础同步达标手册 七年级上（北京市三帆中学）",
  pages: "P39–P41",
  vocab: [
    { word: "marry", phonetic: "ˈmæri", pos: "v.", meaning: "结婚；娶；嫁", use: "marry sb 和某人结婚" },
    { word: "photo", phonetic: "ˈfəʊtəʊ", pos: "n.", meaning: "照片", use: "this year's photo 今年的照片" },
    { word: "screen", phonetic: "skriːn", pos: "n.", meaning: "屏幕", use: "on the screen 在屏幕上" },
    { word: "tradition", phonetic: "trəˈdɪʃn", pos: "n.", meaning: "传统", use: "keep the family tradition 保持家庭传统" },
    { word: "abroad", phonetic: "əˈbrɔːd", pos: "adv.", meaning: "在国外，到国外", use: "go abroad 出国；be abroad 在国外" },
    { word: "neighbour", phonetic: "ˈneɪbə(r)", pos: "n.", meaning: "邻居", use: "our neighbour's dog 我们邻居的狗" },
    { word: "compare", phonetic: "kəmˈpeə(r)", pos: "v.", meaning: "比较", use: "compare A with B 把 A 与 B 比较" },
    { word: "world", phonetic: "wɜːld", pos: "n.", meaning: "世界", use: "the world's longest river 世界上最长的河流" },
    { word: "tailor", phonetic: "ˈteɪlə", pos: "n.", meaning: "裁缝", use: "She is a tailor." },
    { word: "retired", phonetic: "rɪˈtaɪəd", pos: "adj.", meaning: "退休的", use: "a retired serviceman 一位退役军人" },
    { word: "join", phonetic: "dʒɔɪn", pos: "v.", meaning: "参加；加入", use: "ask us to join him 叫我们和他一起去" },
    { word: "blonde", phonetic: "blɒnd", pos: "adj.", meaning: "金色的", use: "the woman with blonde hair 金发的女士" },
    { word: "writer", phonetic: "ˈraɪtə(r)", pos: "n.", meaning: "作家", use: "My mum is a writer." },
    { word: "argue", phonetic: "ˈɑːɡjuː", pos: "v.", meaning: "争吵，争论", use: "We argue sometimes." },
    { word: "grow", phonetic: "ɡrəʊ", pos: "v.", meaning: "成长", use: "grow together 一起成长" },
    { word: "warmth", phonetic: "wɔːmθ", pos: "n.", meaning: "温暖", use: "feel their warmth 感受他们的温暖" },
  ],
  phrases: [
    { en: "in front of", zh: "在……前面", tip: "sit in front of Mum's computer" },
    { en: "keep the family tradition", zh: "保持家庭传统", tip: "How can we keep the family tradition?" },
    { en: "on the screen", zh: "在屏幕上", tip: "come on the screen 出现在屏幕上" },
    { en: "far apart", zh: "相距很远", tip: "together or far apart 无论是相聚还是相隔很远" },
    { en: "wait for", zh: "等待", tip: "wait for my teacher's call 等老师的电话" },
    { en: "every year", zh: "每年", tip: "用于一般现在时表习惯。" },
    { en: "Mother's Day / Children's Day", zh: "母亲节 / 儿童节", tip: "节日名中的所有格要记牢。" },
  ],
  patterns: [
    { en: "This is a child's car.", zh: "这是一辆儿童车。", note: "单数名词后加 's 表示所有格。" },
    { en: "This is my sisters' room.", zh: "这是我姐姐们的房间。", note: "以 s 结尾的复数名词只在 s 后加 '。" },
    { en: "Children's Day is in June.", zh: "儿童节在六月。", note: "不以 s 结尾的复数名词加 's。" },
    { en: "This is a map of China.", zh: "这是一张中国地图。", note: "无生命的名词常用 of 所有格。" },
    { en: "Uncle Wang is a friend of my father's.", zh: "王叔叔是我爸爸的一个朋友。", note: "双重所有格：of + 名词所有格 / 名词性物主代词。" },
    { en: "This is Tim and Tom's bedroom.", zh: "这是蒂姆和汤姆（共有）的卧室。", note: "A and B's 表示两人共有。" },
    { en: "These are Tim's and Tom's bedrooms.", zh: "这些是蒂姆和汤姆各自的卧室。", note: "A's and B's 表示各自所有。" },
  ],
  grammar: [
    {
      title: "名词所有格的构成",
      points: [
        "单数名词后加 's：a child's car、Tom's sister。",
        "以 s 结尾的复数名词只在 s 后加 '：my sisters' room、the students' books。",
        "不以 s 结尾的复数名词加 's：Children's Day、women's clothes。",
        "无生命的名词常用 of 所有格：a map of China。",
      ],
    },
    {
      title: "双重所有格",
      points: [
        "a / an / 可数名词单数 + of + 名词所有格 / 名词性物主代词。",
        "a friend of my father's 我爸爸的一个朋友；a friend of mine 我的一个朋友。",
        "不能写成 a friend of me。",
      ],
    },
    {
      title: "共有与各有",
      points: [
        "A and B's + 单数名词：两人共有一样东西（This is Tim and Tom's bedroom.）。",
        "A's and B's + 复数名词：两人各有一件东西（These are Tim's and Tom's bedrooms.）。",
      ],
    },
    {
      title: "特殊用法",
      points: [
        "表示时间、距离、价值、国家、城市、自然现象等无生命的名词也可用 's：today's newspaper、three hours' riding、China's first gold medal。",
        "表示诊所、店铺或某人的家，所有格后的名词常省略：at the doctor's（office）、at the tailor's（shop）、at Mr. Black's（house）。",
      ],
    },
  ],
  examPoints: [
    "以 s 结尾的复数名词所有格只加 '，不要写成 's。",
    "双重所有格要用名词所有格或名词性物主代词：a friend of mine / a friend of my father's。",
    "共有与各有要看后面的名词是单数还是复数：Tim and Tom's bedroom / Tim's and Tom's bedrooms。",
    "it takes two days' time：表示时间的名词所有格作定语。",
    "翻译时注意：wait for 等待、in front of 在……前面（外部前方）、in the front of 在……前部（内部）。",
  ],
  sections: [
    {
      id: "words",
      title: "一、单词巩固（看音标和中文写单词）",
      type: "dictation",
      items: [
        { q: "[ˈmæri] v. 结婚；娶；嫁", a: "marry", note: "marry sb 与某人结婚；be married 已婚" },
      ],
    },
    {
      id: "phrases",
      title: "二、词组过关（按提示补全句子）",
      type: "fill",
      items: [
        { q: "We three are sitting ____ ____ ____（在……前面）Mum's computer.", a: "in front of", zh: "我们三个坐在妈妈电脑的前面。", note: "in front of 在……（外部）前面。" },
        { q: "But this year's photo ____ ____（是不同的）.", a: "is different", zh: "但今年的照片是不一样的。", note: "be different 是不同的。" },
        { q: "How can we ____ ____ ____ ____（保持家庭传统）?", a: "keep the family tradition", zh: "我们怎样才能保持家庭传统？", note: "keep the tradition 保持传统。" },
        { q: "The photo comes ____ ____ ____（在屏幕上）with four smiling faces.", a: "on the screen", zh: "照片出现在屏幕上，带着四张笑脸。", note: "on the screen 在屏幕上；with 表示“带有”。" },
        { q: "We are a family, together or ____ ____（遥远的）.", a: "far apart", zh: "我们是一家人，无论相聚还是相隔很远。", note: "far apart 相距很远。" },
      ],
    },
    {
      id: "recap",
      title: "三、语法回顾与填一填（补全名词所有格知识并完成句子）",
      type: "fill",
      items: [
        { q: "单数名词后加 's：This is a ____ (child) car.", a: "child's", zh: "这是一辆儿童车。", note: "单数名词所有格加 's。" },
        { q: "以 s 结尾的复数名词只在 s 后加 '：This is my ____ (sisters) room.", a: "sisters'", zh: "这是我姐姐们的房间。", note: "以 s 结尾的复数名词只加 '。" },
        { q: "不以 s 结尾的复数名词加 's：____ (Children) Day is in June.", a: "Children's", zh: "儿童节在六月。", note: "children 的复数是 children。" },
        { q: "of 所有格：This is a map ____ China.", a: "of", zh: "这是一张中国地图。", note: "无生命的名词常用 of 所有格。" },
        { q: "双重所有格：a friend of my ____ (father) 我爸爸的一个朋友；a friend of ____ 我的一个朋友", a: "father's mine", zh: "双重所有格结构。", note: "of + 名词所有格 / 名词性物主代词。" },
        { q: "A and B 共有：This is ____ and ____ bedroom.", a: "Tim Tom's", zh: "这是蒂姆和汤姆（共有）的卧室。", note: "共有只在最后一个名字后加 's。" },
        { q: "A 和 B 各有：These are Tim's and ____ bedrooms.", a: "Tom's", zh: "这些是蒂姆和汤姆各自的卧室。", note: "各有则每个名字后都加 's。" },
        { q: "特殊用法：____ (today) newspaper 今天的报纸；three ____ (hour) riding 三小时的车程", a: "today's hours'", zh: "表示时间等无生命名词也可用 's。", note: "today's；three hours' riding。" },
        { q: "The woman in red is ____ mother.（穿红色衣服的女人是托尼的妈妈。）", a: "Tony's", zh: "穿红色衣服的女人是托尼的妈妈。", note: "单数名词所有格加 's。" },
        { q: "I will buy some flowers for my mother on ____ Day.（母亲节那天，我将为我妈妈买些花。）", a: "Mother's", zh: "母亲节那天我要给妈妈买花。", note: "Mother's Day 母亲节。" },
        { q: "Children always have a good time on ____ Day.（孩子们在儿童节那天总是玩得很开心。）", a: "Children's", zh: "孩子们在儿童节总是玩得很开心。", note: "Children's Day 儿童节。" },
        { q: "The two women are ____ mothers.（那两位女士是琳达和吉姆的妈妈。）", a: "Linda and Jim's", zh: "那两位女士是琳达和吉姆的妈妈。", note: "两人共有（同一个妈妈？此处指共同的妈妈），只在最后加 's。" },
        { q: "This is ____ room.（这是露西和莉莉的房间。）", a: "Lucy and Lily's", zh: "这是露西和莉莉的房间。", note: "共用一个房间，共有所有格。" },
        { q: "The leg ____ the desk is broken.（这张书桌的腿折了。）", a: "of", zh: "这张书桌的腿折了。", note: "无生命的东西用 of 所有格。" },
        { q: "Uncle Wang is a friend of ____.（王叔叔是我爸爸的一个朋友。）", a: "my father's", zh: "王叔叔是我爸爸的一个朋友。", note: "双重所有格 of + 名词所有格。" },
      ],
    },
    {
      id: "choice",
      title: "四、单项选择",
      type: "choice",
      items: [
        { q: "The girl in a red dress is ____ sister Jenny.", options: ["Tom", "Tom's", "Toms", "Toms'"], a: "B", explain: "单数名词 Tom 的所有格是 Tom's。" },
        { q: "— Who is that woman?\n— She is ____ mother.", options: ["Tony and Peter's", "Tony and Peter", "Tony's and Peter's", "Tony's and Peter"], a: "A", explain: "mother 是单数，说明两人共有同一位妈妈，用 A and B's。" },
        { q: "This year, the family went camping on ____ Day.", options: ["Child", "Child's", "Children's", "Children"], a: "C", explain: "儿童节是 Children's Day。" },
        { q: "I met John at the ____ last time. The doctor said he was much better.", options: ["doctor's", "doctor", "teacher's", "teacher"], a: "A", explain: "由 The doctor 可知是在诊所，at the doctor's (office) 表示在诊所。" },
        { q: "Mr. Black is a friend of ____.", options: ["Jack's aunt's", "Jack's aunt", "Jack aunt's", "Jack aunt"], a: "A", explain: "双重所有格：of + 名词所有格，Jack's aunt's 表示“杰克姑姑的（朋友）”。" },
      ],
    },
    {
      id: "formfill",
      title: "五、用所给词的适当形式填空",
      type: "fill",
      items: [
        { q: "In the 1920s, the ____ (world) first three-colour traffic lights were put into use.", a: "world's", zh: "20 世纪 20 年代，世界上第一组三色交通灯投入使用。", note: "the world's first ... 世界上的第一个。" },
        { q: "It takes two ____ (day) time to finish this picture.", a: "days'", zh: "完成这幅画要花两天时间。", note: "表示时间的名词所有格作定语：two days' time。" },
        { q: "— Is your grandpa at home, Alice?\n— No, he isn't. He's at ____ (Mr. Green).", a: "Mr. Green's", zh: "——爱丽丝，你爷爷在家吗？——不在，他在格林先生家。", note: "at Mr. Green's 表示在格林先生家，后面的 house 省略。" },
        { q: "We would like to look after our ____ (neighbour) dog when she is away.", a: "neighbour's", zh: "邻居不在时我们想照看她的狗。", note: "单数名词所有格加 's。" },
        { q: "We shouldn't compare (v. 比较) our clothes or shoes with our ____ (classmate).", a: "classmates'", zh: "我们不应该和同学们比衣服或鞋子。", note: "以 s 结尾的复数名词所有格只加 '。" },
      ],
    },
    {
      id: "translate",
      title: "六、根据中文意思和英文提示词语写出句子",
      type: "translate",
      items: [
        { zh: "我的家长正等待着老师的电话。(wait for)", a: "My parents are waiting for my teacher's call.", note: "wait for 等待；现在进行时 are waiting。" },
        { zh: "每年，我和哥哥春节都吃饺子。(every year; the Spring Festival)", a: "Every year, my brother and I eat dumplings at the Spring Festival.", note: "每年用一般现在时；the Spring Festival 前用 at。" },
        { zh: "他出国学习了。(be abroad)", a: "He went abroad to study.", accept: ["He is abroad to study.", "He is studying abroad."], note: "go abroad 出国；be abroad 在国外。" },
        { zh: "Lily 的书桌在电视前面。(in front of)", a: "Lily's desk is in front of the TV.", note: "in front of 在……前面（外部）。" },
        { zh: "这是我同学们的最佳照片。(best photo)", a: "This is the best photo of my classmates.", note: "of 所有格表示“我同学们的”。" },
      ],
    },
    {
      id: "reading",
      title: "七、阅读加油站（This is my family：阅读短文，选择最佳答案）",
      type: "choice",
      tip: "Pre-reading: Where is the warmest place in the world?（世界上最温暖的地方在哪里？）带着这个问题读短文，完成文后 5 道小题。",
      passage: [
        "Hi, my name is Daisy. I'm 13 and in 7th grade. I have a wonderful family. Here's a photo of us. I'm the one in the pink dress.",
        "Sitting right in the middle is my grandmother, Tracy. She is a tailor (裁缝). She has made lots of beautiful clothes for me. Next to her is my grandfather, Richard. He is a retired serviceman (退役军人). He goes for a walk every morning and often asks us to join him. But none of us can get up as early as he does.",
        "The handsome man behind my grandfather is my dad, John. He is an engineer (工程师). He spends most of his time working. But in his free time, he enjoys going fishing and cooking for us. The woman with blonde hair is my mum, Jane. She is a writer and has come out with (出版) many books. She tells me that words have super power (力量). I want to be just like her one day.",
        "Standing between my mum and dad is my brother, Tom. He is two years older than me and is in 9th grade. He is great at both maths and football. We argue (吵架) sometimes, but we love each other very much. He always helps me out when I have problems with my schoolwork.",
        "During the holidays, we go on a trip together. We really enjoy the time we spend together. I love my family so much. They are the best in the world.",
      ],
      items: [
        { q: "What is Daisy wearing in the photo?", options: ["A white shirt.", "A black skirt.", "A blue T-shirt.", "A pink dress."], a: "D", explain: "文中说 I'm the one in the pink dress，可见她穿着粉色连衣裙。" },
        { q: "Why don't Daisy and the others go walking with grandfather?", options: ["They like other sports.", "They often forget to join him.", "They are still asleep at that time.", "They have to go to work or school."], a: "C", explain: "none of us can get up as early as he does 说明他们那时还在睡觉。" },
        { q: "Who would most likely (最可能) help Daisy with writing?", options: ["Her father, John.", "Her mother, Jane.", "Her grandmother, Tracy.", "Her grandfather, Richard."], a: "B", explain: "妈妈 Jane 是作家（writer），还会出版很多书，最可能在写作上帮助她。" },
        { q: "What can we learn about Daisy's brother?", options: ["He doesn't like Daisy.", "He is younger than Daisy.", "He wants to be a football player.", "He helps Daisy with her studies."], a: "D", explain: "He always helps me out when I have problems with my schoolwork。他比 Daisy 大两岁。" },
        { q: "How does Daisy feel about being in the family?", options: ["Happy.", "Sorry.", "Busy.", "Difficult."], a: "A", explain: "I love my family so much. They are the best in the world. 可见她感到幸福快乐。" },
      ],
    },
  ],
};
