// 七年级上册 Unit 3 Homework 3: Developing ideas (Listening and Speaking) —— P42–P43
export default {
  id: "tb7a-u3-3",
  book: "七年级上册",
  unit: "Unit 3",
  title: "Homework 3: Developing ideas (Listening and Speaking)",
  subtitle: "语音辨析 · in order to · 语法填空 · 翻译",
  source: "基础同步达标手册 七年级上（北京市三帆中学）",
  pages: "P42–P43",
  vocab: [
    { word: "queen", phonetic: "kwiːn", pos: "n.", meaning: "女王", use: "dress up as a queen 装扮成女王" },
    { word: "pick", phonetic: "pɪk", pos: "v.", meaning: "挑选，选择", use: "pick a colour 挑一种颜色" },
    { word: "pick up", phonetic: "pɪk ʌp", pos: "词组", meaning: "搭载，接载", use: "pick her up 接她；宾语是代词时放中间" },
    { word: "actress", phonetic: "ˈæktrɪs", pos: "n.", meaning: "女演员", use: "a good actress 一位好演员（男演员是 actor）" },
    { word: "change", phonetic: "tʃeɪndʒ", pos: "v.", meaning: "换（衣服）；改变", use: "change clothes 换衣服；change one's mind 改变主意" },
    { word: "advice", phonetic: "ədˈvaɪs", pos: "n.", meaning: "建议，忠告", use: "give sb advice on sth 就某事给某人建议" },
    { word: "solve", phonetic: "sɒlv", pos: "v.", meaning: "解决", use: "solve the problem 解决问题" },
    { word: "harmony", phonetic: "ˈhɑːməni", pos: "n.", meaning: "和谐", use: "Harmony is the most valuable. 和为贵。" },
    { word: "decision", phonetic: "dɪˈsɪʒn", pos: "n.", meaning: "决定", use: "make a decision 做出决定" },
    { word: "relationship", phonetic: "rɪˈleɪʃnʃɪp", pos: "n.", meaning: "关系", use: "family relationships 家庭关系" },
  ],
  phrases: [
    { en: "turn to", zh: "求助于；转向", tip: "turn to sb for help 向某人求助" },
    { en: "in order to", zh: "为了", tip: "in order to catch the first bus 为了赶上第一班公交车" },
    { en: "dress up as", zh: "装扮成", tip: "dress up as a queen 装扮成女王" },
    { en: "give advice on", zh: "就……给出建议", tip: "give advice on family relationships" },
    { en: "not ... any more", zh: "不再", tip: "I'm not a little girl any more." },
    { en: "pick up", zh: "搭载，接载", tip: "pick up two passengers 载两位乘客" },
    { en: "work out", zh: "解出，算出", tip: "work out this maths problem 解出这道数学题" },
    { en: "catch", zh: "赶上（车、船等）", tip: "catch the first bus 赶上第一班公交车" },
    { en: "cartoon characters", zh: "卡通人物", tip: "dress up as cartoon characters 装扮成卡通人物" },
  ],
  patterns: [
    { en: "Every day, she dresses up as a queen.", zh: "每天她都装扮成女王。", note: "dress up as + 身份/角色。" },
    { en: "In order to catch the first bus, Tom gets up very early every day.", zh: "为了赶上第一班公交车，汤姆每天起得很早。", note: "in order to + 动词原形，表目的。" },
    { en: "When I meet difficulties, I turn to my friends for help.", zh: "当我遇到困难时，我向我的朋友们求助。", note: "turn to sb for help 向某人求助。" },
    { en: "Many countries offer family hotlines to give advice on family relationships.", zh: "许多国家提供家庭热线，就家庭关系提供建议。", note: "give sb advice on sth 就某事给某人建议。" },
    { en: "The driver picked up two passengers.", zh: "这名司机载了两位乘客。", note: "pick up 接载；passenger 乘客。" },
    { en: "I'm not a little girl any more.", zh: "我不再是个小女孩了。", note: "not ... any more 不再。" },
    { en: "It is difficult for me to work out this maths problem.", zh: "解出这道数学题对我来说是困难的。", note: "It is + adj. + for sb + to do sth 句型。" },
  ],
  grammar: [
    {
      title: "字母组合的发音（语音辨析）",
      points: [
        "would /wʊd/、should /ʃʊd/ 中的 ou 读 /ʊ/；touch /tʌtʃ/ 中的 ou 读 /ʌ/；about /əˈbaʊt/ 中的 ou 读 /aʊ/。",
        "up、but、duck 中的 u 读 /ʌ/；use、unit 中的 u 读 /juː/；push 中的 u 读 /ʊ/。",
        "good、book 中的 oo 读 /ʊ/；cool 中的 oo 读 /uː/；door 中的 oor 读 /ɔː/。",
        "son 中的 o 读 /ʌ/；lose 中的 o 读 /uː/；hope 中的 o 读 /əʊ/。",
        "true、blue 中的 ue 读 /uː/；bus 中的 u 读 /ʌ/。",
      ],
    },
    {
      title: "不定式作目的状语",
      points: [
        "in order to + 动词原形，表示“为了……”，可放在句首或句中：In order to catch the first bus, Tom gets up early.",
        "表示“为了不……”用 in order not to do sth：He left early in order not to be late.",
        "so as to do sth 也表示目的，但一般不放在句首；to do sth 也可直接表目的。",
        "注意 in order to 后接动词原形，不能接 doing，也不能省略 to。",
      ],
    },
    {
      title: "advice 与 advise 的用法",
      points: [
        "advice 是不可数名词：a piece of advice 一条建议、some advice 一些建议，不能说 an advice 或 advices。",
        "give sb advice on sth 就某事给某人建议；ask sb for advice 向某人征求建议。",
        "动词形式是 advise：advise sb to do sth 建议某人做某事。",
      ],
    },
    {
      title: "not ... any more 与转变类动词",
      points: [
        "not ... any more 表示“不再”，any more 放在句末：I'm not a little girl any more.",
        "no more + 名词，表示“没有更多的……”：I have no more time.",
        "change 表示“改变、更换”：change one's mind 改变主意；change clothes 换衣服。",
        "make a decision 做出决定；solve the problem 解决问题。",
      ],
    },
  ],
  examPoints: [
    "语音题要先把划线字母组合读准，再逐个代入选项对比读音，注意 ou、oo、u、ue 都有多种读音。",
    "in order to 后接动词原形；in order not to do sth 表示“为了不……”。",
    "advice 不可数：a piece of advice、some advice；其动词形式是 advise sb to do sth。",
    "pick up 的宾语若是代词，代词必须放在 pick 和 up 之间：pick her up。",
    "dress up as + 角色/身份；dress up as a queen / cartoon characters。",
    "“不再”用 not ... any more，any more 位于句末。",
  ],
  sections: [
    {
      id: "words",
      title: "一、单词巩固（看音标和中文写单词）",
      type: "dictation",
      items: [
        { q: "[kwiːn] n. 女王", a: "queen", note: "dress up as a queen 装扮成女王" },
        { q: "[pɪk] v. 挑选，选择", a: "pick", note: "pick a colour 挑选一种颜色" },
        { q: "[pɪk ʌp]（词组）搭载，接载", a: "pick up", note: "宾语是代词时要放中间：pick her up" },
        { q: "[ˈæktrɪs] n. 女演员", a: "actress", note: "男演员是 actor" },
        { q: "[tʃeɪndʒ] v. 换（衣服）", a: "change", note: "change clothes 换衣服" },
      ],
    },
    {
      id: "phrases",
      title: "二、词组过关（按括号里的提示补全句子）",
      type: "fill",
      items: [
        { q: "Her mother often goes to ____ her ____（接）in this dress.", a: "pick up", zh: "她妈妈经常穿着这条裙子去接她。", note: "pick sb up 接某人；宾语是代词时放在 pick 和 up 中间。" },
        { q: "Who can you talk to ____ ____ ____（为了）____ ____ ____（解决问题）in your family?", a: "in order to solve the problem", zh: "在你的家里，你可以和谁交谈来解决问题？", note: "in order to + 动词原形 表目的；solve the problem 解决问题。" },
        { q: "Every day, she ____ ____（装扮成）as a queen.", a: "dresses up", zh: "每天她装扮成女王。", note: "every day 表习惯用一般现在时，主语 she 后用 dresses up。" },
        { q: "Many countries offer family hotlines to ____ ____ ____（给关于……的建议）family relationships.", a: "give advice on", zh: "许多国家提供家庭热线，为家庭关系提供建议。", note: "give sb advice on sth；advice 是不可数名词。" },
        { q: "I'm ____ a little girl ____ ____（不再）.", a: "not any more", zh: "我不再是个小女孩了。", note: "not ... any more 不再，any more 位于句末。" },
      ],
    },
    {
      id: "wordform",
      title: "三、根据句意、音标、首字母或汉语提示写单词",
      type: "fill",
      items: [
        { q: "I think Mary is a good ____ [ˈæktrɪs]. I like her movies very much.", a: "actress", zh: "我认为玛丽是位好演员，我非常喜欢她的电影。", note: "根据音标和句意可知填 actress（女演员）。" },
        { q: "I don't think we can ____ [tʃeɪndʒ] his mind if he has made a decision.", a: "change", zh: "我认为如果他已下定决心，我们无法改变他的主意。", note: "change one's mind 改变主意。" },
        { q: "The Chinese nation has the idea that “h____ is the most valuable”（和为贵）.", a: "harmony", zh: "中华民族有“和为贵”的思想。", note: "harmony 和谐；the most valuable 最宝贵的。" },
        { q: "Lily's dad always ____（接）Lily after she finishes school.", a: "picks up", zh: "莉莉的爸爸总是在她放学后接她。", note: "always 表习惯用一般现在时，主语是第三人称单数，用 picks up。" },
        { q: "Thank you for giving me the useful a____ to solve the problem.", a: "advice", zh: "谢谢你给我解决这个问题的有用建议。", note: "advice 不可数名词，可用 some useful advice。" },
      ],
    },
    {
      id: "phonetics",
      title: "四、选出与划线部分发音相同的单词",
      type: "choice",
      tip: "先读准题干的划线部分，再逐个代入选项对比读音。",
      items: [
        { q: "would（划线部分：ou）", options: ["about", "should", "touch"], a: "B", explain: "would 与 should 中的 ou 都读 /ʊ/；about 中 ou 读 /aʊ/，touch 中 ou 读 /ʌ/。" },
        { q: "up（划线部分：u）", options: ["but", "use", "push"], a: "A", explain: "up 与 but 中的 u 都读 /ʌ/；use 中的 u 读 /juː/，push 中的 u 读 /ʊ/。" },
        { q: "good（划线部分：oo）", options: ["book", "door", "cool"], a: "A", explain: "good 与 book 中的 oo 都读 /ʊ/；door 中的 oor 读 /ɔː/，cool 中的 oo 读 /uː/。" },
        { q: "son（划线部分：o）", options: ["lose", "hope", "duck"], a: "C", explain: "son 与 duck 中的 o、u 都读 /ʌ/；lose 中的 o 读 /uː/，hope 中的 o 读 /əʊ/。" },
        { q: "true（划线部分：ue）", options: ["bus", "blue", "unit"], a: "B", explain: "true 与 blue 中的 ue 都读 /uː/；bus 中的 u 读 /ʌ/，unit 中的 u 读 /juː/。" },
      ],
    },
    {
      id: "cloze",
      title: "五、语法填空（填入一个适当的词或括号中所给单词的正确形式）",
      type: "cloze",
      passage: [
        "Today I would like to tell you how to make a photo album (相册) about your family.",
        "1. {{1}} (one), think about your family and look at your family photos. What photos do you want 2. {{2}} (use)? Who are the family 3. {{3}} (member) in each photo? You can make a form.",
        "Second, write a paragraph with the help of the form. It is a good idea to describe your 4. {{4}} (family) support (支持). You can use the words and sentences 5. {{5}} the textbooks.",
        "At last, share 6. {{6}} (you) paragraph with teachers, classmates and friends. For Chinese, it's a bit 7. {{7}} (difficulty) to talk about family's love in public, but after sharing, I am sure you will know more about 8. {{8}} (happy).",
        "The photo album 9. {{9}} (help) you understand the meaning of a family and always brings you great 10. {{10}} (memory). How warm the photo album is!",
      ],
      blanks: [
        { n: 1, a: "First", hint: "one", explain: "句首用序数词表示“首先”，与后文 Second、At last 呼应。" },
        { n: 2, a: "use", hint: "use", explain: "want to do sth，用所给动词的原形。" },
        { n: 3, a: "members", hint: "member", explain: "每张照片里的家庭成员不止一个，用复数 members。" },
        { n: 4, a: "family's", hint: "family", explain: "“家人的支持”用名词所有格 family's support。" },
        { n: 5, a: "from", hint: "填一个适当的词", explain: "use the words and sentences from the textbooks 从课本中选用词句。" },
        { n: 6, a: "your", hint: "you", explain: "修饰名词 paragraph，用形容词性物主代词 your。" },
        { n: 7, a: "difficult", hint: "difficulty", explain: "a bit 后接形容词作表语，difficulty → difficult。" },
        { n: 8, a: "happiness", hint: "happy", explain: "know more about 后接名词，happy → happiness。" },
        { n: 9, a: "helps", hint: "help", explain: "主语 The photo album 是第三人称单数，用 helps。" },
        { n: 10, a: "memories", hint: "memory", explain: "great 后接可数名词复数，memory → memories。" },
      ],
    },
    {
      id: "translate",
      title: "六、根据中文意思和英文提示词语写出句子",
      type: "translate",
      items: [
        { zh: "当我遇到困难时，我向我的朋友寻求帮助。(turn to)", a: "When I meet difficulties, I turn to my friends for help.", note: "turn to sb for help 向某人求助；when 引导时间状语从句。" },
        { zh: "为了赶上第一班公交车，汤姆每天起得很早。(in order to; catch)", a: "In order to catch the first bus, Tom gets up very early every day.", note: "in order to + 动词原形 表目的，可放句首。" },
        { zh: "我喜欢装扮成卡通人物。(dress up as; cartoon characters)", a: "I like dressing up as cartoon characters.", note: "like doing sth 喜欢做某事；dress up as + 角色。" },
        { zh: "这名司机载了两位乘客。(pick up)", a: "The driver picked up two passengers.", note: "pick up 接载；注意用一般过去时 picked up。" },
        { zh: "解出这道数学题对我来说是困难的。(work out)", a: "It is difficult for me to work out this maths problem.", note: "It is + adj. + for sb + to do sth 句型。" },
      ],
    },
  ],
};
