// 七年级上册 Unit 3 Homework 4: Developing ideas (Reading for writing 1) —— P44–P46
export default {
  id: "tb7a-u3-4",
  book: "七年级上册",
  unit: "Unit 3",
  title: "Homework 4: Developing ideas (Reading for writing 1)",
  subtitle: "比较级 · 不定式作宾语 · 选词填空阅读",
  source: "基础同步达标手册 七年级上（北京市三帆中学）",
  pages: "P44–P46",
  vocab: [
    { word: "race", phonetic: "reɪs", pos: "v. & n.", meaning: "比赛", use: "race without his brother 不和他哥哥一起比赛；bike races 自行车比赛" },
    { word: "disease", phonetic: "dɪˈziːz", pos: "n.", meaning: "疾病，病", use: "heart disease 心脏病" },
    { word: "trailer", phonetic: "ˈtreɪlə", pos: "n.", meaning: "拖车，挂车", use: "pull Robert's trailer 拉罗伯特的拖车" },
    { word: "bright", phonetic: "braɪt", pos: "adj.", meaning: "欢快的；充满生气的", use: "a bright smile 欢快的笑容" },
    { word: "result", phonetic: "rɪˈzʌlt", pos: "n.", meaning: "结果，后果", use: "the result of the match 比赛的结果" },
    { word: "power", phonetic: "ˈpaʊə", pos: "v. & n.", meaning: "给（车辆或机器）提供动力；力量", use: "power me to go on 给我继续下去的动力" },
    { word: "serious", phonetic: "ˈsɪəriəs", pos: "adj.", meaning: "严重的；严肃的", use: "not serious 不严重" },
    { word: "stay", phonetic: "steɪ", pos: "v.", meaning: "停留，逗留，留下", use: "stay at home 待在家" },
    { word: "pull", phonetic: "pʊl", pos: "v.", meaning: "拉；扯；拖", use: "pull the trailer 拉拖车" },
    { word: "refuse", phonetic: "rɪˈfjuːz", pos: "v.", meaning: "拒绝，回绝", use: "refuse to do sth 拒绝做某事" },
    { word: "matter", phonetic: "ˈmætə", pos: "v.", meaning: "重要，要紧，有关系", use: "It doesn't matter. 没关系。" },
    { word: "alone", phonetic: "əˈləʊn", pos: "adv. & adj.", meaning: "独自，单独", use: "live alone 独自居住" },
    { word: "lonely", phonetic: "ˈləʊnli", pos: "adj.", meaning: "孤独的，寂寞的", use: "feel lonely 感到孤独" },
  ],
  phrases: [
    { en: "be close to each other", zh: "彼此亲近", tip: "They are always close to each other." },
    { en: "stay at home", zh: "待在家", tip: "He has to stay at home every day." },
    { en: "feel lonely", zh: "感到孤独", tip: "He often feels lonely." },
    { en: "for the first time", zh: "第一次", tip: "For the first time, Robert felt like the other kids." },
    { en: "feel like", zh: "感觉像", tip: "feel like the other kids 感觉像其他孩子一样" },
    { en: "It's hard for sb to do sth", zh: "对某人来说做某事很难", tip: "It was hard for John to pull Robert's trailer." },
    { en: "refuse to do sth", zh: "拒绝做某事", tip: "John refused to race without his brother." },
    { en: "take part in", zh: "参加", tip: "take part in outdoor activities 参加户外活动" },
    { en: "not ... at all", zh: "一点也不", tip: "I'm not hungry at all." },
    { en: "close to the seaside", zh: "靠近海边", tip: "This hotel is close to the seaside." },
  ],
  patterns: [
    { en: "They are always close to each other.", zh: "他们总是彼此亲近。", note: "be close to sb 与某人亲近，close 作形容词。" },
    { en: "He has to stay at home every day and he often feels lonely.", zh: "他每天不得不待在家里，而且他常常感到孤独。", note: "have to 不得不；feel lonely 感到孤独。" },
    { en: "For the first time, Robert felt like the other kids.", zh: "罗伯特第一次感觉自己和其他孩子一样。", note: "for the first time 第一次；feel like 感觉像。" },
    { en: "It was hard for John to pull Robert's trailer.", zh: "约翰很难拉动罗伯特的拖车。", note: "It is/was + adj. + for sb + to do sth 句型。" },
    { en: "But John refused to race without his brother.", zh: "但约翰拒绝在没有哥哥的情况下比赛。", note: "refuse to do sth 拒绝做某事，to 不能省略。" },
    { en: "Health is more important than money.", zh: "健康比金钱更重要。", note: "多音节形容词的比较级用 more + 原级 + than。" },
    { en: "Sometimes, the result doesn't matter.", zh: "有时候，结果并不重要。", note: "matter 作动词，意为“要紧”；主语是第三人称单数，用 doesn't matter。" },
  ],
  grammar: [
    {
      title: "形容词比较级",
      points: [
        "单音节词一般在词尾加 -er：bright → brighter、close → closer；以 e 结尾的加 -r。",
        "多音节词在词前加 more：more important、more serious、more beautiful。",
        "比较级 + than 表示“比……更……”：Health is more important than money.",
        "much / a bit / even 可以修饰比较级：he was much better。",
        "as + 原级 + as 表示同级比较：none of us can get up as early as he does。",
      ],
    },
    {
      title: "不定式作宾语",
      points: [
        "refuse to do sth 拒绝做某事；decide to do sth 决定做某事；plan to do sth 打算做某事。",
        "hope / want / would like to do sth 希望、想要做某事。",
        "注意搭配：enjoy doing sth、finish doing sth，但 refuse to do sth、decide to do sth。",
        "to 是不定式符号，后面接动词原形。",
      ],
    },
    {
      title: "系动词 + 形容词",
      points: [
        "feel / look / sound / taste / smell 等系动词后接形容词：feel lonely、taste better。",
        "形容词作表语，副词修饰动词，不要混用：He feels lonely.（不能说 feels lonelyly）。",
        "alone 表示“独自（的）”，不含感情色彩；lonely 表示孤单、寂寞，带有感情色彩。",
        "be close to 中的 close 是形容词，意为“近的、亲近的”。",
      ],
    },
    {
      title: "一般现在时与第三人称单数",
      points: [
        "主语是第三人称单数时，动词加 -s/-es：smile → smiles、go → goes、help → helps。",
        "否定句用 doesn't + 动词原形：Sometimes, the result doesn't matter.",
        "主语是复数或 I / you 时用动词原形：Tom and I always take part in bike races together.",
        "always、often、sometimes 等频度副词常与一般现在时连用。",
      ],
    },
  ],
  examPoints: [
    "take part in + 活动；bike races 用复数表示多场比赛。",
    "refuse to do sth 中 to 不能省略，也不能接 doing。",
    "alone（独自）与 lonely（孤独的）要区分：live alone but not feel lonely。",
    "not ... at all 一点也不，at all 放在句末。",
    "matter 作动词意为“要紧”，常用 It doesn't matter. 和 the result doesn't matter。",
    "比较级前可用 much / a bit / even 修饰，不能用 very。",
    "选词填空要先判断所填词的词性，再考虑时态、语态和词形变化（如 real → really、happy → happiness）。",
  ],
  sections: [
    {
      id: "words",
      title: "一、单词巩固（看音标和中文写单词）",
      type: "dictation",
      items: [
        { q: "[reɪs] v. 比赛 n. 比赛", a: "race", note: "bike races 自行车比赛" },
        { q: "[dɪˈziːz] n. 疾病，病", a: "disease", note: "heart disease 心脏病" },
        { q: "[ˈtreɪlə] n. 拖车，挂车", a: "trailer", note: "pull the trailer 拉拖车" },
        { q: "[braɪt] adj. 欢快的；充满生气的", a: "bright", note: "a bright smile 欢快的笑容" },
        { q: "[rɪˈzʌlt] n. 结果，后果", a: "result", note: "the result of the match 比赛结果" },
        { q: "[ˈpaʊə] v. 给（车辆或机器）提供动力", a: "power", note: "power me to go on 给我继续下去的动力" },
        { q: "[ˈsɪəriəs] adj. 严重的", a: "serious", note: "not serious 不严重" },
        { q: "[steɪ] v. 停留，逗留，留下", a: "stay", note: "stay at home 待在家" },
        { q: "[pʊl] v. 拉；扯；拖", a: "pull", note: "pull the trailer 拉拖车" },
        { q: "[rɪˈfjuːz] v. 拒绝，回绝", a: "refuse", note: "refuse to do sth 拒绝做某事" },
        { q: "[ˈmætə] v. 重要，要紧，有关系", a: "matter", note: "It doesn't matter. 没关系。" },
      ],
    },
    {
      id: "phrases",
      title: "二、词组过关（按括号里的提示补全句子）",
      type: "fill",
      items: [
        { q: "They ____ ____ ____（与……亲近）each other.", a: "are close to", zh: "他们总是彼此亲近。", note: "be close to sb 与某人亲近；主语是 they，用 are。" },
        { q: "He has to ____ ____ ____（待在家）every day and he often ____ ____（感到孤独）.", a: "stay at home feels lonely", zh: "他每天不得不待在家里，而且常常感到孤独。", note: "待在家用 stay at home；感到孤独用 feel lonely，主语 he 后用 feels。" },
        { q: "____ ____ ____ ____（第一次）, Robert ____ ____（感觉像）the other kids.", a: "For the first time felt like", zh: "罗伯特第一次感觉自己和其他孩子一样。", note: "for the first time 首字母大写；feel like 用过去式 felt like。" },
        { q: "It ____ ____ for John ____ pull Robert's trailer.（对某人来说做某事很难）", a: "is hard to", accept: ["was hard to"], zh: "约翰很难拉动罗伯特的拖车。", note: "It is/was + adj. + for sb + to do sth 句型；故事发生在过去，也可用 was。" },
        { q: "But John ____ ____（拒绝）race without his brother.", a: "refused to", zh: "但约翰拒绝在没有哥哥的情况下比赛。", note: "refuse to do sth 拒绝做某事，用过去式 refused to。" },
      ],
    },
    {
      id: "wordform",
      title: "三、根据句意、音标、首字母或汉语提示写单词",
      type: "fill",
      items: [
        { q: "It doesn't m____ to make mistakes when growing up.", a: "matter", zh: "成长过程中犯错没有关系。", note: "It doesn't matter 没关系；matter 作动词，意为“要紧”。" },
        { q: "They all feel sad about the ____（结果）of the school basketball match.", a: "result", zh: "他们都为校篮球赛的结果感到难过。", note: "the result of ……的结果。" },
        { q: "David is really tired after the 1,000-metre r____.", a: "race", zh: "大卫跑完 1000 米比赛后真的累了。", note: "1,000-metre race 1000 米赛跑。" },
        { q: "The hot weather is bad for your heart ____ [dɪˈziːz].", a: "disease", zh: "炎热的天气对你的心脏疾病不利。", note: "heart disease 心脏病。" },
        { q: "John got hurt in the basketball match, but luckily, it was not ____ [ˈsɪəriəs].", a: "serious", zh: "约翰在篮球赛中受伤了，但幸运的是，伤得不重。", note: "not serious 不严重。" },
      ],
    },
    {
      id: "formfill",
      title: "四、用所给词的适当形式填空",
      type: "fill",
      items: [
        { q: "Lucy always ____ (smile) at others.", a: "smiles", zh: "露西总是对别人微笑。", note: "主语 Lucy 是第三人称单数，用 smiles。" },
        { q: "Health is ____ (important) than money.", a: "more important", zh: "健康比金钱更重要。", note: "多音节形容词的比较级用 more important。" },
        { q: "You shouldn't refuse ____ (help) others. You will also need help some day.", a: "to help", zh: "你不应该拒绝帮助别人，有一天你也会需要帮助。", note: "refuse to do sth 拒绝做某事。" },
        { q: "Go and enjoy the game. Sometimes, the result ____ (not matter).", a: "doesn't matter", zh: "去享受比赛吧，有时候结果并不重要。", note: "主语 the result 是第三人称单数，否定用 doesn't matter。" },
        { q: "Tom and I always take part in bike ____ (race) together.", a: "races", zh: "汤姆和我总是一起参加自行车比赛。", note: "bike races 用复数表示多场比赛。" },
      ],
    },
    {
      id: "translate",
      title: "五、根据中文意思和英文提示词语写出句子",
      type: "translate",
      items: [
        { zh: "我爷爷独自居住，但他并不感到孤单。(alone; lonely)", a: "My grandpa lives alone, but he doesn't feel lonely.", note: "live alone 独自居住；feel lonely 感到孤独。" },
        { zh: "我一点也不饿。(not ... at all)", a: "I'm not hungry at all.", note: "not ... at all 一点也不，at all 放在句末。" },
        { zh: "这周末我打算参加一些户外活动。(take part in)", a: "I'm going to take part in some outdoor activities this weekend.", note: "take part in + 活动；outdoor activities 户外活动。" },
        { zh: "别担心，我们会找到办法的。(way)", a: "Don't worry. We will find a way.", note: "find a way 找到办法。" },
        { zh: "这家酒店靠近海边。(close; seaside)", a: "This hotel is close to the seaside.", note: "be close to 靠近；seaside 海边。" },
      ],
    },
    {
      id: "reading",
      title: "六、阅读加油站（Food made by loved ones tastes better：选词填空）",
      type: "cloze",
      tip: "易读度 81.1，词数 249。从下面方框中选出 10 个单词，用它们的正确形式填入短文，使短文意思正确通顺（每词限用一次）。方框：same; use; when; eat; they; real; everyone; special; food; make; about; scientist（有 2 个词是多余的）",
      passage: [
        "Many people think their mother makes the best food in the world. A new study has found that this may be true for {{1}}.",
        "Of course, it's hard to decide what the “best food in the world” {{2}} is. But the study, done in the UK, showed something interesting. People found food made by loved ones tasted better than other food.",
        "In the study, people were blindfolded (被蒙上眼睛的) and {{3}} two cakes. Both cakes used the {{4}} recipe (食谱), but one was made by a professional cook and the other was made by someone they knew, such as their mother.",
        "{{5}} checked the heart rates (检查心率) of the eaters and watched their faces while they ate. Every person liked the home-made cake better. {{6}} they ate the home-made cake, their hearts beat (跳动) faster. They also smiled more.",
        "People also answered questions {{7}} home cooking. One out of three said {{8}} mothers' food tasted best. And 90% said food tasted better when it was made by someone they loved.",
        "And it's not just eating the food — 40% also said baking with a loved one helped them feel closer, and 67% said they enjoyed {{9}} family recipes.",
        "“Baking is not just about taste or skill. It is about the love and care you put in. That is what people taste. That is what makes home-made food so {{10}},” said Charles Spence, one of the scientists.",
      ],
      blanks: [
        { n: 1, a: "everyone", hint: "everyone", explain: "“这可能对每个人都成立”，用 everyone。" },
        { n: 2, a: "really", hint: "real", explain: "修饰 be 动词 is，用副词 really，意为“真正地”。" },
        { n: 3, a: "ate", hint: "eat", explain: "与 were blindfolded 并列，叙述过去的事，用过去式 ate。" },
        { n: 4, a: "same", hint: "same", explain: "两个蛋糕用的是同一份食谱，用 the same recipe。" },
        { n: 5, a: "Scientists", hint: "scientist", explain: "做研究的科学家不止一位，用复数 Scientists，句首首字母大写。" },
        { n: 6, a: "When", hint: "when", explain: "“……的时候”，用 when 引导时间状语从句，句首大写。" },
        { n: 7, a: "about", hint: "about", explain: "answer questions about sth 回答关于……的问题。" },
        { n: 8, a: "their", hint: "they", explain: "修饰名词 mothers，用形容词性物主代词 their。" },
        { n: 9, a: "making", hint: "make", explain: "enjoy doing sth 喜欢做某事，用 making。" },
        { n: 10, a: "special", hint: "special", explain: "make + 宾语 + 形容词，用 special 作宾补。" },
      ],
    },
  ],
};
