// 七年级上册 Unit 3 Homework 5: Developing ideas (Reading for writing 2) —— P47–P50
export default {
  id: "tb7a-u3-5",
  book: "七年级上册",
  unit: "Unit 3",
  title: "Homework 5: Developing ideas (Reading for writing 2)",
  subtitle: "单元写作：Family Members' Support · 阅读加油站",
  source: "基础同步达标手册 七年级上（北京市三帆中学）",
  pages: "P47–P50",
  vocab: [
    { word: "share", phonetic: "ʃeə", pos: "v.", meaning: "分享", use: "share sth with sb 与某人分享某物" },
    { word: "problem", phonetic: "ˈprɒbləm", pos: "n.", meaning: "问题，困难", use: "have a problem with ... 在……方面有困难" },
    { word: "worry", phonetic: "ˈwʌri", pos: "n. & v.", meaning: "担心，忧虑", use: "Seeing my worry ... 看到我的担心……" },
    { word: "prepare", phonetic: "prɪˈpeə", pos: "v.", meaning: "准备", use: "prepare dinner 准备晚饭" },
    { word: "smile", phonetic: "smaɪl", pos: "v. & n.", meaning: "微笑", use: "smile at sb 对某人微笑" },
    { word: "patiently", phonetic: "ˈpeɪʃntli", pos: "adv.", meaning: "耐心地", use: "help sb patiently 耐心地帮助某人" },
    { word: "encourage", phonetic: "ɪnˈkʌrɪdʒ", pos: "v.", meaning: "鼓励", use: "encourage sb to do sth 鼓励某人做某事" },
    { word: "calm", phonetic: "kɑːm", pos: "v. & adj.", meaning: "使镇静；镇静的", use: "calm down 冷静下来" },
    { word: "safe harbor", phonetic: "seɪf ˈhɑːbə", pos: "词组", meaning: "安全的港湾", use: "my family is my safe harbor 家是我安全的港湾" },
    { word: "difference", phonetic: "ˈdɪfrəns", pos: "n.", meaning: "影响；不同", use: "make a big difference 起很大作用" },
    { word: "backup", phonetic: "ˈbækʌp", pos: "n.", meaning: "后援；支持", use: "my strongest backup 我最坚强的后盾" },
    { word: "company", phonetic: "ˈkʌmpəni", pos: "n.", meaning: "陪伴", use: "because of their company 因为他们的陪伴" },
    { word: "confident", phonetic: "ˈkɒnfɪdənt", pos: "adj.", meaning: "自信的", use: "make me feel confident 让我感到自信" },
    { word: "courage", phonetic: "ˈkʌrɪdʒ", pos: "n.", meaning: "勇气", use: "turn anxiety into courage 把焦虑变成勇气" },
  ],
  phrases: [
    { en: "share sth with sb", zh: "与某人分享某物", tip: "share both good and bad things with my parents" },
    { en: "have a problem with ...", zh: "在……方面遇到问题/困难", tip: "have a problem with my schoolwork 功课上有困难" },
    { en: "encourage sb to do sth", zh: "鼓励某人做某事", tip: "encourage me to be confident 鼓励我自信一些" },
    { en: "calm down", zh: "冷静下来", tip: "Their actions calmed me down greatly." },
    { en: "safe harbor", zh: "安全的港湾", tip: "My family is my safe harbor." },
    { en: "make a big difference", zh: "起很大作用；产生重大影响", tip: "even small acts of care can make a big difference" },
    { en: "backup", zh: "后援；支持", tip: "my strongest backup 我最坚强的后盾" },
    { en: "company", zh: "陪伴", tip: "because of their company and support 因为他们的陪伴和支持" },
    { en: "power sb to do sth", zh: "给某人做某事的动力", tip: "powered me to do my best 给我做到最好的动力" },
  ],
  patterns: [
    { en: "I'd like to share how my family members support each other.", zh: "我想分享我的家人是如何相互支持的。", note: "I'd like to do sth 我想做某事；how 引导宾语从句。" },
    { en: "Every day after school, my parents prepare dinner and we talk about our day.", zh: "每天放学后，我父母准备晚饭，我们聊聊各自的一天。", note: "every day 表日常，用一般现在时。" },
    { en: "If I have a problem with my schoolwork, my father patiently helps me.", zh: "如果我的功课遇到问题，我爸爸会耐心地帮助我。", note: "if 引导条件状语从句，主句用一般现在时表习惯。" },
    { en: "Last month, I was very nervous before the English speech contest.", zh: "上个月，英语演讲比赛前我非常紧张。", note: "回忆具体往事用一般过去时。" },
    { en: "Seeing my worry, my mother smiled at me and encouraged me to be confident.", zh: "看到我的担心，妈妈对我微笑，并鼓励我要自信。", note: "Seeing my worry 是现在分词短语作状语。" },
    { en: "Their actions calmed me down greatly and powered me to do my best.", zh: "他们的举动让我大大地平静下来，也给了我做到最好的动力。", note: "power sb to do sth 给某人做某事的动力。" },
    { en: "I think my family is my safe harbor.", zh: "我认为我的家是我安全的港湾。", note: "表达感受时用 I think ... 引出自己的看法。" },
  ],
  grammar: [
    {
      title: "单元写作：三段式结构",
      points: [
        "第一段点明主题：I'd like to share how my family members support each other.",
        "第二段介绍家人之间相互支持：可以先写日常、经常性的帮助，再举一个具体例子。",
        "第三段表达感受：I think my family is my safe harbor. / It teaches me that even small acts of care can make a big difference.",
        "每一段的第一句写主旨句，段落围绕主旨句展开。",
      ],
    },
    {
      title: "时态的选择",
      points: [
        "描述家人之间日常、经常性的支持行为，用一般现在时。",
        "通过回忆具体往事来体现亲情，用一般过去时。",
        "同一段内不要混用两种时态：先说清楚是“每天都……”还是“上个月有一次……”。",
      ],
    },
    {
      title: "常用表达与句型",
      points: [
        "make sb do sth / make sb + 形容词：Their support makes me feel loved and confident.",
        "It is/was hard for sb to do sth：It was hard for me to fall asleep.",
        "power / encourage sb to do sth 表示给人力量、鼓励。",
        "It teaches me that ... 用来总结感受与收获。",
      ],
    },
    {
      title: "点明主题与收尾",
      points: [
        "开头自我介绍并点题：I am Li Hua from Hongxing Middle School. I'd like to share how ...",
        "结尾可以用 safe harbor、strongest backup、company and support 等短语表达对家人的感激。",
        "写完后按评价表自评：格式规范、结构清晰、要点齐全、人称时态正确、语言准确、语言丰富。",
      ],
    },
  ],
  examPoints: [
    "写作前先列提纲（点明主题—举例介绍—表达感受），每段第一句写主旨句。",
    "日常支持用一般现在时，具体的一次经历用一般过去时。",
    "提示词语仅供选用，不要逐词对译；注意 problem with、encourage sb to do sth 等固定搭配。",
    "人称以第一人称为主；介绍自己时可用 I am Li Hua from ...。",
    "字数不少于 50 词，写完后检查拼写、标点和时态是否一致。",
    "阅读篇目中的 sign、notice、miss、head out 等词要会认会读。",
  ],
  sections: [
    {
      id: "words",
      title: "一、写作必备词汇（看中文写英文）",
      type: "dictation",
      items: [
        { q: "①分享", a: "share", note: "share sth with sb 与某人分享某物" },
        { q: "②在……方面遇到问题/困难", a: "have a problem with ...", note: "have a problem with my schoolwork" },
        { q: "③耐心地", a: "patiently", note: "help sb patiently 耐心地帮助某人" },
        { q: "④鼓励某人做某事", a: "encourage sb to do sth", note: "encourage sb to do sth 中 to 不能省略" },
        { q: "⑤冷静下来", a: "calm down", note: "Their actions calmed me down." },
        { q: "⑥安全的港湾（提供庇护和安慰的地方或人）", a: "safe harbor", note: "My family is my safe harbor." },
        { q: "⑦起很大作用；产生重大影响", a: "make a big difference", note: "even small acts of care can make a big difference" },
        { q: "⑧后援；支持", a: "backup", note: "my strongest backup 我最坚强的后盾" },
        { q: "⑨陪伴", a: "company", note: "because of their company 因为他们的陪伴" },
      ],
    },
    {
      id: "writing",
      title: "二、单元写作（Family Members' Support）",
      tip: "体裁：记叙文；时态：一般现在时或一般过去时为主；人称：第一人称为主；不少于 50 词。提示词语：problem, worry, prepare, smile, help, love, power, confident。写完后按评价表自评：格式规范（1分）、结构清晰（2分）、要点齐全（2分）、人称时态（2分）、语言准确（2分）、语言丰富（1分）。",
      type: "translate",
      items: [
        {
          zh: "【写作任务】家人的支持是我们生活中最温暖的力量，它常常体现在那些彼此陪伴、共度难关的时刻。假设你是红星中学的学生李华，请你以 “Family Members' Support” 为题，用英语写一篇短文，讲述一个你家庭相互支持的事并表达你的感受。你可以讲述日常生活中的事情，也可以回忆具体的经历。提示问题：①Who are the family members? ②What do/did your family members do to support each other? ③What do you think of the family members?",
          a: "Family Members' Support  I am Li Hua from Hongxing Middle School. I'd like to share how my family members support each other.  Every day after school, my parents prepare dinner and we talk about our day. We share both happy and sad things with each other. If I have a problem with my schoolwork, my father patiently helps me. We are always close to each other.  Last month, I was very nervous before the English speech contest. It was hard for me to fall asleep. Seeing my worry, my mother smiled at me and encouraged me to be confident. My father even prepared a small card for me. Their actions calmed me down greatly and powered me to do my best.  I think my family is my safe harbor. Their daily support makes me feel loved and confident. It teaches me that even small acts of care can make a big difference.",
          note: "范文按“点明主题—介绍家人之间的相互帮助（日常 + 一次具体经历）—表达感受”三段展开，注意日常用一般现在时、回忆用一般过去时。",
        },
        {
          zh: "【段落提纲】第一段：点明主题——I am Li Hua from Hongxing Middle School. I'd like to share how my family members support each other.",
          a: "I am Li Hua from Hongxing Middle School. I'd like to share how my family members support each other.",
          note: "自我介绍后直接点明主题，注意校名和姓名的英文写法。",
        },
        {
          zh: "【段落提纲】第二段（日常）：介绍家人之间日常、经常性的相互帮助——Every day after school, my parents ... We talk about ... and share both ... and ... things. If I have a problem with my ..., my ... patiently helps me. We are always close to each other.",
          a: "Every day after school, my parents prepare dinner and we talk about our day. We share both happy and sad things with each other. If I have a problem with my schoolwork, my father patiently helps me. We are always close to each other.",
          note: "用 every day / always 等词配合一般现在时，写出经常性的支持。",
        },
        {
          zh: "【段落提纲】第二段（举例）：回忆一次具体的经历——Last month, I was very nervous before ... It was hard for me to ... Seeing my worry, my father ... me, and my mother ... My ... even made a ... for me. Their actions calmed me down greatly and powered me to ...",
          a: "Last month, I was very nervous before the English speech contest. It was hard for me to fall asleep. Seeing my worry, my mother smiled at me and encouraged me to be confident. My father even prepared a small card for me. Their actions calmed me down greatly and powered me to do my best.",
          note: "回忆具体往事要用一般过去时，可用 It was hard for me to ... 表达困难。",
        },
        {
          zh: "【段落提纲】第三段：表达感受与看法——I think my family is my safe harbor. Their daily support makes me feel loved and confident. It teaches me that even small acts of care can make a big difference.",
          a: "I think my family is my safe harbor. Their daily support makes me feel loved and confident. It teaches me that even small acts of care can make a big difference.",
          note: "结尾用 I think ... / It teaches me that ... 总结感受，点明家人支持的意义。",
        },
        {
          zh: "【备选结尾】I think my family is my strongest backup. With my family members, I feel all my anxiety can turn into courage because of their company and support.",
          a: "I think my family is my strongest backup. With my family members, I feel all my anxiety can turn into courage because of their company and support.",
          note: "换一个结尾句式，可以让文章更有文采，注意 anxiety、courage 的拼写。",
        },
      ],
    },
    {
      id: "reading",
      title: "三、阅读加油站（Start your own ColourWalk）",
      tip: "易读度 89.5，词数 256。先读文章，再根据提示描述你自己的 ColourWalk 经历。WORD BANK：pick /pɪk/ v. 选择；head out 出发；sign /saɪn/ n. 指示牌；notice /ˈnəʊtɪs/ v. 注意到；miss /mɪs/ v. 错过。",
      type: "translate",
      passage: [
        "A new kind of walk is becoming popular. It is called a ColourWalk and is a simple and relaxing way to enjoy the city.",
        "Here is how it works: First, pick a colour. Then go for a walk outside. As you walk, look for things in that colour. There is no need to plan a route (路线) or have a destination (目的地). Just pick a colour and head out. While walking, take your time and look closely. This helps you slow down and enjoy the moment.",
        "Many people share their ColourWalk stories online. For example, Ms. Kang often felt worried because of work. One day, she tried a ColourWalk and picked green. For 20 minutes, she only looked for green things. She found a green swing (秋千) in the park, green signs in the subway, and a green coffee bag. She also had a matcha cake (抹茶蛋糕). Slowly, she began to feel better.",
        "Another story is about a student. During exam time, she felt tired. So she went out to find yellow things. She saw sunsets, yellow flowers, and warm yellow signs. She saw many nice things she did not notice before. She felt much happier.",
        "The goal is not to pick the “right” colour. It is to slow down and notice the beauty we often miss. On busy days, give yourself 20 minutes. Let go of all your troubles. Just focus on how you feel and look at the colours around you. This can be a simple way to feel better.",
      ],
      items: [
        { zh: "【叙述经历】When and where did you go?（什么时候、去了哪里？）", a: "Last Sunday afternoon, I went for a ColourWalk in the park near my home.", note: "用一般过去时写时间、地点，注意时态一致。" },
        { zh: "【叙述经历】What colour did you choose? Why?（你选了哪种颜色？为什么？）", a: "I chose green, because green makes me feel relaxed and peaceful.", note: "用 because 说明理由，注意 choose 的过去式 chose。" },
        { zh: "【叙述经历】What did you find?（你发现了什么？）", a: "I found green trees, green swings and a green coffee bag. I also noticed some small green signs on the wall.", note: "用 found / noticed 等过去式动词，列举具体事物。" },
        { zh: "【叙述经历】How did you feel after the walk?（走完之后你有什么感受？）", a: "After the walk, I felt much happier and calmer. I slowed down and noticed the beauty around me.", note: "用比较级 much happier 表达感受，呼应文章结尾。" },
      ],
    },
  ],
};
